// Reading task formats (情報検索, 統合理解, 長文). Original practice material; see formats.cjs for the entry shape.
module.exports = {
N5: [],
N4: [
['info-search', 'reading', 'Die Stadtbibliothek', 'Öffnungszeiten, Ausleihgrenzen und Rückgabe in einem Aushang kombinieren.',
['さくら{市立|しりつ}{図書館|としょかん}　ご{利用|りよう}{案内|あんない}\n・{開館|かいかん}{時間|じかん}：{火曜日|かようび}〜{金曜日|きんようび}　{午前|ごぜん}{九時|くじ}〜{午後|ごご}{七時|しちじ}\n　{土曜日|どようび}・{日曜日|にちようび}　{午前|ごぜん}{九時|くじ}〜{午後|ごご}{五時|ごじ}\n・{休館日|きゅうかんび}：{月曜日|げつようび}\n・{本|ほん}は{一人|ひとり}{十冊|じゅっさつ}まで、{二週間|にしゅうかん}{借|か}りられます。\n・{雑誌|ざっし}は{一人|ひとり}{三冊|さんさつ}まで、{一週間|いっしゅうかん}です。\n・{本|ほん}や{雑誌|ざっし}を{返|かえ}すときは、{入|い}り{口|ぐち}の{横|よこ}の「{返却|へんきゃく}ポスト」に{入|い}れることもできます。{休館日|きゅうかんび}も{使|つか}えます。'],
'Städtische Bibliothek Sakura – Benutzungshinweise. Öffnungszeiten: Dienstag bis Freitag 9 bis 19 Uhr, Samstag und Sonntag 9 bis 17 Uhr. Schließtag: Montag. Bücher: bis zu zehn pro Person für zwei Wochen. Zeitschriften: bis zu drei pro Person für eine Woche. Bücher und Zeitschriften kann man auch in die Rückgabebox neben dem Eingang werfen; sie ist auch am Schließtag nutzbar.',
[['返却（へんきゃく）ポスト', 'Rückgabebox'], ['休館日（きゅうかんび）', 'Schließtag'], ['雑誌（ざっし）', 'Zeitschrift']],
'Bei Aushängen musst du oft zwei Angaben verbinden: Wochentag und Uhrzeit, Obergrenze und Art des Mediums. Lies jede Zeile einzeln und prüfe dann die Kombination.', [
['Frau Lee arbeitet bis 18 Uhr und ist frühestens um 18:30 Uhr in der Bibliothek. An welchen Tagen kann sie hineingehen?', 0, ['Von Dienstag bis Freitag.', 'Nur an diesen Tagen ist bis 19 Uhr (午後七時) geöffnet.'], ['Am Samstag und Sonntag.', 'Am Wochenende schließt die Bibliothek schon um 17 Uhr.'], ['Am Montag.', 'Montag ist Schließtag.'], ['An jedem Tag der Woche.', 'Montags ist geschlossen, am Wochenende schließt sie zu früh.']],
['Ken möchte zwölf Bücher und zwei Zeitschriften ausleihen. Wie viel davon kann er höchstens auf einmal ausleihen?', 0, ['Zehn Bücher und zwei Zeitschriften.', 'Bücher sind auf zehn begrenzt, zwei Zeitschriften liegen unter der Grenze von drei.'], ['Zwölf Bücher und zwei Zeitschriften.', 'Mehr als zehn Bücher sind nicht erlaubt.'], ['Zehn Bücher, aber keine Zeitschriften.', 'Die zwei Zeitschriften kann er zusätzlich ausleihen; für sie gilt eine eigene Grenze von drei.'], ['Drei Bücher und zwei Zeitschriften.', 'Drei ist die Grenze für Zeitschriften, nicht für Bücher.']],
['Ken will seine Bücher an einem Montag zurückgeben. Was kann er tun?', 0, ['Sie in die Rückgabebox neben dem Eingang werfen.', 'Die Box ist ausdrücklich auch am Schließtag nutzbar.'], ['Er muss bis Dienstag warten, weil montags keine Rückgabe möglich ist.', 'Die Rückgabebox funktioniert auch am Montag.'], ['Er gibt sie am Schalter im Inneren ab.', 'Montags ist die Bibliothek geschlossen.'], ['Er schickt sie per Post an die Bibliothek.', 'Eine Rückgabe per Post wird nicht erwähnt.']]
]],
['info-search', 'reading', 'Preise im Sportzentrum', 'Preise, Altersgrenzen und Sonderregeln eines Sportzentrums anwenden.',
['みどりスポーツセンター　{料金|りょうきん}のご{案内|あんない}\n・プール（{一回|いっかい}{二時間|にじかん}まで）：{大人|おとな}{四百円|よんひゃくえん}　{中学生|ちゅうがくせい}{以下|いか}{二百円|にひゃくえん}\n・トレーニングルーム（{一回|いっかい}）：{三百円|さんびゃくえん}　※{十六歳|じゅうろくさい}{以上|いじょう}の{方|かた}だけ{使|つか}えます。\n・プールの{回数券|かいすうけん}：{大人|おとな}{十一回分|じゅういっかいぶん}を{四千円|よんせんえん}で{売|う}っています。\n・{毎月|まいつき}{第一|だいいち}{日曜日|にちようび}は、{市|し}に{住|す}んでいる{人|ひと}はプールが{無料|むりょう}です。\n・{月曜日|げつようび}はお{休|やす}みです。'],
'Sportzentrum Midori – Preise. Schwimmbad (pro Besuch bis zu zwei Stunden): Erwachsene 400 Yen, Mittelschüler und Jüngere 200 Yen. Fitnessraum (pro Besuch): 300 Yen, nur ab 16 Jahren. Mehrfachkarte fürs Schwimmbad: elf Besuche für Erwachsene für 4000 Yen. Am ersten Sonntag jedes Monats ist das Schwimmbad für Einwohner der Stadt kostenlos. Montags geschlossen.',
[['回数券（かいすうけん）', 'Mehrfachkarte'], ['以下（いか）／以上（いじょう）', 'höchstens … / mindestens …'], ['無料（むりょう）', 'kostenlos']],
'以下 und 以上 schließen die genannte Zahl ein: 十六歳以上 bedeutet „16 Jahre und älter“. Prüfe bei Sonderregeln immer, für wen und wann sie gelten.', [
['Eine Mutter geht mit ihrem Sohn (Grundschüler) an einem gewöhnlichen Samstag schwimmen. Wie viel zahlen beide zusammen?', 0, ['600 Yen.', '400 Yen für die Mutter und 200 Yen für das Kind (中学生以下).'], ['800 Yen.', 'Das Kind zahlt nicht den Erwachsenenpreis.'], ['400 Yen.', 'Auch das Kind muss bezahlen.'], ['Nichts.', 'Kostenlos ist es nur am ersten Sonntag für Einwohner.']],
['Wer darf den Fitnessraum NICHT benutzen?', 0, ['Ein 15-jähriger Schüler.', 'Der Fitnessraum ist erst ab 16 Jahren (十六歳以上) erlaubt.'], ['Eine 16-jährige Schülerin.', '以上 schließt die 16 ein.'], ['Ein 70-jähriger Rentner.', 'Eine obere Altersgrenze gibt es nicht.'], ['Ein Erwachsener aus einer anderen Stadt.', 'Der Wohnort spielt nur beim kostenlosen Sonntag im Schwimmbad eine Rolle.']],
['Wie viel spart ein Erwachsener mit der Mehrfachkarte gegenüber elf Einzelbesuchen im Schwimmbad?', 0, ['400 Yen.', 'Elf Einzelbesuche kosten 4400 Yen, die Karte 4000 Yen.'], ['1100 Yen.', 'So viel wäre es nur bei einem anderen Einzelpreis.'], ['Nichts, beides kostet gleich viel.', '11 × 400 Yen sind mehr als 4000 Yen.'], ['4000 Yen.', '4000 Yen ist der Preis der Karte, nicht die Ersparnis.']]
]]
],
N3: [
['info-search', 'reading', 'Kurse im Bürgerzentrum', 'Aus einem Kursangebot den passenden Kurs nach mehreren Bedingungen auswählen.',
['ひまわり市民センター　秋の講座（10月〜12月）\n①はじめての中国語　火曜日　19:00〜20:30　全10回　8,000円　定員15名\n②家庭で作る和菓子　土曜日　10:00〜12:00　全5回　6,500円（材料費込み・作った菓子は持ち帰り可）　定員12名\n③スマホ写真教室　水曜日　14:00〜15:30　全6回　4,000円　定員20名　※スマートフォンを持参\n④やさしいヨガ　日曜日　9:00〜10:00　全8回　5,000円　定員25名\n・申し込みは9月20日まで。定員を超えた場合は抽選となります。\n・市内に住んでいる方、または市内に在勤の方は、受講料が1割引になります。'],
'Bürgerzentrum Himawari – Herbstkurse (Oktober bis Dezember). ① Chinesisch für Anfänger: dienstags 19:00–20:30, 10 Termine, 8000 Yen, 15 Plätze. ② Japanische Süßigkeiten selbst gemacht: samstags 10:00–12:00, 5 Termine, 6500 Yen (inklusive Material, die Süßigkeiten dürfen mitgenommen werden), 12 Plätze. ③ Fotografieren mit dem Smartphone: mittwochs 14:00–15:30, 6 Termine, 4000 Yen, 20 Plätze, Smartphone mitbringen. ④ Sanftes Yoga: sonntags 9:00–10:00, 8 Termine, 5000 Yen, 25 Plätze. Anmeldung bis 20. September; bei mehr Anmeldungen als Plätzen wird gelost. Wer in der Stadt wohnt oder arbeitet, erhält 10 % Rabatt.',
[['定員（ていいん）', 'Höchstzahl der Teilnehmenden'], ['抽選（ちゅうせん）', 'Auslosung'], ['在勤（ざいきん）', 'dort beschäftigt sein']],
'In Kurslisten stehen Tag, Uhrzeit, Preis und Sonderregeln oft in einer Zeile. Streiche zuerst die Kurse, die eine Bedingung verletzen, und rechne erst dann.', [
['Frau Sato arbeitet werktags bis 18 Uhr. Sie möchte am Wochenende etwas lernen und am Ende etwas Essbares mit nach Hause nehmen. Welcher Kurs passt?', 0, ['②, der Kurs für japanische Süßigkeiten.', 'Er findet samstags statt, und die Süßigkeiten dürfen mitgenommen werden.'], ['④, das Yoga am Sonntag.', 'Der Termin passt, aber man nimmt nichts Essbares mit.'], ['①, der Chinesischkurs.', 'Er findet dienstags statt, nicht am Wochenende.'], ['③, der Fotokurs.', 'Mittwoch um 14 Uhr ist während ihrer Arbeitszeit.']],
['Herr Kim wohnt in der Nachbarstadt, arbeitet aber in dieser Stadt. Wie viel kostet Kurs ③ für ihn?', 0, ['3600 Yen.', 'Wer in der Stadt arbeitet (在勤), erhält 10 % Rabatt auf 4000 Yen.'], ['4000 Yen.', 'Der Rabatt gilt auch für Menschen, die nur in der Stadt arbeiten.'], ['3000 Yen.', 'Der Rabatt beträgt 1割, also 10 %, nicht 25 %.'], ['2000 Yen.', 'Es gibt keinen Rabatt von 50 %.']],
['Für Kurs ② melden sich 20 Personen an. Was passiert?', 0, ['Es wird ausgelost, wer teilnehmen darf.', 'Bei mehr Anmeldungen als Plätzen (定員12名) entscheidet das Los.'], ['Der Kurs wird zweimal angeboten.', 'Ein zweiter Termin wird nicht erwähnt.'], ['Die ersten zwölf Anmeldungen erhalten einen Platz.', 'Die Reihenfolge der Anmeldung spielt keine Rolle.'], ['Die Anmeldefrist wird verlängert.', 'Von einer Verlängerung steht nichts im Aushang.']]
]],
['info-search', 'reading', 'Mit dem Bus zum Flughafen', 'Abfahrtszeiten, Fahrzeiten und Preisregeln eines Flughafenbusses verbinden.',
['空港リムジンバス　中央駅 → 空港\n・発車時刻：6:10／6:40／7:20／8:00／9:00（9時以降は毎時0分）\n・所要時間：約50分。ただし、朝7時から9時の間に出発する便は、道路が混むため約70分かかります。\n・運賃：大人1,300円、子ども650円\n・乗車券は駅の券売機でお求めください。車内で現金で支払う場合は、1人につき100円高くなります。\n・大きな荷物は1人2個まで無料でお預かりします。'],
'Flughafen-Limousinenbus vom Hauptbahnhof zum Flughafen. Abfahrten: 6:10, 6:40, 7:20, 8:00, 9:00, danach jeweils zur vollen Stunde. Fahrzeit etwa 50 Minuten; Busse, die zwischen 7 und 9 Uhr morgens abfahren, brauchen wegen des Verkehrs etwa 70 Minuten. Fahrpreis: Erwachsene 1300 Yen, Kinder 650 Yen. Fahrkarten gibt es am Automaten im Bahnhof; wer im Bus bar bezahlt, zahlt pro Person 100 Yen mehr. Große Gepäckstücke: bis zu zwei pro Person kostenlos.',
[['所要時間（しょようじかん）', 'benötigte Zeit, Fahrzeit'], ['乗車券（じょうしゃけん）', 'Fahrkarte'], ['券売機（けんばいき）', 'Fahrkartenautomat']],
'Achte auf ただし: Danach folgt eine Ausnahme, die die allgemeine Regel einschränkt. Hier verändert sie die Fahrzeit am Morgen.', [
['Du musst spätestens um 8:15 Uhr am Flughafen sein. Welchen Bus nimmst du spätestens?', 0, ['Den Bus um 6:40 Uhr.', 'Er fährt vor 7 Uhr ab, braucht etwa 50 Minuten und ist gegen 7:30 Uhr am Flughafen.'], ['Den Bus um 7:20 Uhr.', 'Er fährt in der Stoßzeit, braucht etwa 70 Minuten und kommt erst gegen 8:30 Uhr an.'], ['Den Bus um 8:00 Uhr.', 'Dieser Bus kommt frühestens um 9 Uhr an.'], ['Den Bus um 6:10 Uhr.', 'Er kommt rechtzeitig an, ist aber nicht der späteste mögliche Bus.']],
['Zwei Erwachsene und ein Kind bezahlen ihre Fahrt bar im Bus. Wie viel zahlen sie zusammen?', 0, ['3550 Yen.', '2 × 1400 Yen plus 750 Yen: Der Aufschlag von 100 Yen gilt für jede Person.'], ['3250 Yen.', 'Das ist der Preis am Automaten ohne Aufschlag.'], ['3350 Yen.', 'Der Aufschlag gilt pro Person, nicht nur einmal.'], ['4200 Yen.', 'Das Kind zahlt nicht den Erwachsenenpreis.']]
]]
],
N2: [
['integrated', 'reading', 'Homeoffice: zwei Erfahrungen', 'Gemeinsamkeiten und Unterschiede zweier Meinungen zum Homeoffice herausarbeiten.',
['Text A: 在宅勤務が広がって三年になる。通勤に使っていた一日往復二時間を、私は勉強や家族との時間に充てられるようになった。集中を要する資料作成は、話しかけられることの多い職場より家の方がはかどる。もちろん、対面で話し合うべき場面はある。だからこそ、出社する日を目的に応じて選べる今の働き方を、会社には続けてほしい。一律に全員を毎日出社させる制度に戻れば、これまでに得た成果を手放すことになる。', 'Text B: 私の部署では昨年、在宅勤務の日を週二日に減らした。仕事の効率が落ちたからではない。入社したばかりの社員が、分からないことを気軽に聞けず、一人で悩んでいたことが分かったのだ。画面越しの会議では、用件は伝わっても、ちょっとした雑談から生まれる助言や信頼関係は育ちにくい。在宅勤務の利点は認めつつも、経験の浅い人が孤立しない仕組みを先に考えるべきだと思う。'],
'Text A: Homeoffice gibt es seit drei Jahren. Die zwei Stunden Pendelzeit pro Tag kann ich nun fürs Lernen und für die Familie nutzen. Konzentrierte Schreibarbeit gelingt zu Hause besser als im Büro, wo man oft angesprochen wird. Natürlich gibt es Situationen, die ein persönliches Gespräch erfordern. Gerade deshalb soll die Firma die jetzige Regel beibehalten, bei der man die Bürotage je nach Zweck wählen kann. Eine einheitliche Pflicht zur täglichen Anwesenheit würde das Erreichte aufgeben. Text B: Meine Abteilung hat die Homeoffice-Tage im letzten Jahr auf zwei pro Woche reduziert – nicht, weil die Effizienz sank, sondern weil neue Mitarbeitende nicht einfach nachfragen konnten und allein mit Problemen blieben. In Videokonferenzen kommt das Anliegen an, aber Rat und Vertrauen aus kleinen Gesprächen wachsen kaum. Ich erkenne die Vorteile an, meine aber, man müsse zuerst dafür sorgen, dass Unerfahrene nicht isoliert werden.',
[['充てられる（あてられる）', 'für etwas verwenden können'], ['一律（いちりつ）', 'einheitlich, ohne Ausnahme'], ['孤立（こりつ）', 'Isolation']],
'Beim Vergleich zweier Texte hilft eine einfache Tabelle: Was sagen beide? Wo setzen sie andere Schwerpunkte? Achte auf einschränkende Formulierungen wie 認めつつも.', [
['Worin sind sich beide Texte einig?', 1, ['Homeoffice hat Vorteile, doch für manches bleibt persönlicher Kontakt wichtig.', 'A nennt Situationen für persönliche Gespräche, B erkennt die Vorteile des Homeoffice an.'], ['Man sollte vollständig zur täglichen Büroarbeit zurückkehren.', 'A lehnt das ausdrücklich ab, B fordert es nicht.'], ['Homeoffice senkt die Effizienz der Arbeit.', 'B betont, dass die Effizienz nicht der Grund war.'], ['Neue Mitarbeitende arbeiten zu Hause besser.', 'B beschreibt gerade ihre Schwierigkeiten zu Hause.']],
['Wie unterscheidet sich Text B von Text A?', 1, ['B stellt die Unterstützung neuer Mitarbeitender in den Vordergrund und hält deshalb weniger Homeoffice-Tage für sinnvoll.', 'B begründet die Reduzierung mit der Isolation neuer Kollegen.'], ['B hält Homeoffice für unproduktiv.', 'B sagt ausdrücklich, dass die Effizienz nicht gesunken ist.'], ['B möchte, dass jeder seine Bürotage frei wählt.', 'Das ist die Position von Text A.'], ['B lehnt Videokonferenzen grundsätzlich ab.', 'B sagt nur, dass dort Vertrauen schwer entsteht.']]
]],
['integrated', 'reading', 'Höhere Eintrittspreise für die Burg', 'Zwei Stellungnahmen zu einer Preiserhöhung vergleichen und ihre Vorschläge unterscheiden.',
['Text A: 市は来年度から、城の天守の入場料を500円から1,200円に引き上げる。観光客が増え続け、傷んだ階段や展示の修理が追いつかないためだ。値上げで得た収入は、全額を建物の保存と整備に充てる。市民については、住所を確認できる証明書を示せば、今の料金のままとする。見学の質を守るためにも、混雑をある程度抑えることは必要だと考えている。', 'Text B: 文化財を守るための費用を利用者が負担するという考え方には賛成だ。しかし、いきなり二倍以上にするのは急すぎる。家族で訪れれば大きな出費になるし、修学旅行の学校が行き先を変えてしまうおそれもある。値上げは段階的に行い、子どもや学生の料金は低く抑えるべきではないか。混雑を減らしたいのであれば、時間帯ごとの予約制を導入するという方法もあるはずだ。'],
'Text A: Die Stadt erhöht ab dem nächsten Haushaltsjahr den Eintritt für den Burgturm von 500 auf 1200 Yen. Die Besucherzahlen steigen weiter, und die Reparaturen beschädigter Treppen und Ausstellungen kommen nicht hinterher. Die Mehreinnahmen fließen vollständig in Erhalt und Pflege. Einwohner zahlen mit einem Nachweis ihres Wohnorts weiterhin den bisherigen Preis. Um die Qualität der Besichtigung zu sichern, sei es auch nötig, den Andrang etwas zu begrenzen. Text B: Dass die Besucher die Kosten für den Erhalt des Kulturguts tragen, befürworte ich. Mehr als eine Verdopplung auf einen Schlag ist aber zu abrupt: Für Familien wird es teuer, und Schulen könnten für Klassenfahrten andere Ziele wählen. Die Erhöhung sollte schrittweise erfolgen, und Kinder und Studierende sollten wenig zahlen. Gegen den Andrang könnte man auch Reservierungen nach Zeitfenstern einführen.',
[['天守（てんしゅ）', 'Burgturm, Hauptturm einer Burg'], ['文化財（ぶんかざい）', 'Kulturgut'], ['段階的（だんかいてき）', 'schrittweise']],
'Stellungnahmen beginnen oft mit Zustimmung (には賛成だ) und bringen danach mit しかし die eigentliche Kritik. Die Vorschläge stehen meist am Ende.', [
['Worin stimmen beide Texte überein?', 1, ['Die Besucher sollen zur Finanzierung des Erhalts der Burg beitragen.', 'A erhöht dafür den Preis; B stimmt dem Grundgedanken ausdrücklich zu.'], ['Der Preis sollte sofort mehr als verdoppelt werden.', 'Das plant nur A; B hält es für zu abrupt.'], ['Einwohner der Stadt sollten mehr bezahlen.', 'A lässt den Preis für Einwohner unverändert; B äußert sich dazu nicht.'], ['Klassenfahrten zur Burg sollten eingeschränkt werden.', 'B befürchtet im Gegenteil, dass Schulen fernbleiben.']],
['Was schlägt Text B vor, was Text A nicht vorsieht?', 1, ['Eine schrittweise Erhöhung, günstige Preise für Kinder und Studierende und Reservierungen nach Zeitfenstern.', 'Genau diese Maßnahmen nennt B als Alternativen.'], ['Den Eintritt für alle kostenlos zu machen.', 'B befürwortet ausdrücklich, dass Besucher zahlen.'], ['Die Einnahmen für Tourismuswerbung zu verwenden.', 'Von Werbung ist in keinem Text die Rede.'], ['Die Vergünstigung für Einwohner abzuschaffen.', 'B geht auf die Regel für Einwohner nicht ein.']],
['Welches Ziel nennen beide Texte im Zusammenhang mit dem Andrang?', 0, ['Weniger Gedränge bei der Besichtigung.', 'A will den Andrang begrenzen; B schlägt dafür Zeitfenster vor.'], ['Mehr Besucher aus dem Ausland.', 'Keiner der Texte wünscht mehr Besucher.'], ['Längere Öffnungszeiten.', 'Öffnungszeiten werden nicht erwähnt.'], ['Den Bau eines zweiten Eingangs.', 'Bauliche Erweiterungen kommen nicht vor.']]
]],
['info-search', 'reading', 'Ausschreibung eines Stipendiums', 'Bewerbungsvoraussetzungen und Formalien einer Stipendienausschreibung prüfen.',
['〇〇財団　2027年度　留学支援奨学金　募集要項\n１．対象：本学の2年生以上で、2027年9月から1年以内の交換留学が決定している者\n２．給付額：月額8万円（返還不要）\n３．成績基準：前年度のGPAが3.0以上であること\n４．併給：他の給付型奨学金との併給は不可。ただし、貸与型奨学金との併用は認める。\n５．提出書類：申請書、成績証明書、留学先大学の受入許可書（写し可）、指導教員による推薦書\n６．締切：2027年5月31日（必着）。郵送でのみ受け付ける。'],
'Stiftung 〇〇 – Stipendium zur Förderung von Auslandsstudien 2027, Ausschreibung. 1. Berechtigt: Studierende dieser Universität ab dem zweiten Jahr, deren Austauschstudium innerhalb eines Jahres ab September 2027 feststeht. 2. Leistung: 80.000 Yen monatlich (nicht rückzahlbar). 3. Leistungsnachweis: GPA des Vorjahres mindestens 3,0. 4. Doppelförderung: Gleichzeitiger Bezug eines anderen nicht rückzahlbaren Stipendiums ist nicht erlaubt; ein Darlehensstipendium darf jedoch zusätzlich bezogen werden. 5. Unterlagen: Antrag, Notenbescheinigung, Zulassung der Gastuniversität (Kopie genügt), Empfehlungsschreiben der betreuenden Lehrkraft. 6. Frist: 31. Mai 2027 (Eingang), nur per Post.',
[['給付（きゅうふ）', 'nicht rückzahlbare Leistung'], ['貸与（たいよ）', 'Darlehen, leihweise Vergabe'], ['必着（ひっちゃく）', 'muss bis zum Stichtag eingegangen sein']],
'In Ausschreibungen trennen ただし und のみ die Regel von ihrer Ausnahme bzw. Einschränkung. 必着 bedeutet: Das Eingangsdatum zählt, nicht der Poststempel.', [
['Wer kann sich bewerben?', 0, ['Eine Studentin im 3. Jahr mit GPA 3,2, deren Austausch ab September 2027 feststeht und die ein Studiendarlehen erhält.', 'Alle Bedingungen sind erfüllt; ein Darlehen (貸与型) darf zusätzlich bezogen werden.'], ['Ein Student im 1. Jahr mit GPA 3,8 und feststehendem Austausch.', 'Bewerben dürfen sich nur Studierende ab dem 2. Jahr.'], ['Eine Studentin mit GPA 3,4, die bereits ein anderes nicht rückzahlbares Stipendium erhält.', 'Ein zweites 給付型-Stipendium ist ausgeschlossen.'], ['Ein Student im 2. Jahr mit GPA 2,8 und feststehendem Austausch.', 'Der GPA muss mindestens 3,0 betragen.']],
['Was gilt für die Unterlagen?', 0, ['Die Zulassung darf eine Kopie sein, die Empfehlung muss von der betreuenden Lehrkraft stammen.', '写し可 und 指導教員による推薦書 regeln genau das.'], ['Alle Dokumente müssen im Original eingereicht werden.', 'Für die Zulassung genügt ausdrücklich eine Kopie.'], ['Man kann die Unterlagen per E-Mail schicken, wenn sie bis 31. Mai ankommen.', 'Es wird nur Post angenommen (郵送でのみ).'], ['Die Empfehlung darf von jeder Lehrkraft der Universität stammen.', 'Gefordert ist die betreuende Lehrkraft (指導教員).']],
['Muss das Stipendium zurückgezahlt werden?', 0, ['Nein, es ist nicht rückzahlbar.', '返還不要 bedeutet, dass keine Rückzahlung nötig ist.'], ['Ja, nach dem Ende des Studiums.', 'Rückzahlung gilt für Darlehen, nicht für dieses Stipendium.'], ['Nur, wenn der GPA unter 3,0 fällt.', 'Eine solche Bedingung steht nicht in der Ausschreibung.'], ['Nur zur Hälfte.', 'Von einer teilweisen Rückzahlung ist keine Rede.']]
]],
['info-search', 'reading', 'Regeln für Tagungsräume', 'Preis-, Storno- und Nutzungsregeln eines Tagungshauses auf konkrete Fälle anwenden.',
['市民会館　会議室のご利用について\n・予約：利用日の3か月前の1日から、窓口またはウェブサイトで受け付けます。\n・料金（1時間あたり）：小会議室（定員10名）800円／中会議室（定員30名）1,500円／大会議室（定員80名）3,000円\n・営利目的でのご利用は、上記料金の2倍となります。\n・キャンセル料：利用日の7日前までは無料、6日前から前日までは料金の50％、当日は100％を申し受けます。\n・飲食は小会議室のみ可能です。ただし、アルコール類は全室でご遠慮ください。'],
'Bürgerhaus – Nutzung der Tagungsräume. Reservierung ab dem 1. des Monats drei Monate vor dem Nutzungstag, am Schalter oder online. Preise pro Stunde: kleiner Raum (10 Personen) 800 Yen, mittlerer Raum (30 Personen) 1500 Yen, großer Raum (80 Personen) 3000 Yen. Bei gewerblicher Nutzung gilt der doppelte Preis. Stornogebühren: bis 7 Tage vorher kostenlos, von 6 Tagen vorher bis zum Vortag 50 %, am Nutzungstag 100 %. Essen und Trinken nur im kleinen Raum; Alkohol ist in allen Räumen nicht erlaubt.',
[['営利（えいり）', 'Gewinnerzielung, gewerblich'], ['窓口（まどぐち）', 'Schalter'], ['遠慮（えんりょ）', 'verzichten (höfliches Verbot)']],
'ご遠慮ください ist ein höfliches Verbot. Prüfe bei Berechnungen Schritt für Schritt: passender Raum, Stunden, Aufschlag.', [
['Eine Firma hält mit 25 Teilnehmenden zwei Stunden lang eine Verkaufsschulung ab. Was kostet der passende Raum?', 0, ['6000 Yen.', 'Mittlerer Raum: 1500 Yen × 2 Stunden, verdoppelt wegen gewerblicher Nutzung.'], ['3000 Yen.', 'Der Aufschlag für gewerbliche Nutzung fehlt.'], ['12.000 Yen.', 'Für 25 Personen reicht der mittlere Raum; der große wäre nicht nötig.'], ['3200 Yen.', 'Der kleine Raum ist nur für 10 Personen.']],
['Eine Gruppe möchte bei ihrem Treffen Kaffee und Kuchen anbieten. Was ist richtig?', 0, ['Das geht nur im kleinen Raum, also mit höchstens 10 Personen.', '飲食は小会議室のみ erlaubt Essen nur dort.'], ['Im großen Raum ist Essen erlaubt, nur Alkohol nicht.', 'Essen ist ausschließlich im kleinen Raum erlaubt.'], ['Essen und Trinken sind in allen Räumen verboten.', 'Im kleinen Raum sind sie erlaubt.'], ['Kaffee ist überall erlaubt, Kuchen nur im kleinen Raum.', 'Die Regel unterscheidet nicht zwischen Getränken und Essen.']],
['Eine Buchung für Samstag wird am Montag derselben Woche storniert. Was zahlt man?', 0, ['Die Hälfte des Preises.', 'Montag ist fünf Tage vor Samstag, also im Zeitraum mit 50 %.'], ['Nichts.', 'Kostenlos ist es nur bis sieben Tage vorher.'], ['Den vollen Preis.', '100 % gelten nur am Nutzungstag selbst.'], ['Ein Viertel des Preises.', 'Eine Gebühr von 25 % ist nicht vorgesehen.']]
]],
['long', 'reading', 'Ein Heft für Fehler', 'Den Gedankengang eines längeren Berichts über Fehlerkultur verfolgen.',
['ある小さな印刷会社では、社員が仕事で失敗をしたとき、その内容を共有のノートに書き込むことになっている。誰が、いつ、どのような失敗をしたのか、そしてなぜそうなったと思うのかを、できるだけ具体的に記すのである。始めた当初、このノートはほとんど白紙のままだった。失敗を書けば評価が下がるのではないか、同僚にどう思われるだろうかと、社員の多くが恐れたからだ。', '状況が変わったのは、社長自身が自分の失敗を書き始めてからである。見積もりの計算を誤って赤字の仕事を引き受けたこと、取引先への連絡を忘れて納期を遅らせたことなど、社長は隠さずに書いた。そして、ノートの内容は人事の評価には一切使わないと、全員の前で約束した。すると、少しずつほかの社員も書き込むようになった。', 'ノートの記録が増えるにつれて、同じような失敗が何度も繰り返されていることが見えてきた。例えば、急ぎの注文ほど確認の手順が省かれ、誤字が見落とされやすい。また、新人が一人で電話を受ける時間帯には、注文内容の聞き間違いが多いことも分かった。そこで会社は、急ぎの仕事にこそ二人で確認する仕組みを取り入れ、電話の内容は必ず書面で確かめることにした。その結果、刷り直しの件数は一年で半分近くに減ったという。', '失敗を責めるだけの職場では、人は失敗を隠そうとする。隠された失敗からは、誰も学ぶことができない。大切なのは、失敗を個人の不注意として片付けるのではなく、なぜ起きたのかを皆で考えられる環境をつくることだろう。このノートの価値は、失敗の数を減らしたことだけではなく、失敗について話し合える雰囲気を職場に生んだことにあるのかもしれない。'],
'In einer kleinen Druckerei tragen Beschäftigte ihre Fehler in ein gemeinsames Heft ein: wer, wann, welcher Fehler und warum er vermutlich passiert ist. Anfangs blieb das Heft fast leer, weil viele eine schlechtere Beurteilung und die Meinung der Kollegen fürchteten. Das änderte sich, als der Chef seine eigenen Fehler aufschrieb – etwa einen falsch kalkulierten Kostenvoranschlag, der einen Verlustauftrag brachte, oder eine vergessene Nachricht, die eine Lieferfrist verzögerte – und vor allen versprach, das Heft nie für Personalbeurteilungen zu nutzen. Mit der Zeit zeigte sich, dass sich ähnliche Fehler wiederholten: Bei Eilaufträgen wurden Kontrollschritte ausgelassen und Tippfehler übersehen, und wenn Neulinge allein am Telefon waren, wurden Bestellungen häufig missverstanden. Die Firma führte deshalb für Eilaufträge eine Kontrolle durch zwei Personen ein und bestätigt telefonische Bestellungen schriftlich. Nachdrucke gingen in einem Jahr um fast die Hälfte zurück. Wo Fehler nur bestraft werden, werden sie versteckt, und aus versteckten Fehlern lernt niemand. Wichtig ist ein Umfeld, in dem man gemeinsam nach den Ursachen fragt. Der Wert des Hefts liegt vielleicht nicht nur in weniger Fehlern, sondern in einer Atmosphäre, in der man über Fehler sprechen kann.',
[['見積もり（みつもり）', 'Kostenvoranschlag'], ['納期（のうき）', 'Liefertermin'], ['刷り直し（すりなおし）', 'Nachdruck']],
'Lange Texte folgen oft dem Muster Problem – Wendepunkt – Ergebnis – Deutung. Die Meinung des Autors steht meist im letzten Absatz, erkennbar an だろう oder のかもしれない.', [
['Was ist die Kernaussage des Textes?', 3, ['Aus Fehlern lernt man nur, wenn man offen und ohne Schuldzuweisung über sie sprechen kann.', 'Der letzte Absatz fasst genau diesen Gedanken zusammen.'], ['Fehler müssen streng bestraft werden, damit sie seltener vorkommen.', 'Der Text beschreibt Bestrafung als Grund, Fehler zu verstecken.'], ['Nur Führungskräfte sollten ihre Fehler aufschreiben.', 'Der Chef ging voran, damit alle schreiben.'], ['Kontrollen sind bei Eilaufträgen überflüssig.', 'Gerade für Eilaufträge wurde eine doppelte Kontrolle eingeführt.']],
['Warum blieb das Heft anfangs fast leer?', 0, ['Viele fürchteten eine schlechtere Beurteilung und die Reaktion der Kollegen.', '評価が下がるのではないか und 同僚にどう思われるか nennen die Gründe.'], ['Es passierten damals kaum Fehler.', 'Später zeigen sich viele wiederholte Fehler.'], ['Das Heft war nur für den Chef bestimmt.', 'Es war ein gemeinsames Heft (共有のノート).'], ['Die Beschäftigten hatten keine Zeit zum Schreiben.', 'Zeitmangel wird nicht als Grund genannt.']],
['Welche Maßnahme ergriff die Firma aufgrund der Einträge?', 2, ['Eilaufträge werden von zwei Personen kontrolliert.', '急ぎの仕事にこそ二人で確認する仕組み wurde eingeführt.'], ['Eilaufträge werden nicht mehr angenommen.', 'Die Firma nimmt sie weiter an, prüft sie aber doppelt.'], ['Neue Mitarbeitende dürfen keine Anrufe mehr annehmen.', 'Telefonische Bestellungen werden stets schriftlich bestätigt.'], ['Die Einträge fließen in die Personalbeurteilung ein.', 'Das hat der Chef ausdrücklich ausgeschlossen.']],
['Was hält der Autor für den vielleicht größten Wert des Hefts?', 3, ['Dass eine Atmosphäre entstand, in der man über Fehler sprechen kann.', 'だけではなく … 雰囲気を生んだこと betont diesen zusätzlichen Wert.'], ['Die eingesparten Kosten für Nachdrucke.', 'Weniger Nachdrucke werden genannt, aber nicht als größter Wert.'], ['Eine genaue Statistik der Fehler jedes Einzelnen.', 'Um Schuldzuweisung an Einzelne geht es gerade nicht.'], ['Dass der Chef keine Fehler mehr macht.', 'Davon ist im Text nicht die Rede.']]
]],
['long', 'reading', 'Die Buchhandlung am Bahnhof', 'Verstehen, warum ein kleiner Laden besteht, und die Verallgemeinerung des Autors erkennen.',
['インターネットで本を買う人が増え、町の本屋は年々数を減らしている。私の住む町でも、この十年で三軒あった本屋のうち二軒が閉店した。ところが、駅前に残った一軒は、客が減るどころか、最近はむしろにぎわっているように見える。平日の夕方でも、棚の前で本を手に取る人の姿が絶えない。その理由が知りたくて、店主に話を聞いてみた。', '店主によれば、店の広さでは大型書店にかなわないため、置く本の数で勝負することはやめたという。その代わりに、店員が実際に読んで勧めたいと思った本を選び、一冊ごとに手書きの紹介文を添えている。「何を読めばいいか分からない」という客にとって、この紹介文が本を選ぶきっかけになっているのだ。紹介文を読むのが楽しみで、毎週のように店に立ち寄る常連客もいるそうだ。', 'また、月に一度、閉店後の店内で読書会を開いている。参加者は同じ本を読んできて、感想を自由に話し合う。初めは数人だった参加者も、今では毎回二十人ほどが集まるという。年齢も職業もさまざまな人々が、一冊の本をきっかけに言葉を交わす。読書会で知り合った人同士が、店の外でも交流するようになったという話も聞いた。', '店主は「本を売るだけなら、ネットには勝てません。でも、本をきっかけに人が集まる場所は、ネットでは作りにくいと思うんです」と語った。便利さや値段では比べられない価値を、どのように示していくか。それは本屋に限らず、町の小さな店が生き残っていくための、共通の課題なのかもしれない。'],
'Immer mehr Menschen kaufen Bücher online, und die Buchhandlungen der Städte werden jedes Jahr weniger. Auch in meiner Stadt haben in zehn Jahren zwei von drei Läden geschlossen. Die übrige Buchhandlung am Bahnhof wirkt dagegen belebter als früher; selbst an Werktagabenden stehen ständig Leute an den Regalen. Ich fragte den Inhaber nach dem Grund. Weil der Laden an Fläche mit großen Buchhandlungen nicht mithalten kann, konkurriert er nicht über die Zahl der Bücher. Stattdessen wählen die Mitarbeitenden Bücher aus, die sie selbst gelesen haben und empfehlen möchten, und legen jedem eine handgeschriebene Empfehlung bei. Für Kunden, die nicht wissen, was sie lesen sollen, ist das der Anstoß; manche Stammkunden kommen fast jede Woche wegen dieser Texte. Außerdem findet einmal im Monat nach Ladenschluss ein Lesekreis statt, zu dem inzwischen rund zwanzig Menschen jeden Alters und Berufs kommen; manche treffen sich inzwischen auch außerhalb des Ladens. Der Inhaber sagt: Nur Bücher verkaufen könne man gegen das Internet nicht gewinnen, aber einen Ort, an dem Bücher Menschen zusammenbringen, könne das Internet schwer schaffen. Wie man einen Wert zeigt, der sich nicht an Bequemlichkeit oder Preis messen lässt, ist vielleicht die gemeinsame Aufgabe aller kleinen Läden.',
[['店主（てんしゅ）', 'Ladeninhaber'], ['読書会（どくしょかい）', 'Lesekreis'], ['常連客（じょうれんきゃく）', 'Stammkunde']],
'どころか verstärkt einen Gegensatz: „nicht nur nicht weniger, sondern sogar mehr“. Achte im letzten Absatz darauf, wie der Autor von einem Einzelfall auf eine allgemeine Frage schließt.', [
['Worum geht es in dem Text hauptsächlich?', 0, ['Warum eine kleine Buchhandlung trotz Online-Konkurrenz Kundschaft gewinnt.', 'Der Autor will genau diesen Grund herausfinden und berichtet darüber.'], ['Wie man Bücher im Internet günstig kauft.', 'Online-Käufe sind nur der Hintergrund.'], ['Warum zwei Buchhandlungen schließen mussten.', 'Die Schließungen werden nur kurz erwähnt.'], ['Wie man einen Lesekreis gründet.', 'Der Lesekreis ist nur eine von mehreren Maßnahmen.']],
['Warum konkurriert der Laden nicht über die Zahl der Bücher?', 1, ['Weil er an Fläche nicht mit großen Buchhandlungen mithalten kann.', '店の広さでは大型書店にかなわない ist der genannte Grund.'], ['Weil die Kunden nur neue Bücher wollen.', 'Das sagt der Inhaber nicht.'], ['Weil große Buchhandlungen keine Empfehlungen schreiben.', 'Über Empfehlungen anderer Läden wird nichts gesagt.'], ['Weil er vor allem gebrauchte Bücher verkauft.', 'Gebrauchte Bücher kommen nicht vor.']],
['Was hilft Kunden, die nicht wissen, was sie lesen sollen?', 1, ['Die handgeschriebenen Empfehlungen zu jedem Buch.', 'Das 紹介文 wird ausdrücklich als Anstoß zur Auswahl genannt.'], ['Ein großes Angebot an Bestsellern.', 'Der Laden setzt gerade nicht auf Menge.'], ['Rabatte für Stammkunden.', 'Rabatte werden nicht erwähnt.'], ['Eine Online-Bestellmöglichkeit.', 'Der Laden grenzt sich vom Internet ab.']],
['Welche Schlussfolgerung zieht der Autor?', 3, ['Kleine Läden müssen einen Wert zeigen, der sich nicht an Bequemlichkeit oder Preis messen lässt.', 'Der letzte Satz verallgemeinert den Einzelfall auf alle kleinen Läden.'], ['Kleine Läden sollten ihre Preise senken.', 'Gerade Preise hält der Autor nicht für entscheidend.'], ['Buchhandlungen sollten zusätzlich online verkaufen.', 'Das empfiehlt der Text nicht.'], ['Lesekreise sind wichtiger als Bücher.', 'Der Lesekreis ergänzt den Verkauf, ersetzt ihn aber nicht.']]
]],
['long', 'reading', 'Helfen, aber auf Dauer', 'Das Problem kurzlebiger Freiwilligenarbeit und die vorgeschlagene Lösung verstehen.',
['災害が起きると、多くの人がボランティアとして被災地に駆けつける。困っている人の力になりたいというその気持ちは尊いものだ。しかし、活動が長く続かないという問題もたびたび指摘されてきた。最初の数週間は大勢の人が集まっても、報道が減るにつれて参加者も目に見えて減ってしまうのだ。一方で、被災した人々の生活が元に戻るまでには、何年もかかることが少なくない。', 'ある地域の団体は、この問題に対して「無理をしない参加」を呼びかけている。毎週来られなくても、月に一度、半日だけでもよい。現地に行けない人には、支援物資の仕分けや、仮設住宅で暮らす人への手紙を書くといった、自宅や近所でできる活動を紹介している。参加の形を増やすことで、関わる人の数を保とうとしているのである。また、参加した人同士が経験を分かち合えるよう、月に一度の報告会も開いている。', '団体の代表は「一度に全力を出して燃え尽きてしまう人を、これまで何人も見てきました」と話す。熱意のある人ほど、仕事や家庭を犠牲にしてまで活動を続けようとし、やがて疲れ果てて離れていく。本人にとってつらいだけでなく、結果的に支援の力も弱くなってしまう。代表は、そうした人をこれ以上出さないことも団体の大切な役目だと考えている。', '支援とは、強い気持ちで一度だけ行うものではなく、細く長く続けていくものなのだろう。自分にできる範囲を知り、その範囲の中で関わり続けること。それは決して消極的な態度ではなく、長い復興の道のりを支えるための、現実的な方法だと言えるのではないだろうか。'],
'Nach Katastrophen eilen viele als Freiwillige ins Katastrophengebiet. Dieser Wunsch zu helfen ist wertvoll, doch oft wird kritisiert, dass die Hilfe nicht lange anhält: In den ersten Wochen kommen viele, aber mit abnehmender Berichterstattung sinkt die Zahl der Helfer sichtbar. Dabei dauert es oft Jahre, bis das Leben der Betroffenen wieder normal ist. Eine regionale Organisation ruft deshalb zu einer „Teilnahme ohne Überforderung“ auf: Wer nicht jede Woche kommen kann, hilft einmal im Monat einen halben Tag. Wer nicht vor Ort sein kann, sortiert Hilfsgüter oder schreibt Briefe an Menschen in Behelfsunterkünften. Durch mehr Formen der Beteiligung soll die Zahl der Helfenden erhalten bleiben; außerdem gibt es einmal im Monat ein Treffen, bei dem die Beteiligten ihre Erfahrungen austauschen. Der Leiter sagt, er habe viele gesehen, die sich auf einmal völlig verausgabt und dann ausgebrannt hätten. Gerade Engagierte opfern Beruf und Familie, erschöpfen sich und ziehen sich zurück – das ist schlimm für sie und schwächt am Ende die Hilfe. Der Leiter sieht es auch als Aufgabe der Organisation, dass es nicht noch mehr solcher Fälle gibt. Hilfe ist wohl nichts, was man einmal mit großem Einsatz leistet, sondern etwas, das man in kleinem Umfang lange fortsetzt. Die eigenen Grenzen zu kennen und in diesem Rahmen dabeizubleiben, ist keine passive Haltung, sondern ein realistischer Weg, den langen Wiederaufbau zu unterstützen.',
[['被災地（ひさいち）', 'Katastrophengebiet'], ['燃え尽き（もえつき）', 'Ausbrennen, Burn-out'], ['復興（ふっこう）', 'Wiederaufbau']],
'Die These steht hier erst im letzten Absatz. Die ersten drei Absätze liefern Problem, Lösungsansatz und Begründung – lies sie als Vorbereitung auf die Schlussfolgerung.', [
['Was ist die Hauptaussage des Textes?', 3, ['Hilfe wirkt am besten, wenn viele im Rahmen ihrer Möglichkeiten lange dabeibleiben.', 'Der letzte Absatz formuliert genau diese These.'], ['Freiwillige sollten sich möglichst intensiv in kurzer Zeit engagieren.', 'Genau davor warnt der Text.'], ['Die Medien sollten mehr über Katastrophen berichten.', 'Die Berichterstattung ist nur ein Faktor im Problem.'], ['Nur Fachleute sollten in Katastrophengebieten helfen.', 'Der Text wirbt für breite Beteiligung.']],
['Welches Problem beschreibt der erste Absatz?', 0, ['Mit abnehmender Berichterstattung gehen auch die Helfer zurück, obwohl der Wiederaufbau Jahre dauert.', 'Dieser Widerspruch wird im ersten Absatz beschrieben.'], ['Es kommen von Anfang an zu wenige Freiwillige.', 'Anfangs kommen im Gegenteil viele.'], ['Die Betroffenen wollen keine Hilfe annehmen.', 'Davon ist keine Rede.'], ['Freiwillige behindern die Arbeit der Behörden.', 'Das wird nicht erwähnt.']],
['Was bietet die Organisation Menschen an, die nicht ins Katastrophengebiet reisen können?', 1, ['Hilfsgüter sortieren oder Briefe an Menschen in Behelfsunterkünften schreiben.', 'Diese Tätigkeiten zu Hause oder in der Nähe werden genannt.'], ['Geld für die Reise ins Gebiet.', 'Reisekosten werden nicht erwähnt.'], ['Online-Kurse über Katastrophenschutz.', 'Solche Kurse kommen im Text nicht vor.'], ['Eine Mitgliedschaft ohne Aufgaben.', 'Es geht um konkrete Tätigkeiten.']],
['Wie bewertet der Autor die Haltung, nur so viel zu tun, wie man kann?', 3, ['Als realistischen, keineswegs passiven Weg, den Wiederaufbau zu unterstützen.', '決して消極的な態度ではなく … 現実的な方法 drückt diese Bewertung aus.'], ['Als Zeichen mangelnden Engagements.', 'Der Autor widerspricht dieser Deutung ausdrücklich.'], ['Als Notlösung, die nur für Ältere geeignet ist.', 'Eine Altersgruppe wird nicht genannt.'], ['Als Grund für das Nachlassen der Hilfe.', 'Als Grund nennt der Text im Gegenteil das Ausbrennen durch Überforderung.']]
]]
],
N1: [
['info-search', 'reading', 'Förderrichtlinien für Kulturprojekte', 'Förderhöhe, förderfähige Kosten und Pflichten aus Richtlinien ableiten.',
['令和9年度　地域文化振興助成　公募要領（抜粋）\n【助成対象】市内で活動する非営利団体が市内で実施する文化事業。ただし、団体の構成員の過半数が市内在住または在勤であること。\n【助成額】対象経費の2分の1以内、上限50万円。ただし、本助成に初めて申請する団体については、対象経費の3分の2以内とする（上限額は同じ）。\n【対象外経費】飲食費、団体構成員への謝礼、備品のうち単価5万円以上のもの\n【重複申請】同一年度内に本市の他の助成を受ける事業は対象としない。\n【実績報告】事業終了後30日以内に報告書を提出すること。提出がない場合は、翌年度の申請を受け付けない。'],
'Förderung der regionalen Kultur im Haushaltsjahr 2027 – Ausschreibung (Auszug). Gefördert werden Kulturprojekte gemeinnütziger Gruppen, die in der Stadt tätig sind und das Projekt in der Stadt durchführen; mehr als die Hälfte der Mitglieder muss in der Stadt wohnen oder arbeiten. Förderhöhe: bis zur Hälfte der förderfähigen Kosten, höchstens 500.000 Yen; Gruppen, die zum ersten Mal beantragen, erhalten bis zu zwei Dritteln (gleiche Obergrenze). Nicht förderfähig: Verpflegung, Honorare für Mitglieder der Gruppe, Ausstattung mit einem Stückpreis ab 50.000 Yen. Projekte, die im selben Jahr eine andere städtische Förderung erhalten, sind ausgeschlossen. Innerhalb von 30 Tagen nach Projektende ist ein Bericht einzureichen; ohne Bericht wird im Folgejahr kein Antrag angenommen.',
[['過半数（かはんすう）', 'Mehrheit, mehr als die Hälfte'], ['謝礼（しゃれい）', 'Honorar, Aufwandsentschädigung'], ['備品（びひん）', 'Ausstattung, Anschaffungen']],
'Bei Förderrichtlinien entscheidet die Reihenfolge: erst Regel, dann ただし-Ausnahme, zuletzt die Obergrenze. Rechne immer alle drei Schritte durch.', [
['Eine Gruppe beantragt zum ersten Mal eine Förderung; die förderfähigen Kosten betragen 900.000 Yen. Wie hoch ist die Förderung höchstens?', 0, ['500.000 Yen.', 'Zwei Drittel wären 600.000 Yen, doch die Obergrenze von 500.000 Yen gilt auch für Erstantragsteller.'], ['600.000 Yen.', 'Die Obergrenze (上限額は同じ) wurde übersehen.'], ['450.000 Yen.', 'Erstantragsteller erhalten bis zu zwei Drittel, nicht nur die Hälfte.'], ['300.000 Yen.', 'Das wäre ein Drittel; eine solche Regel gibt es nicht.']],
['Welche Ausgabe ist förderfähig?', 0, ['Ein Beamer zum Stückpreis von 40.000 Yen.', 'Ausgeschlossen ist Ausstattung erst ab 50.000 Yen pro Stück.'], ['Ein Honorar für ein Vereinsmitglied, das einen Vortrag hält.', 'Honorare an Mitglieder (構成員への謝礼) sind ausgeschlossen.'], ['Getränke und Snacks für das Publikum.', 'Verpflegung (飲食費) ist nicht förderfähig.'], ['Ein Mischpult zum Preis von 80.000 Yen.', 'Ausstattung ab 50.000 Yen pro Stück ist ausgeschlossen.']],
['Eine geförderte Gruppe reicht keinen Bericht ein. Welche Folge nennt der Text?', 0, ['Im folgenden Jahr wird kein Antrag der Gruppe angenommen.', '翌年度の申請を受け付けない ist die einzige genannte Folge.'], ['Die Förderung muss sofort vollständig zurückgezahlt werden.', 'Eine Rückzahlung wird im Auszug nicht erwähnt.'], ['Die Förderung wird im laufenden Jahr halbiert.', 'Davon steht nichts im Text.'], ['Die Gruppe verliert ihre Gemeinnützigkeit.', 'Das ist keine genannte Folge.']]
]],
['info-search', 'reading', 'Rückerstattung bei einem Online-Kurs', 'Erstattungs- und Verlängerungsregeln eines Kursvertrags auf Einzelfälle anwenden.',
['オンライン講座「データ分析実践」受講規約（抜粋）\n第5条（返金）\n１　受講開始日から8日以内に申し出があった場合は、受講料の全額を返金する。ただし、教材の視聴が全体の20％を超えている場合は、この限りでない。\n２　前項の期間の経過後、受講開始日から30日以内に申し出があった場合は、受講料から事務手数料3,000円を差し引いた額の半額を返金する。\n３　受講開始日から30日を超えた場合は、理由の如何を問わず返金しない。\n第6条（受講期間の延長）\n病気その他やむを得ない事情により、医師の診断書等を提出した場合に限り、受講期間を最長3か月延長することができる。延長の申請は、受講期間満了の14日前までに行うものとする。'],
'Online-Kurs „Datenanalyse in der Praxis“ – Teilnahmebedingungen (Auszug). § 5 Rückerstattung: 1. Wer sich innerhalb von 8 Tagen ab Kursbeginn meldet, erhält die volle Gebühr zurück; dies gilt nicht, wenn mehr als 20 % des Materials angesehen wurden. 2. Nach Ablauf dieser Frist und innerhalb von 30 Tagen ab Kursbeginn wird die Hälfte des Betrags erstattet, der nach Abzug einer Bearbeitungsgebühr von 3000 Yen von der Kursgebühr bleibt. 3. Nach mehr als 30 Tagen wird unabhängig vom Grund nichts erstattet. § 6 Verlängerung: Nur bei Krankheit oder sonstigen unvermeidbaren Umständen und gegen Vorlage eines ärztlichen Attests o. Ä. kann der Kurs um höchstens drei Monate verlängert werden. Der Antrag ist bis 14 Tage vor Ablauf der Kursdauer zu stellen.',
[['如何（いかん）', 'wie auch immer, unabhängig davon'], ['満了（まんりょう）', 'Ablauf (einer Frist)'], ['診断書（しんだんしょ）', 'ärztliches Attest']],
'Vertragstexte verweisen oft aufeinander (前項 = der vorige Absatz). この限りでない hebt die vorherige Regel für einen Sonderfall auf.', [
['Die Kursgebühr beträgt 43.000 Yen. Eine Teilnehmerin meldet sich am 15. Tag und hat 10 % des Materials angesehen. Wie viel erhält sie zurück?', 0, ['20.000 Yen.', 'Absatz 2 gilt: (43.000 − 3.000) ÷ 2 = 20.000 Yen.'], ['43.000 Yen.', 'Die volle Erstattung gilt nur innerhalb von 8 Tagen.'], ['21.500 Yen.', 'Vor dem Halbieren wird die Bearbeitungsgebühr abgezogen.'], ['40.000 Yen.', 'Nach Abzug der Gebühr wird zusätzlich halbiert.']],
['Wer erhält eine Verlängerung der Kursdauer?', 0, ['Ein Teilnehmer, der wegen eines Krankenhausaufenthalts ein Attest vorlegt und 20 Tage vor Ablauf beantragt.', 'Grund, Nachweis und Frist (14 Tage vorher) sind erfüllt.'], ['Eine Teilnehmerin, die aus beruflichen Gründen ohne Nachweis verlängern möchte.', 'Ein Nachweis wie ein Attest ist Voraussetzung (に限り).'], ['Ein Teilnehmer mit Attest, der eine Woche vor Ablauf beantragt.', 'Der Antrag muss spätestens 14 Tage vor Ablauf gestellt werden.'], ['Eine Teilnehmerin mit Attest, die dafür sechs Monate Verlängerung erhält.', 'Höchstens drei Monate sind möglich.']],
['Jemand möchte am 40. Tag wegen eines Umzugs aussteigen. Was gilt?', 0, ['Es wird nichts erstattet.', 'Nach 30 Tagen gibt es unabhängig vom Grund (理由の如何を問わず) keine Erstattung.'], ['Die Hälfte abzüglich der Bearbeitungsgebühr wird erstattet.', 'Das gilt nur bis zum 30. Tag.'], ['Bei einem Umzug wird die volle Gebühr erstattet.', 'Umzüge sind keine Ausnahme im Vertrag.'], ['Nur die Bearbeitungsgebühr wird einbehalten.', 'Eine solche Regel gibt es nicht.']]
]],
['long', 'reading', 'Der Preis der Verständlichkeit', 'Die differenzierte These eines Essays über vereinfachte Wissensvermittlung nachvollziehen.',
['近年、専門的な知識を「分かりやすく」伝えることが、あらゆる分野で求められるようになった。難解な研究成果を一般の人々に届けようとする努力そのものは、もちろん歓迎すべきである。専門家が内輪の言葉だけで語り、社会との接点を持とうとしなかった時代を思えば、その変化は確かな前進だと言えよう。実際、身近な言葉で語られた説明によって、それまで縁遠かった分野に関心を持つようになった人も少なくない。', 'しかし、分かりやすさが至上の価値とされるとき、見落とされがちなことがある。それは、単純化の過程で何が切り捨てられたのかが、受け手にはほとんど見えないという点だ。例えば、ある薬に効果があるという説明は、どのような条件の人に、どの程度の確率で効くのかという留保を省けば、確かに分かりやすくなる。だが、その留保こそが、個々人が判断を誤らないために最も必要な情報であることも少なくない。統計の数字も同様で、平均値だけが示されれば、ばらつきの大きさや例外的な事例は視野から消えてしまう。', 'さらに厄介なのは、分かりやすい説明に慣れた受け手が、複雑な説明そのものを不誠実なものとみなし始めることである。条件や例外を丁寧に述べる専門家よりも、断定的に言い切る人の方が頼もしく、信頼できるように感じられてしまう。こうして、慎重であることがかえって説得力の欠如と受け取られるという逆転が生じる。その結果、発信する側もまた、留保を省いた断定へと引き寄せられていくのである。こうした状況が続けば、専門家の中にも、慎重さを誇りとするより、断定の明快さを競おうとする者が現れかねない。', 'もっとも、だからといって分かりやすさを捨てるべきだというのではない。求められているのは、単純化したうえで、何を省いたのかを明示する姿勢であろう。「ここでは細かな条件には触れていない」と一言添えるだけでも、受け手は説明の限界を意識することができる。そして必要に応じて、それを手がかりにより詳しい情報へとたどり着くこともできるだろう。分かりやすさと正確さは、必ずしも二者択一の関係にあるわけではない。', '伝える側にその自覚があるかどうか。そして受け手の側にも、分かりやすい説明の背後にある省略を想像する力があるかどうか。専門知と社会との健全な関係は、その両方にかかっているのではないだろうか。'],
'Seit einigen Jahren soll Fachwissen in allen Bereichen „verständlich“ vermittelt werden. Das Bemühen, schwierige Forschungsergebnisse der Allgemeinheit nahezubringen, ist zu begrüßen; verglichen mit einer Zeit, in der Fachleute nur in ihrem Jargon sprachen und keinen Kontakt zur Gesellschaft suchten, ist das ein echter Fortschritt, und viele haben dadurch Interesse an fernen Gebieten gefunden. Wird Verständlichkeit aber zum höchsten Wert, übersieht man etwas: Was bei der Vereinfachung weggelassen wurde, bleibt für die Empfänger unsichtbar. Die Aussage, ein Medikament wirke, wird verständlicher, wenn man weglässt, bei wem und mit welcher Wahrscheinlichkeit – doch gerade diese Einschränkungen sind oft die wichtigste Information für eine richtige Entscheidung. Ebenso lassen Durchschnittswerte allein Streuung und Ausnahmen aus dem Blick verschwinden. Schwerer wiegt, dass an Vereinfachung gewöhnte Empfänger komplexe Erklärungen für unaufrichtig halten und Menschen, die klar behaupten, vertrauenswürdiger finden als Fachleute, die Bedingungen und Ausnahmen darlegen. So kehrt sich das Verhältnis um: Vorsicht wirkt wie mangelnde Überzeugungskraft, und auch die Sender werden zu Behauptungen ohne Einschränkungen verleitet. Hält das an, könnten selbst Fachleute eher um klare Behauptungen wetteifern, als auf ihre Vorsicht stolz zu sein. Das heißt nicht, dass man auf Verständlichkeit verzichten soll. Gefordert ist, nach der Vereinfachung offenzulegen, was weggelassen wurde; schon ein Satz wie „Einzelheiten werden hier nicht behandelt“ macht die Grenzen bewusst und kann bei Bedarf zu genaueren Informationen führen. Verständlichkeit und Genauigkeit schließen sich nicht aus. Ob die Sender sich dessen bewusst sind und ob die Empfänger sich die Auslassungen hinter einfachen Erklärungen vorstellen können – davon hängt ein gesundes Verhältnis zwischen Fachwissen und Gesellschaft ab.',
[['留保（りゅうほ）', 'Einschränkung, Vorbehalt'], ['断定的（だんていてき）', 'bestimmt, apodiktisch'], ['二者択一（にしゃたくいつ）', 'Entweder-oder']],
'Essays räumen oft zuerst etwas ein (もちろん, 確かに), bevor die eigentliche Kritik kommt (しかし). もっとも leitet danach eine Einschränkung der eigenen Kritik ein – achte auf dieses Hin und Her.', [
['Welche Haltung vertritt der Autor insgesamt?', 3, ['Man soll verständlich erklären, aber kenntlich machen, was dabei weggelassen wurde.', 'Der vierte Absatz formuliert diesen Mittelweg ausdrücklich.'], ['Fachwissen sollte nur noch in Fachsprache vermittelt werden.', 'Die Hinwendung zur Allgemeinheit nennt der Autor einen Fortschritt.'], ['Verständlichkeit ist wichtiger als Genauigkeit.', 'Der Autor hält beide für vereinbar, nicht für gegeneinander abzuwägen.'], ['Vereinfachte Erklärungen sollten verboten werden.', 'Er will ausdrücklich nicht auf Verständlichkeit verzichten.']],
['Was geht nach dem Beispiel im zweiten Absatz bei der Vereinfachung verloren?', 1, ['Angaben dazu, bei wem und mit welcher Wahrscheinlichkeit ein Medikament wirkt.', 'Diese 留保 werden als wichtigste Information für die Entscheidung genannt.'], ['Der Name des Medikaments.', 'Davon ist nicht die Rede.'], ['Die Kosten der Forschung.', 'Kosten werden nicht erwähnt.'], ['Die Nebenwirkungen bei allen Menschen.', 'Genannt werden Bedingungen und Wahrscheinlichkeiten, nicht Nebenwirkungen.']],
['Welche Umkehrung beschreibt der dritte Absatz?', 2, ['Vorsichtige, differenzierte Aussagen wirken weniger überzeugend als klare Behauptungen.', '慎重であることがかえって説得力の欠如と受け取られる beschreibt diese Umkehrung.'], ['Laien erklären Fachwissen besser als Fachleute.', 'Das behauptet der Text nicht.'], ['Komplexe Erklärungen werden populärer als einfache.', 'Es ist umgekehrt.'], ['Fachleute vertrauen der Allgemeinheit nicht mehr.', 'Es geht um das Vertrauen der Empfänger in die Sender.']],
['Was erwartet der Autor von den Empfängern?', 4, ['Dass sie sich vorstellen können, was hinter einer einfachen Erklärung weggelassen wurde.', 'Der letzte Absatz nennt diese Vorstellungskraft ausdrücklich.'], ['Dass sie nur Fachleuten mit Titeln glauben.', 'Titel spielen im Text keine Rolle.'], ['Dass sie komplexe Erklärungen grundsätzlich meiden.', 'Genau diese Haltung kritisiert der Autor.'], ['Dass sie selbst Forschung betreiben.', 'Das wird nicht verlangt.']]
]],
['long', 'reading', 'Erinnerungen bewahren', 'Einem Essay über digitale Regionalarchive und widersprüchliche Erinnerungen folgen.',
['古い写真や日記、地域の祭りの記録などを集め、デジタル化して公開する取り組みが各地で進んでいる。紙の資料は時とともに劣化しやすく、持ち主が亡くなれば散逸してしまうおそれもある。それらを誰もが閲覧できる形で残すことは、地域の歴史を未来へ手渡すうえで、大きな意義を持つ取り組みだと言えるだろう。とりわけ、個人の家に眠っていた資料が公開されることで、これまで知られていなかった暮らしの細部が明らかになることもある。', 'ところが、実際にこうした事業に関わった人々からは、資料を集めることよりも、資料に意味を与えることの方がはるかに難しいという声が聞かれる。一枚の写真には、撮影された日付や場所さえ分からないものが多い。写っている人物が誰で、それがどのような場面なのかを知る人も、年々少なくなっていく。説明のない写真は、どれほど鮮明にデジタル化されたとしても、見る人にとってはただの古い画像にすぎない。', 'そこで、ある町の図書館では、写真を公開するだけでなく、住民が思い出や情報を自由に書き込める場を設けた。すると、同じ一枚の写真について、ある人は祭りの準備の様子だと書き、別の人は台風の後片付けの場面だと記した。書き込みの中には、写真に写った店の名前や当時の値段、そのころ流行していた歌を記したものもあった。人々の記憶は、しばしば食い違う。図書館はそれを無理に一つの説明にまとめることはせず、異なる証言をそのまま並べて残すことにした。', 'この方針に対しては、記録としての正確さを損なうという批判もあるだろう。しかし、過去は一つの正しい物語として存在しているわけではない。同じ出来事を人々がどのように受け止め、どのように語り継いできたのか。その多様さもまた、地域の歴史の一部である。記録の正確さとは、一つの答えを確定させることだけを意味するのではなく、証言がどのように分かれているのかを正確に残すことでもあるはずだ。食い違いを消してしまえば、かえって失われるものがあるのではないか。', '記録を残すとは、単に物を保存することではなく、それについて語る人々の声を保存することなのかもしれない。資料の向こう側にいた人々の経験に想像を巡らせる余地を残しておくこと。その余地こそが、後の世代が過去と対話するための入り口になるのだろう。'],
'Vielerorts werden alte Fotos, Tagebücher und Aufzeichnungen über lokale Feste gesammelt, digitalisiert und veröffentlicht. Papier zerfällt mit der Zeit, und nach dem Tod der Besitzer droht das Material verstreut zu werden. Es für alle zugänglich zu erhalten, ist für die Weitergabe der Ortsgeschichte bedeutsam; gerade Material aus Privathaushalten bringt manchmal unbekannte Details des Alltags ans Licht. Beteiligte berichten jedoch, dass es viel schwieriger sei, dem Material Bedeutung zu geben, als es zu sammeln. Bei vielen Fotos sind nicht einmal Datum oder Ort bekannt, und immer weniger Menschen wissen, wer darauf zu sehen ist und welche Situation es zeigt. Ohne Erläuterung bleibt ein Foto, so scharf es digitalisiert sein mag, nur ein altes Bild. Eine Stadtbibliothek schuf daher einen Ort, an dem Einwohner Erinnerungen und Informationen eintragen können. Zu demselben Foto schrieb der eine, es zeige Festvorbereitungen, der andere, es zeige Aufräumarbeiten nach einem Taifun; manche notierten auch den Namen eines Ladens auf dem Bild, damalige Preise oder Lieder, die damals beliebt waren. Erinnerungen widersprechen sich oft; die Bibliothek fasste sie nicht gewaltsam zu einer Erklärung zusammen, sondern bewahrte die verschiedenen Aussagen nebeneinander. Man mag einwenden, das schade der Genauigkeit. Doch die Vergangenheit existiert nicht als eine einzige richtige Geschichte. Genauigkeit heißt nicht nur, eine Antwort festzulegen, sondern auch genau festzuhalten, wie die Aussagen auseinandergehen. Wie Menschen ein Ereignis aufgenommen und weitererzählt haben, gehört in seiner Vielfalt ebenfalls zur Ortsgeschichte; wer die Widersprüche tilgt, verliert vielleicht gerade etwas. Aufzeichnungen zu bewahren heißt womöglich nicht, Dinge zu bewahren, sondern die Stimmen derer, die davon erzählen – und Raum zu lassen, sich die Erfahrungen der Menschen hinter dem Material vorzustellen. Gerade dieser Raum ist wohl der Zugang, durch den spätere Generationen mit der Vergangenheit ins Gespräch kommen.',
[['劣化（れっか）', 'Zerfall, Qualitätsverlust'], ['散逸（さんいつ）', 'Verstreutwerden, Verlorengehen'], ['証言（しょうげん）', 'Aussage, Zeugnis']],
'Der Autor nimmt im vierten Absatz einen möglichen Einwand vorweg (批判もあるだろう) und widerlegt ihn mit しかし. Solche vorweggenommenen Einwände sind typisch für Essays.', [
['Was ist die Hauptaussage des Textes?', 4, ['Beim Bewahren von Ortsgeschichte kommt es darauf an, auch die unterschiedlichen Erinnerungen der Menschen festzuhalten.', 'Der Schluss beschreibt Archivieren als Bewahren von Stimmen.'], ['Alte Fotos sollten vor allem in hoher Auflösung digitalisiert werden.', 'Gerade die Bildqualität allein reicht laut Text nicht aus.'], ['Widersprüchliche Erinnerungen sollten korrigiert werden.', 'Die Bibliothek bewahrt sie bewusst nebeneinander.'], ['Papierarchive sind digitalen Archiven überlegen.', 'Der Text vergleicht die beiden nicht in dieser Weise.']],
['Was bezeichnen die Beteiligten als die größere Schwierigkeit?', 1, ['Dem Material eine Bedeutung zu geben, weil oft Datum, Ort und Personen unbekannt sind.', '資料に意味を与えることの方がはるかに難しい wird so begründet.'], ['Genug Material zu sammeln.', 'Das Sammeln gilt als der leichtere Teil.'], ['Die hohen Kosten der Digitalisierung.', 'Kosten werden nicht erwähnt.'], ['Die Einwilligung der Besitzer zu erhalten.', 'Davon ist nicht die Rede.']],
['Wie geht die Bibliothek mit widersprüchlichen Einträgen um?', 2, ['Sie bewahrt die verschiedenen Aussagen nebeneinander auf.', '異なる証言をそのまま並べて残す beschreibt ihr Vorgehen.'], ['Sie wählt die glaubwürdigste Aussage aus.', 'Sie fasst die Aussagen ausdrücklich nicht zu einer zusammen.'], ['Sie löscht alle Einträge zu diesem Foto.', 'Nichts wird gelöscht.'], ['Sie lässt Fachleute die richtige Deutung festlegen.', 'Fachleute werden nicht eingeschaltet.']],
['Wie antwortet der Autor auf den Einwand, die Genauigkeit leide?', 3, ['Auch die Vielfalt der Deutungen sei Teil der Geschichte, weil es nicht nur eine richtige Version gibt.', 'Das sagt der vierte Absatz nach しかし.'], ['Er gibt zu, dass der Einwand berechtigt ist, und empfiehlt eine Korrektur.', 'Er widerspricht dem Einwand.'], ['Genauigkeit sei in Archiven unwichtig.', 'Er relativiert den Begriff „eine richtige Geschichte“, nicht die Sorgfalt.'], ['Nur Augenzeugen dürften Einträge schreiben.', 'Eine solche Regel schlägt er nicht vor.']]
]],
['long', 'reading', 'Die unsichtbaren Kosten der Effizienz', 'Die Kritik eines Essays an der Verlagerung von Arbeit auf Kunden verstehen.',
['スーパーのセルフレジ、駅の自動券売機、インターネット上での各種手続き。私たちの身の回りでは、かつて店員や職員が担っていた作業を、利用者自身が行う場面が急速に増えている。事業者にとっては人件費の削減につながり、利用者にとっても待ち時間が短くなるという利点がある。行政の手続きも例外ではなく、かつては窓口で職員に尋ねれば済んだことを、今では画面の案内に従って一人で進めなければならない場面が増えた。一見すると、誰も損をしない、望ましい変化のように思える。', 'だが、ここで見落とされているのは、作業そのものがなくなったわけではないという事実である。商品のバーコードを読み取り、袋に詰め、支払いを済ませる。これらの手間は消えたのではなく、店員から客へと移されたにすぎない。しかも、その労働は対価を伴わず、統計上の生産性にも表れない。効率化の成果として語られるものの一部は、実は利用者の無償の労働によって支えられているのである。言い換えれば、事業者が支払っていた人件費の一部が、利用者の時間と手間という形に姿を変えて付け替えられているのだ。', 'この移転は、すべての人に等しく負担を課すわけでもない。機械の操作に慣れた人にとってはわずかな手間であっても、高齢者や障害のある人、あるいはその国の言葉が十分に分からない人にとっては、大きな壁となりうる。有人の窓口が減らされれば減らされるほど、そうした人々は助けを求める先を失っていく。実際、セルフレジの前で操作に迷い、後ろに並ぶ人の視線を気にしながら焦る高齢者の姿は、決して珍しいものではない。', 'もちろん、私は自動化そのものを否定するつもりはない。問題は、効率化による利益が誰に帰属し、そのための手間を誰が引き受けているのかが、ほとんど議論されないまま事態が進んでいる点にある。利用者の負担を前提とした仕組みであるならば、その負担に見合う配慮、例えば操作に困った人がすぐに頼れる人員を配置することなどが、当然求められるべきだろう。', '便利さの陰で、誰かが目に見えない形で費用を払っている。効率化を評価する際には、削減された費用だけでなく、移し替えられた負担にも目を向ける必要があるのではないだろうか。問われているのは技術の進歩そのものではなく、その負担の配分なのである。'],
'Selbstbedienungskassen im Supermarkt, Fahrkartenautomaten im Bahnhof, Formalitäten im Internet: Immer öfter erledigen Nutzer selbst, was früher Personal tat; auch bei Behörden muss man vieles, was man früher am Schalter erfragte, heute allein nach Bildschirmanweisungen erledigen. Für Unternehmen sinken die Personalkosten, für Nutzer die Wartezeiten – auf den ersten Blick ein Wandel, bei dem niemand verliert. Übersehen wird jedoch, dass die Arbeit nicht verschwunden ist. Scannen, Einpacken, Bezahlen – diese Arbeit wurde nur vom Personal auf die Kunden verlagert. Sie wird nicht bezahlt und taucht in keiner Produktivitätsstatistik auf; ein Teil der gefeierten Effizienz beruht also auf unbezahlter Arbeit der Nutzer. Anders gesagt: Ein Teil der Personalkosten wird in Form von Zeit und Mühe der Nutzer umgebucht. Diese Verlagerung belastet auch nicht alle gleich: Wer mit Geräten vertraut ist, hat wenig Mühe, für ältere Menschen, Menschen mit Behinderung oder Menschen, die die Landessprache nicht gut beherrschen, kann sie eine große Hürde sein. Je mehr bemannte Schalter abgebaut werden, desto mehr verlieren sie jede Anlaufstelle; ältere Menschen, die an der Selbstbedienungskasse unsicher werden und unter den Blicken der Wartenden in Eile geraten, sind kein seltener Anblick. Ich lehne Automatisierung nicht ab. Das Problem ist, dass kaum diskutiert wird, wem der Nutzen der Effizienz zufließt und wer die Mühe trägt. Wenn ein System auf der Belastung der Nutzer aufbaut, sollte es entsprechende Rücksicht nehmen, etwa Personal bereitstellen, an das sich Menschen bei Problemen sofort wenden können. Im Schatten der Bequemlichkeit zahlt jemand unsichtbar einen Preis; bei der Bewertung von Effizienz muss man neben den eingesparten Kosten auch die verlagerten Lasten sehen. Infrage steht nicht der technische Fortschritt selbst, sondern die Verteilung dieser Last.',
[['対価（たいか）', 'Gegenleistung, Bezahlung'], ['無償（むしょう）', 'unentgeltlich'], ['帰属（きぞく）', 'Zugehörigkeit, zufallen']],
'Der Autor grenzt seine Kritik im vierten Absatz ein (もちろん … 否定するつもりはない). Die eigentliche Forderung folgt danach – achte auf べきだろう.', [
['Was ist die zentrale These des Textes?', 1, ['Effizienzgewinne beruhen teils auf unbezahlter Arbeit, die auf die Kunden verlagert wurde.', 'Der zweite Absatz formuliert diese These, der Schluss wiederholt sie.'], ['Automatisierung sollte vollständig abgeschafft werden.', 'Der Autor lehnt Automatisierung ausdrücklich nicht ab.'], ['Selbstbedienung spart allen Beteiligten Zeit und Geld.', 'Genau diesen ersten Eindruck stellt der Autor in Frage.'], ['Unternehmen sollten höhere Preise verlangen.', 'Preise sind nicht das Thema.']],
['Warum taucht die Arbeit der Kunden nicht in der Produktivitätsstatistik auf?', 1, ['Weil sie unbezahlt geleistet wird.', '対価を伴わず erklärt, warum sie statistisch unsichtbar bleibt.'], ['Weil sie nur wenige Sekunden dauert.', 'Die Dauer wird nicht als Grund genannt.'], ['Weil Unternehmen sie absichtlich verschweigen.', 'Von Absicht ist nicht die Rede.'], ['Weil sie von Maschinen erledigt wird.', 'Gerade die Kunden erledigen sie selbst.']],
['Für wen ist die Verlagerung laut Text besonders belastend?', 2, ['Für ältere Menschen, Menschen mit Behinderung und Menschen mit geringen Sprachkenntnissen.', 'Diese Gruppen nennt der dritte Absatz.'], ['Für junge Menschen, die schnell einkaufen wollen.', 'Für Geübte ist es laut Text nur eine kleine Mühe.'], ['Für das Personal, das entlassen wird.', 'Der Text spricht von Kunden, nicht vom Personal.'], ['Für Unternehmen mit hohen Personalkosten.', 'Für Unternehmen ist die Verlagerung ein Vorteil.']],
['Was fordert der Autor konkret?', 3, ['Personal, an das sich Menschen bei Bedienungsproblemen sofort wenden können.', 'Diese Rücksichtnahme nennt er als Beispiel für das, was gefordert werden sollte.'], ['Die Rückkehr zu ausschließlich bemannten Kassen.', 'Er lehnt Automatisierung nicht ab.'], ['Eine Entschädigung in Geld für jeden Kunden.', 'Eine Bezahlung der Kunden fordert er nicht.'], ['Mehr Statistiken über Wartezeiten.', 'Davon ist nicht die Rede.']]
]],
['integrated', 'reading', 'Maschinelle Übersetzung im Sprachunterricht', 'Zwei Positionen zum Einsatz von Übersetzungstools vergleichen und eine vermittelnde Folgerung ziehen.',
['Text A: 大学の語学授業で、機械翻訳の使用を一律に禁じる動きがあるが、私は賛成しかねる。翻訳ツールはすでに社会の隅々にまで浸透しており、学生が卒業後にそれを使わずに働くことはまず考えられない。むしろ授業では、訳文のどこに誤りや不自然さが潜みやすいのかを、原文と照らし合わせて検証する力を養うべきだ。道具の限界を知らないまま使わせることこそ危うい。一律の禁止は、その訓練の機会までも奪ってしまう。', 'Text B: 機械翻訳を検証する力が重要だという主張そのものに異論はない。だが、訳文の誤りに気づくためには、そもそも原文を自力で読み解ける程度の語学力が前提となる。文法や語彙の基礎が固まっていない段階でツールに頼れば、学生はもっともらしい訳文をそのまま受け入れるだけになりかねない。初級の段階では使用を控えさせ、一定の力がついた中級以降に、検証を目的として段階的に導入するのが筋だろう。'],
'Text A: Es gibt Bestrebungen, maschinelle Übersetzung im Sprachunterricht an Universitäten pauschal zu verbieten; dem kann ich nicht zustimmen. Übersetzungstools sind längst überall in der Gesellschaft verbreitet, und dass Studierende nach dem Abschluss ohne sie arbeiten, ist kaum vorstellbar. Vielmehr sollte der Unterricht die Fähigkeit schulen, durch Abgleich mit dem Original zu prüfen, wo sich in Übersetzungen leicht Fehler und Unnatürliches verbergen. Gefährlich ist es gerade, Werkzeuge ohne Kenntnis ihrer Grenzen zu benutzen. Ein pauschales Verbot nimmt auch die Gelegenheit zu diesem Training. Text B: Dass die Fähigkeit zur Überprüfung wichtig ist, bestreite ich nicht. Um Fehler zu bemerken, muss man das Original aber selbst verstehen können. Stützen sich Lernende auf Tools, bevor Grammatik und Wortschatz gefestigt sind, übernehmen sie leicht plausibel klingende Übersetzungen ungeprüft. Sinnvoll ist, die Nutzung im Anfängerstadium zurückzuhalten und sie ab der Mittelstufe schrittweise zum Zweck der Überprüfung einzuführen.',
[['浸透（しんとう）', 'Durchdringung, Verbreitung'], ['検証（けんしょう）', 'Überprüfung'], ['前提（ぜんてい）', 'Voraussetzung']],
'In argumentativen Texten markieren Wendungen wie 異論はない, だが oder 賛成しかねる genau, wo Zustimmung endet und Widerspruch beginnt.', [
['Worin sind sich beide Texte einig?', 1, ['Die Fähigkeit, maschinelle Übersetzungen kritisch zu überprüfen, ist wichtig.', 'A fordert diese Fähigkeit, B bestätigt sie ausdrücklich (異論はない).'], ['Maschinelle Übersetzung sollte an Universitäten ganz verboten werden.', 'A lehnt ein Verbot ab, B will nur eine Einschränkung am Anfang.'], ['Anfänger sollten Übersetzungstools möglichst viel nutzen.', 'B rät gerade Anfängern davon ab.'], ['Übersetzungstools machen Sprachunterricht überflüssig.', 'Beide setzen weiterhin Sprachunterricht voraus.']],
['Wie unterscheidet sich die Position von Text B?', 1, ['B macht den Einsatz vom Lernstand abhängig, weil man Fehler nur mit eigenen Grundkenntnissen erkennt.', 'B verlangt zuerst eine sprachliche Grundlage und führt die Tools erst später ein.'], ['B hält die Tools für so fehlerhaft, dass man sie nie benutzen sollte.', 'B will sie ab der Mittelstufe einführen.'], ['B meint, im Berufsleben brauche man keine Übersetzungstools.', 'Über das Berufsleben äußert sich nur A.'], ['B möchte die Tools nur im Anfängerunterricht erlauben.', 'Es ist umgekehrt: erst ab der Mittelstufe.']],
['Welche Kursplanung entspräche beiden Texten am ehesten?', 1, ['In Fortgeschrittenenkursen werden maschinelle Übersetzungen gezielt mit dem Original verglichen und korrigiert.', 'Das verbindet As Überprüfungstraining mit Bs späterem Einsatz.'], ['Im Anfängerkurs werden alle Hausaufgaben maschinell übersetzt.', 'Das widerspricht B deutlich.'], ['In allen Kursen ist die Nutzung verboten.', 'Das widerspricht A deutlich.'], ['Die Tools werden erst nach dem Studium eingeführt.', 'Beide wollen die Überprüfung im Studium üben.']]
]],
['integrated', 'reading', 'Buslinien auf dem Land', 'Zwei Positionen zur Umstellung ländlicher Buslinien vergleichen.',
['Text A: 利用者が一日に数人しかいない路線バスを、税金で走らせ続けることには限界がある。ほとんど空のバスが決まった時刻に走る一方で、本当に移動に困っている高齢者は、停留所まで歩くことさえ難しい場合が多い。予約に応じて自宅近くまで迎えに行く乗り合いタクシーに切り替えれば、費用を抑えながら、利用者一人ひとりの事情により細かく対応できるはずだ。路線を維持すること自体を目的化すべきではない。', 'Text B: 乗り合いタクシーの利点は理解できる。しかし、予約という手続きは、電話やスマートフォンの操作に不慣れな人にとって、意外な壁となりうる。また、決まった時刻に必ずバスが来るという安心感があるからこそ、通院や買い物の予定を立てられる人も多い。利用者数だけで路線の価値を測るのは一面的だろう。切り替えるのであれば、予約の支援や試行期間を設け、利用者の声を確かめながら慎重に進めるべきである。'],
'Text A: Buslinien mit nur wenigen Fahrgästen pro Tag dauerhaft mit Steuergeld zu betreiben, hat Grenzen. Während fast leere Busse nach Fahrplan fahren, können gerade die älteren Menschen, die wirklich Mobilität brauchen, oft nicht einmal zur Haltestelle gehen. Mit Rufsammeltaxis, die auf Bestellung bis in die Nähe der Wohnung kommen, ließen sich Kosten senken und die Bedürfnisse Einzelner genauer berücksichtigen. Der Erhalt der Linie darf kein Selbstzweck werden. Text B: Die Vorteile von Rufsammeltaxis verstehe ich. Doch die Reservierung kann für Menschen, die mit Telefon oder Smartphone wenig vertraut sind, eine unerwartete Hürde sein. Außerdem können viele ihre Arzt- und Einkaufstermine nur planen, weil sie sich darauf verlassen, dass der Bus zu festen Zeiten kommt. Den Wert einer Linie nur an den Fahrgastzahlen zu messen, ist einseitig. Wenn man umstellt, dann vorsichtig: mit Hilfe bei der Reservierung, einer Testphase und unter Einbeziehung der Nutzer.',
[['目的化（もくてきか）', 'zum Selbstzweck machen'], ['不慣れ（ふなれ）', 'ungeübt, nicht vertraut'], ['一面的（いちめんてき）', 'einseitig']],
'Achte darauf, welches Argument des anderen Textes aufgegriffen wird: B antwortet auf As Vorschlag, bestreitet aber nicht dessen Vorteile, sondern ergänzt Bedingungen.', [
['Welche Aussage würden beide Autoren teilen?', 1, ['Rufsammeltaxis können Vorteile haben, entscheidend sind aber die Bedürfnisse der Menschen, die auf Mobilität angewiesen sind.', 'A argumentiert mit den Bedürfnissen älterer Menschen, B erkennt die Vorteile an und denkt an die Nutzer.'], ['Rufsammeltaxis sind grundsätzlich ungeeignet.', 'B versteht ausdrücklich ihre Vorteile.'], ['Buslinien sollten allein nach Fahrgastzahlen bewertet werden.', 'B nennt diese Sicht einseitig.'], ['Die Stadt sollte die Steuern für den Busverkehr erhöhen.', 'Keiner der Texte fordert höhere Steuern.']],
['Worin unterscheidet sich Text B von Text A?', 1, ['B sieht Hürden bei der Reservierung und den Wert fester Fahrzeiten und will nur schrittweise mit Unterstützung umstellen.', 'Diese Einwände und Bedingungen nennt B.'], ['B lehnt jede Umstellung kategorisch ab.', 'B stellt Bedingungen für eine Umstellung, lehnt sie aber nicht ab.'], ['B hält Linienbusse für zu teuer.', 'Das Kostenargument stammt von A.'], ['B meint, ältere Menschen sollten selbst zur Haltestelle gehen.', 'Das sagt keiner der Texte.']]
]]
]
};
