module.exports = add => {
add('reading', 'Was Archive auslassen', 'Eine abstrakte Argumentation über Auswahl und Neutralität verfolgen.',
['記録は過去をそのまま保存する容器ではない。何を記録に値するとみなし、どの分類に収めるかという判断が、保存に先立っている。たとえば地域の歴史を行政文書だけで編めば、制度の変遷は詳しく追える一方、制度の外で営まれた助け合いは、そもそも存在しなかったかのように見えてしまう。残された資料が誤っているのではなく、それだけを全体と見なすことに問題がある。', 'では、住民の語りを集めれば欠落は埋まるのか。語りにも、現在の関心に沿って過去を意味づけ直す働きがある。公的な記録を偏ったものとして退け、個人の記憶を無条件に真実とするなら、権威の置き場所を変えたにすぎない。両者の食い違いは、一方を消して解消するより、なぜ違って見えるのかを問う手がかりにしたい。', '資料の限界を示すことは、記録への信頼を損なう行為とは限らない。収集の経緯や選択の基準、残らなかった声の可能性が明らかであれば、読み手は記録が何を語り、何を語れないのかを判断できる。中立性とは選択が存在しない状態ではなく、選択を検討に開いておく姿勢なのではないか。'],
'Aufzeichnungen bewahren Vergangenheit nicht unvermittelt: Entscheidungen über Relevanz und Kategorien gehen voraus. Eine Ortsgeschichte allein aus Verwaltungsakten zeichnet Institutionen nach, lässt informelle Hilfe aber unsichtbar werden. Nicht die Akten sind deshalb falsch, sondern ihre Gleichsetzung mit dem Ganzen ist problematisch. Einwohnererzählungen schließen die Lücke nicht einfach: Auch Erinnerungen deuten Vergangenheit aus heutiger Sicht. Amtliche Quellen pauschal abzulehnen und Erinnerungen absolute Wahrheit zuzuschreiben würde nur die Autorität verlagern. Widersprüche sollten Fragen nach unterschiedlichen Perspektiven eröffnen. Grenzen offenzulegen muss Vertrauen nicht untergraben. Herkunft, Auswahl und möglicherweise fehlende Stimmen ermöglichen ein Urteil über Aussagekraft und Leerstellen. Neutralität kann bedeuten, Auswahl zur Prüfung offenzuhalten, statt Auswahlfreiheit zu behaupten.',
[['経緯（けいい）', 'Entstehungsgeschichte / Verlauf'], ['検討に開く（けんとうにひらく）', 'einer kritischen Prüfung zugänglich machen']], 'Die Schlussfrage formuliert eine positive Neubestimmung von Neutralität. Sie behauptet weder gleiche Zuverlässigkeit aller Quellen noch die Unmöglichkeit historischer Erkenntnis.', [
['Wie versteht der Text Neutralität?', 2, ['Als Offenheit der Auswahlentscheidungen für kritische Prüfung.', '選択を検討に開いておく姿勢 ist die vorgeschlagene Neubestimmung.'], ['Als vollständige Abwesenheit jeder Auswahl.', 'Diese Vorstellung wird ausdrücklich ersetzt.'], ['Als ausschließliche Nutzung persönlicher Erinnerungen.', 'Das wäre nur eine Verlagerung der Autorität.'], ['Als Verzicht darauf, überhaupt Geschichte zu schreiben.', 'Der Text entwickelt Bedingungen verantwortlicher Darstellung.']],
['Warum sind mündliche Erinnerungen keine automatische Korrektur aller Aktenlücken?', 1, ['Auch sie deuten die Vergangenheit aus gegenwärtigen Interessen heraus.', '現在の関心に沿って erklärt ihre eigene Perspektivität.'], ['Weil Erinnerungen grundsätzlich erfunden sind.', 'Eine pauschale Unwahrheit wird nicht behauptet.'], ['Weil Verwaltungsakten alle Lebensbereiche vollständig abdecken.', 'Gerade das bestreitet das erste Beispiel.'], ['Weil nur staatliche Stellen Wahrheit festlegen dürfen.', 'Die Autoritätsverlagerung wird kritisch betrachtet.']],
['Wie sollte ein Archiv widersprüchliche Quellen präsentieren?', 2, ['Ihre Herkunft und Grenzen offenlegen und Unterschiede untersuchbar lassen.', 'Transparente Auswahl ermöglicht dem Leser eine eigenständige Einordnung.'], ['Die persönliche Quelle stets löschen.', 'Keine Quellengattung erhält einen absoluten Vorrang.'], ['Widersprüche stillschweigend zu einer glatten Darstellung zusammenziehen.', 'Die Differenzen sollen als Erkenntnishinweise erhalten bleiben.'], ['Alle Quellen als gleich bedeutungslos ausweisen.', 'Grenzen aufzuzeigen ist kein Verzicht auf ihre Aussagekraft.']]
]);
add('reading', 'Zwei Texte über Übersetzung', 'Übereinstimmung trotz verschiedener Schwerpunktsetzung erschließen.',
['Ａ：翻訳の読みやすさは歓迎すべきだが、異なる時代や社会の文章が、初めから自分の常識で書かれたかのように読めるなら、失われたものにも目を向けたい。原文の不自然さをすべて日本語に残せというのではない。理解しにくさの中に、読者自身の前提を揺さぶる契機がある場合、それまで取り除くことを「親切」と呼んでよいのか、という問いである。', 'Ｂ：原文との距離を意識させることは大切だ。しかし、その距離を読者が渡るための足場を示さず、難解さだけを保つなら、異文化への入口はかえって狭くなる。注釈は異質さを消すためではなく、どこに違いがあるかを見定めるためにも使える。本文の流れを守る工夫と、背景を補う工夫は、対立するものではない。', '両者を「難しい訳の支持者」と「易しい訳の支持者」に分けると、議論の核心を逃す。問われているのは読みやすさの量ではなく、その読みやすさが何を可能にし、何を見えなくするかである。読者を迷わせないことと、読者に一度も立ち止まらせないことは、同じではない。'],
'A begrüßt lesbare Übersetzungen, fragt aber nach Verlusten, wenn fremde Zeiten und Gesellschaften wie aus den eigenen Selbstverständlichkeiten heraus erscheinen. Nicht jede Unebenheit muss erhalten bleiben; doch Schwierigkeit kann die Voraussetzungen der Leser erschüttern, und deren restlose Entfernung ist nicht unbedingt hilfreich. B hält Distanzbewusstsein für wichtig, verlangt aber Hilfen, um diese Distanz zu überbrücken. Bloße Schwerverständlichkeit verengt den Zugang. Anmerkungen können Unterschiede sichtbar machen, statt sie zu tilgen; flüssiger Haupttext und Hintergrundhilfen müssen sich nicht widersprechen. Beide auf schwer versus leicht zu reduzieren verfehlt den Kern. Es geht darum, was Lesbarkeit eröffnet und verdeckt. Orientierung zu geben bedeutet nicht, jeden Anlass zum Innehalten zu beseitigen.',
[['異質さ（いしつさ）', 'Fremdheit / Andersartigkeit'], ['足場（あしば）', 'hier: Orientierungshilfe / Grundlage']], 'A verteidigt nicht jede sprachliche Unebenheit. B will Unterschiede nicht beseitigen. Beide fragen nach der Wirkung der Vermittlung.', [
['Was ist der gemeinsame Kern der beiden Positionen?', 2, ['Vermittlung soll Zugang ermöglichen, ohne relevante Unterschiede unsichtbar zu machen.', 'Der Vergleich lenkt von bloßer Schwierigkeit auf Ermöglichung und Verdeckung.'], ['Eine gute Übersetzung muss immer maximal schwer sein.', 'A fordert nicht jede Unnatürlichkeit, B kritisiert bloße Schwierigkeit.'], ['Leser sollen nie über eigene Annahmen nachdenken müssen.', 'A sieht darin gerade einen möglichen Erkenntnisgewinn.'], ['Anmerkungen und flüssige Sprache schließen sich aus.', 'B bestreitet diesen Gegensatz.']],
['Welche Funktion können Anmerkungen nach B erfüllen?', 1, ['Lesern helfen, die Art des Unterschieds zu erkennen.', 'どこに違いがあるかを見定める nennt diese Funktion.'], ['Jede Fremdheit aus dem Werk entfernen.', '異質さを消すためではなく grenzt dies ab.'], ['Die Lektüre des Haupttexts grundsätzlich ersetzen.', 'Anmerkungen sollen Hintergrund ergänzen.'], ['Nur beweisen, dass Übersetzung unmöglich ist.', 'B schlägt praktische Vermittlung vor.']],
['Welche Übersetzungspraxis wäre mit beiden Positionen vereinbar?', 2, ['Flüssig formulieren und entscheidende kulturelle Spannungen gezielt erläutern.', 'Das verbindet Orientierung mit bewusstem Innehalten bei bedeutsamen Differenzen.'], ['Jeden fremden Bezug durch einen vertrauten heimischen ersetzen.', 'Damit würden relevante Unterschiede unsichtbar.'], ['Sämtliche Hintergrundhilfen aus Prinzip weglassen.', 'Das widerspräche Bs Brückenfunktion.'], ['Jede grammatische Unebenheit unverändert kopieren.', 'A verlangt dies ausdrücklich nicht.']]
]);
add('reading', 'Zahlen und kultureller Wert', 'Einen selbstverstärkenden Bewertungsmechanismus erkennen.',
['文化事業の成果を来場者数で示すことには、説明のしやすさという利点がある。だが、来場者数が補助金配分の中心的な基準になると、事業の側も、その数字を伸ばしやすい企画へと傾く。よく知られた題材には人が集まり、実績があるから支援も集まる。この循環の中で、まだ知られていない表現は、価値がないと判断される以前に、判断される機会そのものを得にくくなる。', '人数を数えるなと言いたいのではない。小規模な企画にも無条件で価値があるわけではなく、実施した側には何を試み、何が起きたかを説明する責任がある。ただし、数値に表れにくい成果を語ろうとした途端に「客観性に欠ける」と退けるなら、測定しやすさを価値そのものと取り違えることになる。', '評価には共通の尺度が必要だという反論はもっともである。それでも、すべてを一つの尺度に換算することだけが公平なのかは検討の余地がある。異なる目的を持つ企画に対し、目的に照らした説明と第三者による検討を求めることも、公平さを支える方法になりうる。比較を放棄するのではなく、比較の前提を一つに固定しないのである。'],
'Besucherzahlen machen Kulturförderung leicht erklärbar. Werden sie zum zentralen Verteilungskriterium, bevorzugen Veranstalter publikumswirksame Themen. Bekanntes zieht Publikum und damit weitere Förderung an; Unbekanntes erhält schon kaum Gelegenheit zur Bewertung. Der Text lehnt Zählen nicht ab und schreibt kleinen Vorhaben keinen automatischen Wert zu. Verantwortliche müssen Ziele und Ergebnisse erklären. Nicht leicht messbare Ergebnisse als unobjektiv abzutun verwechselt jedoch Messbarkeit mit Wert. Gemeinsame Maßstäbe sind ein berechtigtes Anliegen, aber ein einziger Umrechnungsmaßstab ist nicht die einzige Form von Fairness. Zweckbezogene Rechenschaft und unabhängige Prüfung können ebenfalls fair sein. Vergleich soll fortbestehen, seine Voraussetzungen sollen plural bleiben.',
[['尺度（しゃくど）', 'Bewertungsmaßstab'], ['換算（かんさん）', 'Umrechnung']], 'Der Autor räumt Gegenargumenten Gewicht ein. Seine Alternative ist begründete Prüfung nach unterschiedlichen Zielen, keine Befreiung von Rechenschaft.', [
['Was kritisiert der Text vor allem?', 0, ['Eine Förderlogik, die Bekanntheit verstärkt und neue Ausdrucksformen schon vor ihrer Bewertung benachteiligt.', 'Der beschriebene Kreislauf betrifft Zugang zu Bewertungsmöglichkeiten.'], ['Dass bekannte Kunst zwangsläufig wertlos sei.', 'Das wird nicht behauptet.'], ['Jede Erfassung von Besucherzahlen.', 'Der zweite Absatz lehnt dieses Verständnis ausdrücklich ab.'], ['Jede öffentliche Erklärung kultureller Ergebnisse.', 'Eine Erklärungspflicht wird bekräftigt.']],
['Welche Pflicht haben auch kleine Projekte?', 1, ['Darlegen, was sie versucht haben und was daraus entstand.', '説明する責任 gilt trotz kleiner Größe.'], ['Automatisch einen Anspruch auf unbegrenzte Förderung anmelden.', 'Kleine Größe begründet keinen automatischen Wert.'], ['Nur dieselbe Besucherzahl wie Großveranstaltungen erreichen.', 'Das wäre der kritisierte einheitliche Maßstab.'], ['Auf jede externe Prüfung verzichten.', 'Der Schluss fordert unabhängige Prüfung als Möglichkeit.']],
['Welche Förderbewertung entspräche der vorgeschlagenen Alternative?', 2, ['Ziele und Ergebnisse begründen lassen und unabhängig anhand passender Kriterien prüfen.', '目的に照らした説明と第三者による検討 beschreibt genau dies.'], ['Alle Vorhaben ohne Vergleich gleich finanzieren.', 'Vergleich wird nicht aufgegeben.'], ['Ausschließlich die größte Besucherzahl belohnen.', 'Das würde die problematische Einheitslogik fortsetzen.'], ['Projektverantwortlichen jede Selbstauskunft ungeprüft glauben.', 'Eine unabhängige Prüfung gehört ausdrücklich zur Alternative.']]
]);
add('reading', 'Ausnahmen und Regeln', 'Ein normatives Argument mit zwei gegensätzlichen Risiken abwägen.',
['規則は、担当者が変わっても扱いが変わらないようにするためにある。しかし、同じ規則を一律に当てはめることが、常に同じ程度の負担をもたらすわけではない。申請を窓口でしか受け付けない制度では、窓口の近くに住む人と、移動に介助を要する人とでは、「同じ手続き」の意味が異なる。形式上の同一性が、実質的な参加の機会を保証するとは限らないのである。', 'だからといって、個々の担当者の善意に例外を委ねればよいわけでもない。事情をうまく説明できた人だけが配慮を得られるなら、別の不公平が生まれる。必要なのは、例外をなくすことでも、例外を無制限に認めることでもなく、どのような事情に対して別の手段を用意するのかを、理由とともに共有することだ。', '例外の記録が蓄積すれば、個別の問題だと思われていたものが制度の設計に由来するとわかる場合もある。そのとき例外を増やしてしのぐだけでは、負担を申請者に押し戻してしまう。例外は規則の敗北ではなく、規則が見落としていた条件を知り、原則を組み直すための情報にもなりうる。'],
'Regeln sollen Behandlung unabhängig vom Sachbearbeiter machen. Dieselbe Vorschrift verursacht aber nicht dieselbe Belastung: Persönliche Antragstellung bedeutet für nahe Wohnende etwas anderes als für Menschen mit Assistenzbedarf. Formale Gleichheit garantiert keine gleiche Teilhabe. Ausnahmen allein dem guten Willen einzelner Beschäftigter zu überlassen erzeugt jedoch neue Ungleichheit zugunsten derjenigen, die ihre Lage gut schildern können. Weder starre Ausnahmslosigkeit noch unbegrenzte Beliebigkeit ist die Lösung; Gründe und Bedingungen alternativer Wege sollen gemeinsam festgehalten werden. Gesammelte Ausnahmen können strukturelle Konstruktionsfehler zeigen. Sie nur weiter einzeln zu behandeln verlagert Lasten auf Antragsteller. Ausnahmen können Informationen zur Revision von Regeln liefern.',
[['一律（いちりつ）', 'einheitlich ohne Differenzierung'], ['由来する（ゆらいする）', 'zurückzuführen sein auf']], 'Der Text vermeidet beide Extreme: starre Gleichbehandlung und willkürliche Einzelentscheidungen. Die Dokumentation macht Ausnahmen institutionell lernbar.', [
['Wie sollen Regeln und Ausnahmen zusammenwirken?', 2, ['Begründete Ausnahmen können Schwächen sichtbar machen und zur Regelrevision beitragen.', '例外 wird als Information zum 原則を組み直す verstanden.'], ['Ausnahmen beweisen, dass jede Regel nutzlos ist.', 'Der Text beschreibt einen legitimen Zweck von Regeln.'], ['Ausnahmen sollen stets undokumentiert bleiben.', 'Gerade ihre gesammelte Dokumentation ermöglicht Erkenntnis.'], ['Regeln dürfen trotz systematischer Nachteile nie verändert werden.', 'Die Revision ist eine zentrale Schlussfolgerung.']],
['Welches Risiko hat eine rein persönliche Kulanzentscheidung?', 1, ['Nur besonders überzeugend erklärende Antragsteller erhalten Rücksicht.', '事情をうまく説明できた人だけ nennt den Selektionsmechanismus.'], ['Alle erhalten automatisch denselben Zugang.', 'Es entsteht gerade neue Ungleichheit.'], ['Regeln werden dadurch zwingend genauer dokumentiert.', 'Dokumentation ist keine automatische Folge persönlicher Kulanz.'], ['Jede Alternative wird gesetzlich unmöglich.', 'Der Text behauptet kein solches Verbot.']],
['Viele Ausnahmen betreffen dieselbe Zugangshürde. Was folgt aus der Argumentation?', 2, ['Das Verfahren selbst auf einen strukturellen Fehler prüfen.', 'Wiederkehrende Fälle können auf 制度の設計 zurückgehen.'], ['Jeden Betroffenen erneut um eine individuelle Rechtfertigung bitten und sonst nichts ändern.', 'Das würde die Last wieder auf Antragsteller verschieben.'], ['Alle künftigen Ausnahmen unabhängig vom Grund ablehnen.', 'Die erkennbar ungleichen Voraussetzungen blieben unberücksichtigt.'], ['Dokumentierte Fälle löschen, um die Regel einheitlich erscheinen zu lassen.', 'Damit würde die Grundlage institutionellen Lernens verschwinden.']]
]);
add('reading', 'Zukunftsoffene Stadtplanung', 'Eine komplexe Gegenüberstellung von Effizienz und Änderbarkeit verstehen.',
['都市計画では、将来の需要を予測し、それに最も適した施設を整えることが合理的だとされる。予測の精度を上げる努力は欠かせないが、予測が外れる可能性まで消せるわけではない。ある用途に極めて効率よく適合した建物が、その用途の変化には対応しにくいこともある。現在の無駄を徹底して削る設計が、将来の選択肢まで削っているかもしれない。', '一方、変更可能性を残す設計にも費用はかかる。使う予定のない余白を確保することは、説明しにくい支出になりがちだ。だからといって、余白は多いほどよいと結論づけるのも安易である。どの部分を変更できるようにし、どこは長く固定するのか。構造の安全性と部屋の使い方を同じ程度に流動的に扱うことはできない。', '求められるのは、完成時の効率だけでなく、変更に要する費用や意思決定の仕組みを含めて評価することだ。壁を動かせても、用途変更を認める手続きがなければ、柔軟性は図面上の性質にとどまる。将来に開かれた計画とは、何も決めない計画ではない。何をいま決め、何を後から決め直せるようにするかを、意識的に区別した計画なのである。'],
'Stadtplanung gilt als rational, wenn sie prognostizierte Nachfrage optimal bedient. Bessere Prognosen beseitigen Unsicherheit jedoch nicht. Ein für einen Zweck extrem effizientes Gebäude kann bei geänderter Nutzung unflexibel sein; heutige Sparsamkeit kann künftige Optionen vernichten. Änderbarkeit kostet ebenfalls. Ungeplanten Spielraum zu finanzieren ist erklärungsbedürftig, doch möglichst viel Spielraum ist auch keine pauschale Lösung. Man muss zwischen veränderbaren und dauerhaften Teilen unterscheiden; statische Sicherheit und Raumnutzung sind nicht gleich flexibel. Bewertung sollte neben Anfangseffizienz auch Umbaukosten und Entscheidungsverfahren erfassen. Bewegliche Wände nutzen wenig, wenn Nutzungsänderungen institutionell unmöglich sind. Zukunftsoffenheit heißt bewusst entscheiden, was jetzt festgelegt wird und was später neu entschieden werden darf.',
[['余白（よはく）', 'hier: ungebundener Spielraum'], ['流動的（りゅうどうてき）', 'veränderlich / nicht festgelegt']], 'Die Gegenüberstellung läuft nicht auf „alles flexibel“ hinaus. Technische Änderbarkeit und die Befugnis, Änderungen zu beschließen, müssen zusammenpassen.', [
['Welche Planung befürwortet der Text?', 2, ['Bewusst zwischen heutigen Festlegungen und später revidierbaren Entscheidungen unterscheiden.', 'Die Schlussdefinition verbindet Festlegung und Änderbarkeit.'], ['Alle Entscheidungen bis in eine unbestimmte Zukunft vertagen.', '何も決めない計画ではない schließt das aus.'], ['Ausschließlich die Effizienz bei Fertigstellung maximieren.', 'Spätere Änderungskosten und Verfahren sollen mitbewertet werden.'], ['Jede bauliche Eigenschaft gleichermaßen veränderlich gestalten.', 'Sicherheit und Nutzung werden ausdrücklich unterschieden.']],
['Warum ist maximaler Spielraum allein keine ausreichende Lösung?', 1, ['Er kostet und muss nach der Art der Bauteile bzw. Entscheidungen differenziert werden.', 'Der zweite Absatz verbindet Kosten mit der nötigen Unterscheidung.'], ['Weil jede Nachfrageprognose sicher zutrifft.', 'Die Einleitung betont verbleibende Unsicherheit.'], ['Weil ungenutzte Fläche immer kostenlos ist.', 'Die Kosten werden ausdrücklich genannt.'], ['Weil Tragwerksicherheit bloß eine Geschmacksfrage ist.', 'Sie wird als anders zu behandeln als Raumnutzung dargestellt.']],
['Ein Haus hat verschiebbare Wände, aber keine Genehmigungswege für neue Nutzungen. Wie wäre es zu beurteilen?', 2, ['Die technische Flexibilität bleibt ohne passende Entscheidungsverfahren praktisch begrenzt.', 'Der Text führt genau diese Diskrepanz als Beispiel an.'], ['Es ist allein wegen der Wände bereits vollständig zukunftsoffen.', 'Das ignoriert den institutionellen Teil.'], ['Es hätte überhaupt keine tragenden Strukturen haben dürfen.', 'Sicherheit soll nicht beliebig veränderbar sein.'], ['Die ursprüngliche Nachfrageprognose muss deshalb falsch gewesen sein.', 'Aus fehlenden Verfahren folgt kein Urteil über die Prognose.']]
]);
add('listening', 'Ein stiller Vorbehalt', 'Eine indirekte Einwendung und ihre praktische Konsequenz verstehen.',
['A: 新制度の説明会ですが、資料は事前に配っていますし、当日は質問を受けるだけにすれば短く済みますね。\nB: そうですね、資料を読んで疑問を言葉にできる方には、その形が合うと思います。', 'A: 何か気になる点がありますか。\nB: 前回、質問がなかった部署ほど、実施後の問い合わせが多かったんです。理解していたというより、何がわからないのかをつかめていなかったのかもしれません。沈黙をそのまま理解の証拠にしてよいのか、少し引っかかっています。', 'A: では、冒頭で資料を全部読み上げましょうか。\nB: それだと、読んできた方には負担ですね。典型的な場面を一つ示して、どう対応するかを考えてもらってはどうでしょう。そこで出た違いを材料に説明すれば、質問できなかった部分も見えてくると思います。'],
'A: Die Unterlagen zur neuen Regelung sind vorab verteilt. Wenn wir beim Termin nur Fragen beantworten, wird es kurz. B: Für diejenigen, die nach dem Lesen ihre Unklarheiten formulieren können, passt das wohl. A: Gibt es Bedenken? B: Bei der letzten Einführung kamen aus Abteilungen ohne Fragen später die meisten Rückfragen. Vielleicht konnten sie ihre Unklarheit noch nicht erfassen. Schweigen als Verständnisbeweis zu behandeln irritiert mich. A: Dann lesen wir alles vor? B: Das belastet Vorbereitete. Besser wäre ein typischer Fall, zu dem alle ein Vorgehen überlegen. Unterschiede in den Antworten könnten bislang nicht formulierte Unklarheiten sichtbar machen.',
[['引っかかる（ひっかかる）', 'hier: Bedenken hervorrufen'], ['冒頭（ぼうとう）', 'Anfang eines Vortrags / Texts']], 'Bs anfängliches そうですね stimmt nur für eine eingeschränkte Gruppe zu. Der folgende Relativsatz trägt den eigentlichen Vorbehalt.', [
['Was signalisiert Bs erste Antwort im Gesamtzusammenhang?', 0, ['Bedingte Zustimmung: Das Format passt nur zu Menschen, die Unklarheiten bereits formulieren können.', '資料を読んで疑問を言葉にできる方 begrenzt die Zustimmung.'], ['Uneingeschränkte Zustimmung zum Format für alle.', 'Die Einschränkung und spätere Einwendung widersprechen dem.'], ['Die Forderung, die Unterlagen nicht zu verteilen.', 'Die Vorabunterlagen werden nicht abgelehnt.'], ['Den Wunsch, die Regelung vollständig zurückzunehmen.', 'B diskutiert die Vermittlung, nicht die Abschaffung.']],
['Welche Beobachtung begründet Bs Bedenken?', 1, ['Abteilungen ohne anfängliche Fragen hatten später besonders viele Rückfragen.', 'Der Gegensatz zwischen anfänglichem Schweigen und späteren Fragen ist das Argument.'], ['Alle Teilnehmer hatten die Unterlagen verloren.', 'Das wird nicht behauptet.'], ['Vorbereitete Teilnehmer stellten immer zu viele Fragen.', 'Die relevante Gruppe hatte anfangs gerade keine Fragen.'], ['Die neue Regelung war bereits aufgehoben.', 'Die Einführung steht noch bevor.']],
['Welche Gestaltung empfiehlt B?', 2, ['Einen typischen Fall bearbeiten lassen und Unterschiede zur Erklärung nutzen.', 'B will unausgesprochene Verständnisschwierigkeiten durch Anwendung sichtbar machen.'], ['Die gesamten Unterlagen unverändert vorlesen.', 'Das hält B für belastend für Vorbereitete.'], ['Schweigende Personen automatisch als informiert abhaken.', 'Diese Gleichsetzung wird kritisiert.'], ['Nur schriftlich perfekte Fragen zulassen.', 'Das würde genau die problematische Zugangshürde verstärken.']]
]);
add('listening', 'Ein Vortrag über Unsicherheit', 'Die Funktion eines Begriffswechsels in einem Kurzvortrag erfassen.',
['予測の不確実性を伝えると、専門家への信頼が下がるのではないか。そう心配する声をよく聞きます。ただ、ここでは「信頼する」という言葉で何を指しているかを分けて考える必要があります。必ず当たると期待することと、限界も含めて誠実に説明すると期待することは、同じではありません。', 'たとえば、数値を一つだけ示せば、聞き手は判断しやすく感じるでしょう。しかし条件が変わって数値を修正したとき、前の説明が間違いだったと受け取られかねません。最初から、どの条件のもとで、どの程度の幅があるかを示していれば、修正を知識の更新として理解できる余地が生まれます。', 'もちろん、幅のある数字を並べるだけでは説明したことになりません。何が判断を左右し、どの情報が得られれば見通しが変わるのかまで伝える必要があります。不確実性の説明は、責任を免れるための断り書きではなく、聞き手が後の変化を解釈するための手がかりを渡す行為なのです。'],
'Man hört die Sorge, offengelegte Prognoseunsicherheit mindere Expertenvertrauen. Doch Vertrauen in unfehlbare Vorhersagen unterscheidet sich von Vertrauen in ehrliche Erklärung einschließlich Grenzen. Eine einzelne Zahl wirkt entscheidungsfreundlich; wird sie bei neuen Bedingungen revidiert, kann die frühere Auskunft wie ein Fehler erscheinen. Wer Bedingungen und Bandbreite von Anfang an erklärt, ermöglicht die Deutung einer Korrektur als Wissenszuwachs. Zahlenintervalle allein genügen aber nicht. Man muss erläutern, welche Faktoren entscheidend sind und welche neuen Informationen den Ausblick verändern würden. Unsicherheitserklärung dient nicht dem Abstreifen von Verantwortung, sondern gibt Orientierung zur Deutung späterer Veränderungen.',
[['免れる（まぬがれる）', 'sich entziehen / entgehen'], ['断り書き（ことわりがき）', 'einschränkender Hinweis']], 'Der Vortrag unterscheidet zwei Arten von Vertrauen. Unsicherheit wird nicht als Freibrief für beliebige Aussagen präsentiert.', [
['Was ist die Hauptthese?', 2, ['Erklärte Unsicherheit kann Orientierung für spätere Änderungen geben.', '後の変化を解釈するための手がかり benennt den positiven Zweck.'], ['Fachleute sollten jede Verantwortung ablehnen.', '責任を免れるためではなく weist das zurück.'], ['Nur punktgenaue Prognosen verdienen Vertrauen.', 'Der Vortrag unterscheidet Vertrauen von Unfehlbarkeit.'], ['Bandbreiten erklären sich immer von selbst.', '数字を並べるだけでは erklärt ausdrücklich das Gegenteil.']],
['Welches Risiko hat eine isolierte Einzelzahl?', 1, ['Ihre spätere Änderung kann als Fehler der ursprünglichen Erklärung verstanden werden.', '条件が変わって修正した場合の受け取り方 ist das Beispiel.'], ['Sie verhindert jede Entscheidung vollständig.', 'Sie kann sich zunächst sogar leichter entscheidbar anfühlen.'], ['Sie macht Bedingungen automatisch transparent.', 'Die Bedingungen fehlen gerade bei einer isolierten Zahl.'], ['Sie ist zwangsläufig absichtlich erfunden.', 'Es geht um Deutung bei geänderten Bedingungen, nicht Betrug.']],
['Was sollte eine fachliche Prognose ergänzend erklären?', 2, ['Welche Faktoren maßgeblich sind und welche neuen Informationen eine Revision auslösen würden.', 'Diese beiden Punkte machen Unsicherheit praktisch interpretierbar.'], ['Nur möglichst viele Intervalle ohne Kontext.', 'Eine bloße Liste genügt nicht.'], ['Dass jede spätere Änderung unbegründet akzeptiert werden muss.', 'Der Vortrag verlangt nachvollziehbare Gründe.'], ['Dass Zuhörer grundsätzlich keine eigenen Entscheidungen treffen können.', 'Sie sollen gerade Interpretationshilfen erhalten.']]
]);
add('listening', 'Wessen Beteiligung zählt?', 'Konkurrierende Argumente zu einem Verfahren differenziert erfassen.',
['A: 住民会議をオンラインにしたら、参加者が倍になりました。参加の壁はかなり取り除けたと言ってよさそうですね。\nB: 人数が増えたのは評価できます。ただ、発言した人の顔ぶれはあまり変わっていません。接続していることと、議論に関われることは分けて見たほうがいいと思います。', 'A: 発言しない自由もあるでしょう。全員に話してもらうのは、かえって負担ではありませんか。\nB: ええ、発言を義務にしたいわけではありません。気になるのは、話したいのに入るタイミングがつかめない人です。口頭以外にも意見を出せる方法があれば、選べる幅が広がります。', 'A: では、終了後に全員へアンケートを送りますか。\nB: それも有用ですが、決定したあとだけでは、意見が議論に影響しません。会議の途中で短く書き込める時間を設け、進行役が紹介する形を試してはどうでしょう。黙っていたい人は、そのままでいいんです。'],
'A: Seit die Bürgerversammlung online ist, hat sich die Teilnahme verdoppelt. Die Hürden sind wohl weitgehend beseitigt. B: Mehr Teilnehmer sind positiv, aber es sprechen fast dieselben Personen. Verbindung und Mitwirkung sollten unterschieden werden. A: Es gibt auch die Freiheit zu schweigen; verpflichtendes Sprechen wäre belastend. B: Ja, ich will keine Pflicht. Mich beschäftigen Menschen, die sprechen möchten, aber keinen Einstieg finden. Nichtmündliche Wege erweitern die Wahl. A: Eine Umfrage nachher? B: Nützlich, aber erst nach Beschlüssen beeinflussen Beiträge die Diskussion nicht. Probieren wir kurze Schreibphasen während der Sitzung, deren Beiträge die Moderation vorstellt. Wer schweigen möchte, darf es weiterhin.',
[['顔ぶれ（かおぶれ）', 'Zusammensetzung der beteiligten Personen'], ['進行役（しんこうやく）', 'Moderation']], 'B unterscheidet freiwilliges Schweigen von verhinderten Beiträgen. Eine höhere Teilnehmerzahl ist anerkannt, aber nicht das ganze Teilhabeziel.', [
['Worin liegt Bs zentrale Unterscheidung?', 0, ['Zwischen technischer Teilnahme und tatsächlicher Möglichkeit, die Diskussion mitzugestalten.', '接続していることと議論に関われること werden getrennt.'], ['Zwischen gültigen und grundsätzlich wertlosen Onlinebeiträgen.', 'B schlägt selbst einen digitalen Schreibweg vor.'], ['Zwischen allen neuen und allen alten Einwohnern.', 'Das ist nicht die verwendete Unterscheidung.'], ['Zwischen verpflichtender Teilnahme und verpflichtendem Reden.', 'B lehnt eine Redepflicht ab.']],
['Wessen Situation möchte B besonders verbessern?', 1, ['Menschen, die etwas sagen möchten, aber keinen Einstieg finden.', '話したいのに入るタイミングがつかめない benennt diese Gruppe.'], ['Menschen, die bewusst nichts beitragen möchten, durch Zwang.', 'Deren Freiheit soll erhalten bleiben.'], ['Nur der ohnehin häufig Sprechenden.', 'Die unveränderte Sprechergruppe ist Teil des Problems.'], ['Nur derjenigen, die gar nicht angeschlossen sind.', 'Der Fokus liegt auf Mitwirkung innerhalb des Formats.']],
['Warum bevorzugt B Schreibmöglichkeiten während der Sitzung gegenüber ausschließlich nachträglicher Befragung?', 2, ['Die Beiträge können so noch vor der Entscheidung in die Diskussion einfließen.', 'Nach dem Beschluss fehlt diese unmittelbare Wirkung.'], ['Nachträgliche Umfragen seien unter allen Umständen nutzlos.', 'B nennt sie ausdrücklich ebenfalls nützlich.'], ['Dann muss ausnahmslos jeder einen Beitrag abgeben.', 'Freiwilliges Schweigen bleibt ausdrücklich möglich.'], ['So kann die Moderation alle abweichenden Beiträge geheim halten.', 'Die Moderation soll Beiträge gerade vorstellen.']]
]);
add('listening', 'Eine Ausstellung ohne glatte Geschichte', 'Implizite Absichten in einer fachlichen Auseinandersetzung erkennen.',
['A: 展示の最後に、技術の発展で生活が豊かになった、とまとめる構成ですね。流れは明快ですが、少しきれいに収まりすぎる気もします。\nB: 便利になったという実感は、多くの来場者に共有されると思ったのですが。', 'A: そこを否定したいのではないんです。同じ技術によって、ある仕事が楽になる一方、別の仕事が見えにくい場所へ移されたこともありましたよね。その両方を示したほうが、便利さが何によって支えられているかを考えられるのでは。\nB: ただ、問題点を並べると、結局どちらがよいのか、結論がぼやけませんか。', 'A: 来場者に賛否を一つ選ばせることが目的でしたっけ。むしろ、自分が使う道具の向こうにいる人を想像できるようにする、という話だったはずです。\nB: そうでした。では、最後の総括を断定文から問いに変え、便利になった場面と、それを支える作業を対にして見せましょう。'],
'A: Die Ausstellung endet mit „Technischer Fortschritt bereichert das Leben“. Das ist klar, wirkt aber etwas zu glatt. B: Ich dachte, viele Besucher teilen die Erfahrung größerer Bequemlichkeit. A: Das bestreite ich nicht. Dieselbe Technik erleichterte manche Arbeit und verlagerte andere an unsichtbarere Orte. Zeigen wir beides, kann man über die Grundlagen der Bequemlichkeit nachdenken. B: Wird ohne klares Pro oder Contra der Schluss unscharf? A: Ging es darum, die Besucher auf eine Seite festzulegen? Unser Ziel war doch, Menschen hinter den verwendeten Geräten vorstellbar zu machen. B: Richtig. Dann ersetzen wir die Schlussbehauptung durch eine Frage und stellen bequeme Nutzung und tragende Arbeit paarweise gegenüber.',
[['総括（そうかつ）', 'abschließende Gesamtdeutung'], ['断定（だんてい）', 'eindeutige Festlegung / Behauptung']], 'As rhetorische Frage erinnert an das vereinbarte Bildungsziel. Sie fordert kein pauschales Urteil gegen Technik.', [
['Was beabsichtigt A mit der Kritik am „zu glatten“ Schluss?', 0, ['Die einseitige Fortschrittserzählung um unsichtbare Voraussetzungen ergänzen.', 'Die zunächst indirekte Kritik wird später durch die verborgene Arbeit konkretisiert.'], ['Jeglichen Nutzen der Technik leugnen.', 'A sagt ausdrücklich, diesen Nutzen nicht bestreiten zu wollen.'], ['Die Ausstellung vollständig absagen.', 'Es geht um die Gestaltung des Schlusses.'], ['Besucher zu einer eindeutigen Ablehnung zwingen.', 'A hinterfragt gerade den Zwang zu Pro oder Contra.']],
['Welche zwei Folgen derselben Technik nennt A?', 1, ['Erleichterung mancher Arbeit und Verlagerung anderer Arbeit aus dem Blickfeld.', '楽になる一方 und 見えにくい場所へ移された bilden die Gegenüberstellung.'], ['Ausschließlich mehr Freizeit für alle.', 'Der Text nennt unterschiedliche Auswirkungen.'], ['Völlige Abschaffung jeder menschlichen Arbeit.', 'Arbeit bleibt zur Unterstützung der Bequemlichkeit nötig.'], ['Nur technische Defekte und höhere Eintrittspreise.', 'Diese Themen kommen nicht vor.']],
['Wie wird der Schluss überarbeitet?', 2, ['Mit einer offenen Frage und gepaarten Beispielen von Bequemlichkeit und unterstützender Arbeit.', 'B übernimmt die Zielklärung in zwei konkrete Gestaltungsentscheidungen.'], ['Mit einer stärkeren uneingeschränkten Fortschrittsbehauptung.', 'Die Behauptung wird gerade durch eine Frage ersetzt.'], ['Mit einer Abstimmung, die alle Besucher zu Ja oder Nein zwingt.', 'Das wurde als ursprüngliches Ziel zurückgewiesen.'], ['Durch Weglassen aller Beispiele zur Arbeit.', 'Die Arbeit soll sichtbarer werden.']]
]);
add('listening', 'Ein Experiment fortsetzen?', 'Evidenzgrenzen, konkurrierende Ziele und einen bedingten Beschluss verbinden.',
['A: 四日勤務の試行ですが、参加した部署では残業が減り、納期も守られています。この結果なら全社に広げられるのではないでしょうか。\nB: 成果は認めます。ただ、参加部署は自分たちで希望したところですし、顧客対応の少ない時期でもありました。条件の違う部署で同じ結果になるとは、まだ言い切れません。', 'A: 慎重なのはわかりますが、条件が完全にそろうまで待っていたら、いつまでも判断できませんよ。\nB: 完全な証明を求めているわけではありません。次に広げる範囲を、何を確かめたいかに合わせたいんです。たとえば顧客対応の多い部署で、引き継ぎの負担が誰に移るかを見る。その負担が別の部署に押し出されているなら、試行部署の残業だけを測っても不十分でしょう。', 'A: なるほど。では、全社導入の決定は保留し、性質の違う二部署を加えますか。\nB: 賛成です。その際、継続の条件だけでなく、見直しに戻る条件も先に決めておきましょう。\nA: わかりました。関係部署の負担と納期への影響を共同で確認する基準を作り、それに合意してから次の試行を始めます。'],
'A: Im Versuch mit der Viertagewoche sanken Überstunden bei eingehaltenen Lieferterminen. Können wir das auf die ganze Firma ausweiten? B: Das ist ein Erfolg, aber die Abteilungen hatten sich freiwillig gemeldet und die Phase hatte wenig Kundenkontakt. Andere Bedingungen könnten andere Ergebnisse bringen. A: Vollständig gleiche Bedingungen abzuwarten würde Entscheidungen endlos vertagen. B: Ich verlange keinen vollständigen Beweis. Die nächste Ausweitung soll gezielt offene Fragen prüfen, etwa wohin Übergabelasten in kundenintensiven Bereichen wandern. Werden sie auf andere Abteilungen verschoben, reichen die Überstunden der Versuchsabteilung als Maßstab nicht. A: Also noch keine Gesamteinführung, sondern zwei andersartige Abteilungen ergänzen? B: Ja, vorab Bedingungen sowohl für Fortsetzung als auch für Überarbeitung festlegen. A: Wir vereinbaren gemeinsame Kriterien für Belastung verbundener Abteilungen und Liefertermine und starten erst danach.',
[['保留（ほりゅう）', 'vorläufiges Zurückstellen'], ['引き継ぎ（ひきつぎ）', 'Arbeitsübergabe']], 'B verlangt weder Stillstand noch eine sofortige Gesamteinführung. Die Ausweitung soll Erkenntnislücken gezielt prüfen und vorab vereinbarte Rückkehrbedingungen besitzen.', [
['Wie lässt sich Bs Position am treffendsten beschreiben?', 1, ['Schrittweise Ausweitung anhand konkreter offener Fragen statt sofortiger Verallgemeinerung.', '何を確かめたいかに合わせたい bestimmt Bs Vorschlag.'], ['Ablehnung jeder weiteren Erprobung bis zum vollständigen Beweis.', 'B weist dieses Verständnis ausdrücklich zurück.'], ['Unverzügliche Einführung in allen Abteilungen ohne Zusatzprüfung.', 'Die Übertragbarkeit ist noch offen.'], ['Bestreiten der beobachteten Erfolge in den bisherigen Abteilungen.', 'B erkennt die Erfolge ausdrücklich an.']],
['Welche Messlücke nennt B?', 1, ['Belastung könnte in andere Abteilungen verlagert werden und dort ungemessen bleiben.', '押し出されているなら erklärt die Grenze lokaler Überstundenmessung.'], ['Liefertermine wurden bisher ausnahmslos verpasst.', 'A berichtet eingehaltene Termine.'], ['Es wurde bereits jede denkbare Kundensituation erfasst.', 'Die erste Phase hatte wenig Kundenkontakt.'], ['Alle Abteilungen wurden zur Teilnahme gezwungen.', 'Die bisherigen Abteilungen hatten sich freiwillig gemeldet.']],
['Welcher nächste Schritt wird abschließend vereinbart?', 2, ['Gemeinsame Kriterien auch für Nebenbelastungen und Revision vereinbaren, dann zwei andersartige Abteilungen erproben.', 'Der Beschluss verbindet begrenzte Erweiterung, Vorabkriterien und Zustimmung vor Start.'], ['Die Gesamteinführung sofort als endgültig verkünden.', 'Diese Entscheidung wird zurückgestellt.'], ['Nur die ursprünglichen Abteilungen unverändert weiter messen.', 'Zwei andersartige Abteilungen sollen hinzukommen.'], ['Erst nach Beginn entscheiden, welche Ergebnisse zählen sollen.', 'Die Kriterien sollen ausdrücklich vorher vereinbart werden.']]
]);
require('./n1-expansion.cjs')(add);
};
