module.exports = add => {
add('reading', 'Schneller ist nicht immer hilfreicher', 'Die These eines Kommentars samt Einschränkung erkennen.',
['問い合わせへの返答は速いほどよい、と言われる。確かに、何日も返事が来なければ利用者は不安になる。しかし、速さを唯一の目標にすると、担当者は事情を十分に確かめず、用意された説明を送るだけになりがちだ。返答は届いても、問題が解決したとは限らない。', 'ある施設では、すぐ答えられない質問に対し、まず受け付けたことと、いつまでに詳しく答えるかを知らせるようにした。最終的な回答までの時間は短くならなかったが、同じ人からの催促は減ったという。利用者にとっては、待つ時間そのものだけでなく、いつまで待てばよいかわからないことも負担だったのだ。', 'もちろん、期限を知らせればいくら遅くてもよいわけではない。伝えた期限を守り、難しい場合は途中で状況を説明する必要がある。対応のよさは、最初の返信に何分かかったかだけでなく、相手が見通しを持てたかという点からも考えるべきだ。'],
'Antworten auf Anfragen sollen möglichst schnell kommen. Lange Funkstille verunsichert tatsächlich. Wird Tempo aber zum einzigen Ziel, schicken Beschäftigte leicht Standardsätze ohne ausreichende Klärung; eine Antwort ist noch keine Lösung. Eine Einrichtung bestätigt schwierige Anfragen zunächst und nennt einen Termin für die ausführliche Antwort. Obwohl die endgültige Antwort nicht schneller kam, gab es weniger Nachfragen. Nicht nur Wartezeit, sondern Ungewissheit belastete die Nutzer. Das erlaubt keine beliebigen Verzögerungen: Fristen müssen eingehalten und Probleme zwischendurch erklärt werden. Gute Bearbeitung sollte auch daran gemessen werden, ob die Betroffenen den weiteren Ablauf absehen können.',
[['催促（さいそく）', 'Nachhaken / Mahnung'], ['見通し（みとおし）', 'absehbarer weiterer Verlauf']], 'わけではない begrenzt eine Aussage. Die Kritik am reinen Tempo ist keine Rechtfertigung unbegrenzten Wartens.', [
['Was ist die zentrale Forderung?', 2, ['Service auch nach der vermittelten Planungssicherheit beurteilen.', '見通しを持てたか ergänzt den reinen Zeitmaßstab.'], ['Antwortgeschwindigkeit grundsätzlich ignorieren.', 'Auch Fristen und Zwischenmeldungen bleiben nötig.'], ['Nur die erste Antwort automatisieren.', 'Automatisierung wird nicht als Lösung gefordert.'], ['Schwierige Anfragen gar nicht beantworten.', 'Ein Termin für eine ausführliche Antwort ist Teil der Lösung.']],
['Was änderte sich in der beschriebenen Einrichtung?', 1, ['Weniger Nachfragen trotz unveränderter Dauer bis zur endgültigen Antwort.', '回答までの時間は短くならなかったが markiert genau diesen Gegensatz.'], ['Alle Fragen wurden sofort abschließend gelöst.', 'Schwierige Fragen benötigen weiterhin Zeit.'], ['Die Nutzer durften nicht mehr nachfragen.', 'Es wird kein Verbot beschrieben.'], ['Es wurden keine Empfangsbestätigungen mehr versandt.', 'Empfang und Frist wurden nun ausdrücklich mitgeteilt.']],
['Welche Praxis entspricht dem Kommentar?', 2, ['Eine realistische Frist nennen und bei Verzögerungen aktiv informieren.', 'Fristtreue und laufende Erklärung setzen die These praktisch um.'], ['Eine beliebige Frist nennen und danach schweigen.', 'Die genannte Frist muss ernst genommen werden.'], ['Nur die Antwortminuten zählen, unabhängig vom Inhalt.', 'Genau diesen alleinigen Maßstab kritisiert der Text.'], ['Auf Klärung verzichten, solange sofort eine Standardantwort kommt.', 'Die Einleitung beschreibt dies als Risiko.']]
]);
add('reading', 'Zwei Meinungen zur Bibliothek', 'Gemeinsame Ziele und unterschiedliche Mittel in zwei Texten vergleichen.',
['意見Ａ：図書館の開館時間を延ばしてほしい。仕事帰りに利用したくても、閉館に間に合わない。電子書籍があれば十分という声もあるが、資料を手に取って比べたり、職員に相談したりする機会は画面だけでは得にくい。毎日でなく、週に一日でも夜に利用できれば助かる。', '意見Ｂ：夜間開館には人件費がかかる。限られた予算で利用の機会を広げるなら、まず予約した本を駅で受け取れる仕組みを整えてはどうか。相談の必要な人への対応は残すべきだが、本を借りるだけの人まで同じ場所、同じ時間に来る必要はない。', '両者とも、現在の時間帯では図書館を利用しにくい人がいるという認識は共有している。ただし、利用機会の改善を、建物に入れる時間を増やすことから始めるか、建物に行かなくてもできることを増やすことから始めるかで、優先順位が異なる。'],
'Meinung A wünscht längere Öffnungszeiten: Nach der Arbeit ist die Bibliothek oft schon zu. E-Books ersetzen das Vergleichen physischer Materialien und die Beratung nur bedingt. Ein Abend pro Woche würde bereits helfen. Meinung B verweist auf Personalkosten. Bei begrenztem Budget sollte man zuerst die Abholung reservierter Bücher am Bahnhof ermöglichen. Beratung soll erhalten bleiben, doch reine Ausleihe erfordert nicht für alle denselben Ort und dieselbe Zeit. Beide erkennen eingeschränkten Zugang. Sie unterscheiden sich darin, ob zuerst der Zugang zum Gebäude zeitlich erweitert oder mehr Nutzung ohne Besuch ermöglicht werden soll.',
[['夜間開館（やかんかいかん）', 'Abendöffnung'], ['優先順位（ゆうせんじゅんい）', 'Prioritätenfolge']], 'Ein gemeinsames Ziel bedeutet keine gleiche Priorität. B lehnt Beratung nicht ab und A verlangt keine tägliche Nachtöffnung.', [
['Worin stimmen beide überein?', 2, ['Die bisherigen Zugangszeiten erschweren manchen Menschen die Nutzung.', 'この認識を共有している wird im Vergleich ausdrücklich erläutert.'], ['Nur digitale Bücher sind künftig nötig.', 'A widerspricht einer solchen Ersetzung.'], ['Bibliotheksberatung sollte eingestellt werden.', 'B will sie ausdrücklich erhalten.'], ['Tägliche Nachtöffnung ist die einzige Lösung.', 'A akzeptiert einen Abend; B priorisiert ein anderes Mittel.']],
['Welche Leistung betont A besonders?', 0, ['Materialien vor Ort vergleichen und Beratung erhalten.', 'Diese Möglichkeiten begründen den Wunsch nach Abendöffnung.'], ['Reservierte Bücher am Bahnhof abholen.', 'Das ist Bs Vorschlag.'], ['Personalkosten durch Schließung senken.', 'A möchte zusätzliche Öffnung.'], ['Alle Bestände ausschließlich online lesen.', 'A hält den Bildschirm nicht für einen vollständigen Ersatz.']],
['Welcher erste Schritt entspricht eher B?', 1, ['Eine externe Abholung erproben und Beratung weiter anbieten.', 'B priorisiert Bahnhofsabholung bei erhaltener Beratung.'], ['Beratung abschaffen, um rund um die Uhr zu öffnen.', 'Beides widerspricht Bs Vorschlag.'], ['Sofort jeden Abend öffnen, ohne Kostenprüfung.', 'B nennt gerade die Budgetgrenze.'], ['Alle Nutzer zu identischen Besuchszeiten verpflichten.', 'B möchte diese Notwendigkeit verringern.']]
]);
add('reading', 'Die Grenze von Durchschnittswerten', 'Eine Kennzahl im Zusammenhang mit Verteilung und Zweck bewerten.',
['ある会社が会議時間の削減に取り組み、一回当たりの平均時間は六十分から四十分に短くなった。報告書では成果が強調されたが、社員への聞き取りでは、以前より忙しくなったという声も少なくなかった。数字が改善したのに、なぜ負担感は減らなかったのだろう。', '調べると、会議を時間どおりに終えるため、決められなかった事項を別の会議に回していたことがわかった。一回の時間は短くても、開催回数が増えれば、全体の時間は減らない。さらに、会議のたびに仕事を中断し、準備し直す手間は、一回の長さには表れない。', 'これは数値による管理そのものが無意味だという話ではない。何を改善したかったのかに戻り、指標がその目的を捉えているかを確かめる必要がある。負担を減らすのが目的なら、平均時間に加え、総時間や中断の回数、会議後に決定事項が実行できたかも見るべきだ。'],
'Ein Unternehmen senkte die mittlere Sitzungsdauer von 60 auf 40 Minuten und meldete Erfolg. Dennoch berichteten etliche Beschäftigte von mehr Belastung. Eine Prüfung ergab, dass ungelöste Punkte in zusätzliche Sitzungen verschoben wurden. Kürzere Einzeltermine sparen keine Gesamtzeit, wenn ihre Zahl steigt. Unterbrechung und erneute Vorbereitung sind im Mittelwert ebenfalls unsichtbar. Der Text verwirft Kennzahlen nicht, sondern verlangt zu prüfen, ob sie das eigentliche Ziel erfassen. Soll Belastung sinken, sind auch Gesamtzeit, Unterbrechungen und die Umsetzbarkeit von Beschlüssen relevant.',
[['指標（しひょう）', 'Indikator / Kennzahl'], ['中断（ちゅうだん）', 'Unterbrechung']], 'Eine Verbesserung des Durchschnitts beweist keine Verbesserung der Gesamtsituation. Achte auf die Bezugsgröße 一回当たり.', [
['Was will der Text zeigen?', 2, ['Eine Kennzahl muss zum eigentlichen Verbesserungsziel passen.', '目的を捉えているか ist der entscheidende Prüfmaßstab.'], ['Jede Zahlenmessung ist nutzlos.', 'Das wird ausdrücklich zurückgewiesen.'], ['Vierzig Minuten sind immer die ideale Sitzungsdauer.', 'Der Text legt keine ideale Dauer fest.'], ['Mitarbeiterbefragungen dürfen nicht berücksichtigt werden.', 'Sie decken hier gerade das Problem auf.']],
['Warum konnte die Belastung trotz kürzerer Sitzungen steigen?', 1, ['Offene Punkte führten zu mehr Sitzungen und Unterbrechungen.', 'Zusatztermine und erneute Vorbereitung erklären den Widerspruch.'], ['Alle Sitzungen wurden auf sechzig Minuten verlängert.', 'Der Durchschnitt sank.'], ['Es gab gar keine Entscheidungen mehr im Unternehmen.', 'Das ist eine unbelegte Verallgemeinerung.'], ['Die Zahl der Beschäftigten wurde verdoppelt.', 'Zur Mitarbeiterzahl steht nichts.']],
['Welche neue Auswertung wäre sinnvoll?', 2, ['Gesamtzeit und Unterbrechungen zusammen mit umsetzbaren Ergebnissen betrachten.', 'Diese zusätzlichen Größen werden aus dem Entlastungsziel abgeleitet.'], ['Nur besonders kurze Sitzungen zählen.', 'Das würde die einseitige Messung fortsetzen.'], ['Alle Befragungen durch denselben Mittelwert ersetzen.', 'Der Mittelwert allein war unzureichend.'], ['Erfolg allein am pünktlichen Sitzungsende festmachen.', 'Genau das kann offene Punkte in neue Sitzungen verschieben.']]
]);
add('reading', 'Ein gemeinsamer Arbeitsraum', 'Vertragsähnliche Alltagsinformationen mit Ausnahmen abgleichen.',
['共同作業室の利用案内。一般会員は月額四千円で平日の九時から十八時まで利用できます。夜間会員は月額六千円で、平日は二十二時まで利用できますが、土日の利用には、どちらの会員も一日五百円の追加料金が必要です。', '会議室は一回二時間まで、前日までの予約制です。一般会員は一時間五百円、夜間会員は月に合計四時間まで無料です。無料の範囲でも予約は必要で、余った時間を翌月へ繰り越すことはできません。', '入会月の月額料金は半額です。ただし、会議室と土日の追加料金は割引になりません。退会は希望月の十日までに届け出てください。十一日以降の届け出は翌月末の退会となり、利用しなくても翌月分の月額料金が発生します。'],
'Gemeinschaftlicher Arbeitsraum: Basismitgliedschaft 4.000 Yen monatlich, werktags 9–18 Uhr. Abendmitgliedschaft 6.000 Yen, werktags bis 22 Uhr. Wochenende kostet für beide zusätzlich 500 Yen pro Tag. Besprechungsräume sind spätestens am Vortag für höchstens zwei Stunden pro Termin zu buchen. Basis: 500 Yen je Stunde. Abend: insgesamt vier Stunden pro Monat kostenlos, trotzdem reservierungspflichtig und nicht übertragbar. Im Eintrittsmonat ist nur der Monatsbeitrag halbiert, nicht die Zusatzkosten. Kündigung bis zum 10. des gewünschten Austrittsmonats; spätere Meldung wirkt zum Ende des Folgemonats, dessen Beitrag auch ohne Nutzung anfällt.',
[['繰り越す（くりこす）', 'in den nächsten Zeitraum übertragen'], ['届け出（とどけで）', 'formelle Meldung']], '無料 betrifft den Preis, nicht die Reservierung. 月に合計四時間 ist ein Monatskontingent, nicht vier Stunden pro Termin.', [
['Welche Aussage beschreibt die Mitgliedschaften richtig?', 0, ['Die Abendmitgliedschaft erweitert Werktagszeiten; Wochenenden kosten bei beiden extra.', 'Die Zeitvorteile und die gemeinsame Zusatzgebühr sind getrennt geregelt.'], ['Abendmitglieder nutzen jedes Wochenende kostenlos.', 'どちらの会員も schließt sie in die Gebühr ein.'], ['Basismitglieder dürfen samstags nie hinein.', 'Wochenendnutzung ist gegen Aufpreis möglich.'], ['Beide Mitgliedschaften kosten gleich viel.', 'Vier- und sechstausend Yen werden unterschieden.']],
['Was gilt für kostenlose Besprechungsstunden der Abendmitglieder?', 1, ['Reservierung nötig, maximal zwei Stunden je Termin und vier je Monat.', 'Die allgemeine Termingrenze gilt innerhalb des Monatskontingents.'], ['Vier Stunden pro Termin ohne Anmeldung.', 'Das verwechselt Monatskontingent und Terminlänge und ignoriert die Reservierung.'], ['Ungenutzte Stunden verdoppeln das nächste Monatskontingent.', 'Übertragung ist ausgeschlossen.'], ['Kostenlos nur während des Eintrittsmonats.', 'Diese Freistunden sind ein regulärer Mitgliedsvorteil.']],
['Ein Abendmitglied tritt neu ein und nutzt einen Samstag, keine Besprechungsräume. Was kostet dieser Monat?', 2, ['3.500 Yen.', 'Halber Monatsbeitrag 3.000 plus ungekürzte Wochenendgebühr 500.'], ['3.250 Yen.', 'Auch die Wochenendgebühr zu halbieren wäre falsch.'], ['3.000 Yen.', 'Die Wochenendgebühr fehlt.'], ['6.500 Yen.', 'Die Ermäßigung des Eintrittsmonats wurde nicht angewandt.']]
]);
add('reading', 'Reparieren als Lernprozess', 'Die Funktion eines Beispiels für ein abstrakteres Argument erkennen.',
['壊れた物を直す活動は、ごみを減らす方法として紹介されることが多い。それは確かに重要だが、修理の場を見ていると、別の価値にも気づく。参加者は、普段は中身を意識しない道具を開き、どこが、なぜ動かなくなったのかを人と相談しながら考えている。', 'ある参加者は、結局直せなかったラジオを持ち帰りながら、「次に買うときは、開けやすい構造かも見たい」と話した。その日の修理成功率だけを見れば、この作業は失敗に数えられる。しかし、その人が物を選ぶ基準は変わった。成果は、当日動くようになった台数に限られないのである。', 'だからといって、直せなくても常によい経験になるとは言えない。原因や試した方法を共有せず、ただ専門家の手元を見るだけなら、参加者には何も残らないかもしれない。修理を学びの機会にするには、結果だけでなく、判断の過程を一緒にたどれる場づくりが欠かせない。'],
'Reparaturaktivitäten werden oft als Abfallvermeidung vorgestellt. Daneben öffnen Teilnehmer Geräte, deren Inneres sie sonst nicht beachten, und überlegen gemeinsam Ursachen. Eine Person nahm ein nicht repariertes Radio mit, wollte beim nächsten Kauf aber auf ein gut zu öffnendes Gehäuse achten. In der Tages-Erfolgsquote zählt das als Misserfolg, dennoch hat sich ein Auswahlkriterium verändert. Ergebnisse sind also nicht auf reparierte Stückzahlen beschränkt. Nicht jede erfolglose Reparatur ist automatisch lehrreich: Ohne gemeinsame Erklärung der Ursachen und Versuche bleibt beim bloßen Zuschauen womöglich nichts. Lernen erfordert, den Entscheidungsprozess gemeinsam nachvollziehen zu können.',
[['成功率（せいこうりつ）', 'Erfolgsquote'], ['過程（かてい）', 'Verlauf / Prozess']], 'Das Radiobeispiel widerlegt die Gleichsetzung „nicht repariert = nichts gewonnen“. Es beweist nicht, dass jede erfolglose Reparatur nützlich ist.', [
['Welche Position vertritt der Text?', 2, ['Reparatur kann durch gemeinsam nachvollziehbare Entscheidungen zum Lernen führen.', '判断の過程を一緒にたどれる benennt die notwendige Gestaltung.'], ['Defekte Geräte sollten niemals wieder funktionieren.', 'Reparieren bleibt ein wichtiges Ziel.'], ['Fachwissen verhindert grundsätzlich Lernen.', 'Problematisch ist bloßes Zuschauen ohne geteilte Erklärung.'], ['Jeder erfolglose Versuch ist automatisch ein Lernerfolg.', '常によい経験になるとは言えない begrenzt die Aussage.']],
['Was änderte sich bei der Person mit dem Radio?', 1, ['Sie will beim nächsten Kauf auch auf Zugänglichkeit des Inneren achten.', '開けやすい構造 wird zum neuen Auswahlkriterium.'], ['Ihr Radio funktionierte danach wieder.', 'Es konnte nicht repariert werden.'], ['Sie wollte nie wieder ein Gerät kaufen.', 'Sie spricht ausdrücklich vom nächsten Kauf.'], ['Sie bewertete nur die Tages-Erfolgsquote.', 'Die Quote ist die Perspektive, die der Autor als unvollständig zeigt.']],
['Welche Gestaltung würde dem Argument am besten entsprechen?', 2, ['Fachleute erklären ihre Vermutungen und besprechen Versuche mit Teilnehmenden.', 'So wird der Entscheidungsprozess gemeinsam zugänglich.'], ['Nur reparierte Geräte zählen und alle Fehlversuche verschweigen.', 'Das blendet die mögliche Lernwirkung aus.'], ['Teilnehmende schweigend nur von fern zuschauen lassen.', 'Dieses bloße Zuschauen wird als mögliche Leerstelle beschrieben.'], ['Jede Diagnose vermeiden, damit niemand enttäuscht wird.', 'Ursachen und Methoden sollen gerade geteilt werden.']]
]);
add('listening', 'Eine Entscheidung im Team', 'Vorbehalt, Zustimmung und Beschluss in einer Besprechung erkennen.',
['A: 新しい予約画面、来週公開という予定でしたね。試してもらった人からは、見た目がわかりやすいという評価が多かったです。\nB: ただ、日付を変更したあとに人数が元に戻ることがあるんです。見た目の問題というより、予約内容を間違えるおそれがあります。', 'A: それは公開前に直す必要がありますね。説明を追加するだけではだめですか。\nB: 毎回説明を読んでもらえるとは限りませんし、入力した人数はそのまま残るべきでしょう。原因の確認に二日、修正とテストにあと二日はほしいです。', 'A: では、公開は一週間延ばしましょう。今日中に関係者へ理由を伝えます。\nB: お願いします。私はまず、どの操作で起きるかを整理します。見た目の細かい調整は、そのあとに回します。'],
'A: Die neue Reservierungsseite sollte nächste Woche veröffentlicht werden. Testpersonen fanden sie meist übersichtlich. B: Nach einer Datumsänderung springt aber manchmal die Personenzahl zurück. Das gefährdet die Buchungsdaten. A: Das muss vorher behoben werden. Reicht ein Hinweis? B: Hinweise werden nicht immer gelesen; eingegebene Zahlen sollten erhalten bleiben. Zwei Tage für Ursachenklärung, zwei weitere für Korrektur und Test wären nötig. A: Wir verschieben um eine Woche und ich informiere heute die Beteiligten. B: Ich grenze zuerst die auslösenden Schritte ein; optische Feinheiten kommen später.',
[['おそれ', 'Risiko / Gefahr'], ['関係者（かんけいしゃ）', 'Beteiligte']], '見た目の問題というより korrigiert die Problemkategorie: Datenrichtigkeit hat hier Vorrang vor Gestaltung.', [
['Warum wird die Veröffentlichung verschoben?', 0, ['Ein Fehler kann zu falschen Reservierungsdaten führen.', 'B beschreibt das Zurücksetzen der Personenzahl als inhaltliches Risiko.'], ['Die Mehrheit findet die Seite unübersichtlich.', 'Die Rückmeldungen zum Aussehen waren überwiegend positiv.'], ['Es fehlen sämtliche Reservierungsfunktionen.', 'Beschrieben ist ein bestimmter Fehler.'], ['Die Beteiligten wollen grundsätzlich keine neue Seite.', 'Eine solche Ablehnung wird nicht geäußert.']],
['Wie bewertet B einen zusätzlichen Erklärungstext?', 1, ['Er reicht nicht, weil er womöglich nicht gelesen wird und die Eingabe erhalten bleiben sollte.', 'B nennt sowohl Nutzerverhalten als auch erwartete Funktion.'], ['Er ersetzt sicher jede technische Korrektur.', 'B weist diese Lösung als unzureichend zurück.'], ['Er ist nur wegen seiner Farbe ungeeignet.', 'Farbe ist nicht Bs Argument.'], ['Er macht weitere Tests unnötig.', 'B plant ausdrücklich Korrektur und Tests.']],
['Was tut B zuerst?', 2, ['Die auslösenden Bedienungsschritte eingrenzen.', 'まず und どの操作で起きるか benennen die erste Aufgabe.'], ['Die optischen Feinheiten abschließen.', 'Diese werden zurückgestellt.'], ['Allen Beteiligten den Termin erklären.', 'Das übernimmt A.'], ['Die Seite sofort veröffentlichen.', 'Es wurde eine Verschiebung beschlossen.']]
]);
add('listening', 'Eine Ansage im Zug', 'Priorisierte Anweisungen unter mehreren Reisemöglichkeiten verstehen.',
['お客様にご案内いたします。この列車は前方の設備確認のため、次の桜町駅で運転を見合わせます。運転再開まで、少なくとも三十分かかる見込みです。再開時刻は決まり次第お知らせいたします。', '空港へお急ぎのお客様は、桜町駅で空港行きのバスにお乗り換えください。バス乗り場は東口です。駅の西口にもバス乗り場がありますが、空港行きは発車いたしません。なお、バスの運賃は別途必要です。', '桜町駅より先へお越しで、空港以外が目的地のお客様は、車内で次の案内をお待ちください。現在、他社線での振替輸送を調整しておりますが、まだご利用いただける段階ではありません。'],
'Wegen einer technischen Prüfung voraus wird dieser Zug am nächsten Bahnhof Sakuramachi angehalten. Die Wiederaufnahme dauert voraussichtlich mindestens 30 Minuten; eine genaue Zeit wird noch bekannt gegeben. Wer dringend zum Flughafen muss, soll dort in den Flughafenbus am Ostausgang umsteigen. Am Westausgang gibt es ebenfalls Busse, aber keine zum Flughafen. Der Bus kostet zusätzlich. Reisende zu anderen Zielen hinter Sakuramachi sollen im Zug auf weitere Hinweise warten. Eine Ersatzbeförderung über andere Bahnen wird abgestimmt, kann aber noch nicht genutzt werden.',
[['見合わせる（みあわせる）', 'vorläufig aussetzen'], ['別途（べっと）', 'gesondert / zusätzlich']], '少なくとも nennt eine Untergrenze. 調整しております ist ein laufender Prozess, keine bestätigte Freigabe.', [
['Wie ist die Betriebslage?', 0, ['Halt in Sakuramachi; die Weiterfahrt verzögert sich mindestens ungefähr eine halbe Stunde.', '見込み bezeichnet eine Prognose, nicht eine garantierte Wiederaufnahmezeit.'], ['Der Zug fährt garantiert in genau dreißig Minuten weiter.', '少なくとも und die noch offene Uhrzeit schließen diese Garantie aus.'], ['Der Zug fährt ohne Halt direkt zum Flughafen.', 'Er stellt den Betrieb am nächsten Bahnhof vorläufig ein.'], ['Alle anderen Bahnlinien sind bereits kostenlos freigegeben.', 'Ersatzbeförderung wird noch abgestimmt.']],
['Wo fährt der Flughafenbus ab und was gilt für den Preis?', 1, ['Am Ostausgang, mit gesondertem Fahrpreis.', '東口 und 別途必要 sind die relevanten Angaben.'], ['Am Westausgang ohne Aufpreis.', 'Ort und Preis sind beide falsch.'], ['An beiden Ausgängen zum gleichen Bahntarif.', 'Am Westausgang fährt kein Flughafenbus.'], ['Direkt am Bahnsteig kostenlos.', 'Das wird nicht angeboten.']],
['Eine Person fährt weiter, aber nicht zum Flughafen. Was soll sie jetzt tun?', 2, ['Im Zug auf weitere Hinweise warten.', 'Für genau diese Zielgruppe wird dies ausdrücklich gesagt.'], ['Sofort eine andere Bahn als bereits freigegeben nutzen.', 'Die Abstimmung ist noch nicht abgeschlossen.'], ['Unbedingt den Flughafenbus nehmen.', 'Dieser Hinweis gilt nur für eilige Flughafenreisende.'], ['Am Westausgang einen garantierten kostenlosen Ersatzbus suchen.', 'Eine solche Verbindung wurde nicht zugesagt.']]
]);
add('listening', 'Eine Kundin äußert Bedenken', 'Indirekte Ablehnung und eine akzeptable Alternative heraushören.',
['A: 今回の広告案ですが、若い人に親しみを持ってもらおうと、かなりくだけた表現にしました。\nB: 狙いはわかります。ただ、私どもの店には長く通ってくださる方も多いので、急に別の店になったように感じられては、と思うんです。', 'A: では、全部を以前の表現に戻しましょうか。\nB: いえ、新しい方に届く工夫は必要です。写真は今の案を生かして、文章だけ少し落ち着いた調子にできませんか。', 'A: 承知しました。見出しも変えますか。\nB: 見出しは短くて目を引くので、そのままで。本文で店が大切にしてきたことが伝われば、全体として違和感は減ると思います。'],
'A: Für die Werbung habe ich einen lockeren Ton gewählt, um junge Menschen anzusprechen. B: Ich verstehe das Ziel. Viele Stammkunden besuchen uns aber schon lange; ich möchte vermeiden, dass sie uns plötzlich für ein anderes Geschäft halten. A: Sollen wir alles zurücksetzen? B: Nein, neue Menschen zu erreichen bleibt wichtig. Behalten wir die Fotos und beruhigen nur den Text etwas. A: Auch die Überschrift ändern? B: Die ist kurz und auffällig, sie kann bleiben. Wenn im Haupttext unsere langjährigen Werte erkennbar sind, wirkt der Entwurf insgesamt stimmiger.',
[['くだけた表現（くだけたひょうげん）', 'lockere / umgangssprachliche Formulierung'], ['本文（ほんぶん）', 'Haupttext']], 'B formuliert die Kritik zurückhaltend, lehnt aber weder neue Kundschaft noch die ganze Kampagne ab.', [
['Was ist Bs Hauptbedenken?', 0, ['Stammkunden könnten die vertraute Identität des Geschäfts nicht wiedererkennen.', '別の店になったように感じられては formuliert diese Befürchtung indirekt.'], ['Junge Menschen sollen grundsätzlich nicht angesprochen werden.', 'B bestätigt später den Bedarf neuer Ansprache.'], ['Die Fotos sind technisch unscharf.', 'B möchte die Fotos behalten.'], ['Die Werbung enthält zu wenig Preise.', 'Preise werden nicht besprochen.']],
['Was soll aus dem aktuellen Entwurf erhalten bleiben?', 1, ['Die Fotos.', '写真は今の案を生かして ist eine ausdrückliche Zustimmung.'], ['Der gesamte lockere Haupttext ohne Änderung.', 'Der Text soll ruhiger werden.'], ['Nur die alte Fassung.', 'B lehnt eine vollständige Rückkehr ab.'], ['Gar kein Bestandteil.', 'Mehrere Bestandteile dürfen bleiben.']],
['Wie sollte A den Entwurf überarbeiten?', 2, ['Überschrift und Fotos behalten, im Haupttext ruhiger die Werte des Geschäfts vermitteln.', 'Bs letzter Beitrag präzisiert genau diesen begrenzten Änderungsauftrag.'], ['Auch die akzeptierte Überschrift durch einen langen Erklärungstext ersetzen.', 'B möchte sie unverändert behalten.'], ['Alles in den alten Stil zurücksetzen.', 'B lehnt diesen Vorschlag ausdrücklich ab.'], ['Nur die Fotos entfernen und den Text noch lockerer machen.', 'Das widerspricht beiden konkreten Wünschen.']]
]);
add('listening', 'Was eine Befragung zeigen kann', 'Eine vorsichtige Schlussfolgerung von einer Überinterpretation unterscheiden.',
['A: 新しい休憩室のアンケート、利用した人の八割が満足と答えています。これなら、全社員に好評だと言えそうですね。\nB: ちょっと待ってください。回答したのは昼間に休憩室を使った人だけですよね。夜勤の人や、そもそも使っていない人の意見は入っていません。', 'A: でも、利用者の評価としては高いわけですよね。\nB: それは言えます。ただ、使わない理由が「必要ない」のか「場所が遠くて行けない」のかでは、次の対応が違ってきます。満足度だけでは、そこはわかりません。', 'A: では、報告には対象を明記して、未利用の人にも短い調査を追加しましょう。\nB: ええ。今ある結果を捨てる必要はありません。言える範囲をはっきりさせたうえで、足りない情報を集めればいいと思います。'],
'A: Achtzig Prozent der befragten Nutzer des neuen Pausenraums sind zufrieden. Dann ist er wohl bei allen Beschäftigten beliebt. B: Moment: Befragt wurden nur Menschen, die ihn tagsüber nutzten, keine Nachtschicht und keine Nichtnutzer. A: Aber bei den Nutzern ist die Bewertung gut. B: Ja. Ob Nichtnutzer ihn nicht brauchen oder wegen der Entfernung nicht erreichen, verlangt jedoch unterschiedliche Maßnahmen und ist aus Zufriedenheit allein nicht erkennbar. A: Wir nennen im Bericht die Zielgruppe und ergänzen eine kurze Befragung der Nichtnutzer. B: Genau. Vorhandene Ergebnisse bleiben nützlich, wenn ihre Reichweite klar ist und fehlende Informationen ergänzt werden.',
[['夜勤（やきん）', 'Nachtschicht'], ['明記（めいき）', 'ausdrückliche Angabe']], 'Die Einwendung betrifft die Reichweite der Daten. B bestreitet nicht das positive Ergebnis der tatsächlich Befragten.', [
['Was beanstandet B an As Schlussfolgerung?', 0, ['Die befragte Gruppe steht nicht für alle Beschäftigten.', 'Nachtpersonal und Nichtnutzer fehlen in der Befragung.'], ['Achtzig Prozent seien grundsätzlich ein schlechter Wert.', 'B bestätigt die positive Bewertung der Nutzer.'], ['Es sei verboten, Beschäftigte zu befragen.', 'B unterstützt eine weitere Befragung.'], ['Niemand habe den Raum je genutzt.', 'Die Befragung umfasst gerade Nutzer.']],
['Warum möchte B Gründe für Nichtnutzung kennen?', 1, ['Fehlender Bedarf und schlechte Erreichbarkeit erfordern unterschiedliche Maßnahmen.', 'B stellt diese zwei Gründe mit verschiedenen Konsequenzen gegenüber.'], ['Um die vorhandenen Antworten nachträglich zu verändern.', 'Es sollen zusätzliche Informationen erhoben werden.'], ['Weil jede Nichtnutzung zwingend Unzufriedenheit bedeutet.', 'B unterscheidet verschiedene mögliche Gründe.'], ['Damit künftig nur zufriedene Menschen antworten.', 'Die neue Befragung soll die Reichweite erweitern.']],
['Wie soll der Bericht gestaltet werden?', 2, ['Den bisherigen Geltungsbereich nennen und fehlende Perspektiven ergänzen.', 'A schlägt dies vor und B stimmt ausdrücklich zu.'], ['Alle Ergebnisse als wertlos löschen.', 'B hält das ausdrücklich für unnötig.'], ['Unverändert von allen Beschäftigten sprechen.', 'Genau diese Verallgemeinerung wurde kritisiert.'], ['Den Anteil ohne Angabe der Befragten erhöhen.', 'Eine solche Manipulation wird nicht vorgeschlagen.']]
]);
add('listening', 'Zwei Veranstaltungsorte', 'Eine Entscheidung unter konkurrierenden Anforderungen nachvollziehen.',
['A: 交流会の会場ですが、駅前のホールは百人入れて、費用も予算内です。ただ、机を動かせないので、グループに分かれる活動には向きません。\nB: 今回は話を聞くだけでなく、参加者同士で意見を出し合うのが中心でしたね。', 'A: 川沿いの施設なら配置は自由ですが、定員は六十人です。参加希望は今のところ七十人。それに駅から徒歩十五分かかります。\nB: 人数だけなら駅前ですが、目的を考えると川沿いのほうがよさそうですね。二回に分けることはできますか。', 'A: 同じ日に午前と午後なら借りられます。合計費用は少し予算を超えますが、資料を紙からデータにすれば、その分は減らせます。\nB: では、二回開催で進めましょう。ただし、参加者がどちらかの時間を選べるか、先に確認してください。難しい人が多ければ、もう一度会場を考えます。'],
'A: Der Bahnhofssaal fasst hundert Personen und liegt im Budget, hat aber unbewegliche Tische, schlecht für Gruppenarbeit. B: Gegenseitiger Austausch ist dieses Mal zentral. A: Am Fluss ist die Einrichtung flexibel, aber nur sechzig Plätze für bisher siebzig Interessierte; zudem fünfzehn Minuten Fußweg. B: Zahlen sprechen für den Bahnhof, der Zweck eher für den Fluss. Gehen zwei Termine? A: Vormittags und nachmittags am selben Tag wäre möglich. Es kostet etwas mehr, was digitale statt gedruckter Unterlagen ausgleichen könnten. B: Planen wir zwei Durchgänge, prüfen aber zuerst, ob die Teilnehmer zwischen den Zeiten wählen können. Falls viele nicht können, prüfen wir den Ort neu.',
[['配置（はいち）', 'Anordnung'], ['定員（ていいん）', 'Kapazität']], 'では … ただし ist ein Beschluss mit Vorbehalt. Die Zweiteilung ist noch von der Verfügbarkeit der Teilnehmenden abhängig.', [
['Welches Kriterium gibt den Ausschlag zugunsten des Flussgebäudes?', 1, ['Die Eignung für den geplanten Austausch in Gruppen.', 'B gewichtet den Veranstaltungszweck stärker als die reine Platzanzahl.'], ['Es liegt näher am Bahnhof.', 'Es liegt fünfzehn Gehminuten entfernt.'], ['Es bietet mehr Plätze als der Bahnhofssaal.', 'Sechzig sind weniger als hundert.'], ['Es kostet in jedem Fall weniger.', 'Zwei Durchgänge liegen zunächst leicht über Budget.']],
['Wie könnte die Budgetüberschreitung ausgeglichen werden?', 2, ['Mit digitalen statt gedruckter Unterlagen.', '資料を紙からデータにする nennt die Einsparung.'], ['Durch eine kostenlose dritte Veranstaltung.', 'Eine solche Option wird nicht genannt.'], ['Indem die Raumkapazität ignoriert wird.', 'Die Kapazität wird durch zwei Durchgänge berücksichtigt.'], ['Durch fest zugesagte zusätzliche Eintrittsgelder.', 'Solche Einnahmen werden nicht erwähnt.']],
['Was ist vor der endgültigen Umsetzung zu prüfen?', 2, ['Ob die Teilnehmer eine der beiden Zeiten wahrnehmen können.', 'B verlangt diese Rückfrage und nennt andernfalls eine erneute Ortsprüfung.'], ['Ob hundert Personen gleichzeitig in den kleinen Raum passen.', 'Die genannte Kapazität beträgt sechzig.'], ['Ob die Tische am Bahnhof doch schon beweglich sind.', 'Das ist nicht der vereinbarte nächste Prüfschritt.'], ['Ob alle zwingend beide Durchgänge besuchen.', 'Die Teilnehmer sollen eine Zeit wählen, nicht beide besuchen.']]
]);
require('./n2-expansion.cjs')(add);
};
