module.exports = add => {
add('reading', 'Ein Regal für die Nachbarschaft', 'Die Hauptidee eines Alltagsartikels von Beispielen unterscheiden.',
['駅前の喫茶店に、小さな「本の交換棚」ができた。読み終わった本を一冊置けば、気に入った本を一冊持ち帰れる。お金はかからず、店で飲み物を注文しなくても利用できる。', '店長は、最初は本が減るばかりではないかと心配していた。しかし、一か月後には、持ち帰る人より置いていく人のほうが多いとわかった。棚には、店長自身なら選ばないような本も並ぶようになった。', '今では本に短い感想の紙をはさむ人もいる。店長は「本を通して、話したことのない近所の人を少し知ることができます」と話す。棚を増やすより、まずこの小さな交流を大切にしたいという。'],
'Im Café am Bahnhof gibt es ein Büchertauschregal: Wer ein gelesenes Buch abgibt, darf eines mitnehmen. Die Nutzung ist kostenlos und erfordert keine Bestellung. Der Inhaber befürchtete zunächst, dass die Bücher nur weniger würden. Nach einem Monat stellte sich heraus, dass mehr Menschen Bücher bringen als mitnehmen. So stehen auch Bücher dort, die er selbst nicht gewählt hätte. Manche legen kurze Eindrücke bei. Der Inhaber sagt, er lerne durch die Bücher Nachbarn kennen, mit denen er noch nie gesprochen habe. Bevor er weitere Regale aufstellt, möchte er diesen kleinen Austausch pflegen.',
[['交換（こうかん）', 'Austausch'], ['感想（かんそう）', 'persönlicher Eindruck']], '最初は und しかし markieren eine korrigierte Erwartung. Die Sorge am Anfang ist nicht das spätere Ergebnis.', [
['Was steht im Mittelpunkt des Artikels?', 2, ['Ein Büchertausch schafft kleine Kontakte in der Nachbarschaft.', 'Das Schlusszitat deutet das Regal als Austausch zwischen Menschen.'], ['Ein Café verdient mehr Geld mit Buchverkäufen.', 'Die Nutzung ist kostenlos; ein Verkauf wird nicht beschrieben.'], ['Der Inhaber ersetzt Gespräche durch Werbung.', 'Die eingelegten Texte sind persönliche Eindrücke.'], ['Eine Bibliothek wird wegen Besuchermangels geschlossen.', 'Weder Schließung noch Bibliothek sind das Thema.']],
['Was überraschte den Inhaber nach einem Monat?', 1, ['Es wurden mehr Bücher gebracht als mitgenommen.', '置いていく人のほうが多い widerlegt seine Sorge.'], ['Alle Bücher waren verschwunden.', 'Die Sorge traf gerade nicht ein.'], ['Nur seine Lieblingsbücher wurden gebracht.', 'Auch Bücher außerhalb seiner eigenen Auswahl kamen hinzu.'], ['Jeder Besucher bestellte ein Getränk.', 'Bestellungen sind keine Voraussetzung und werden nicht gezählt.']],
['Was würde am besten zur Haltung des Inhabers passen?', 2, ['Leser weiterhin zu kurzen persönlichen Eindrücken ermutigen.', 'Das unterstützt den von ihm geschätzten kleinen Austausch.'], ['Zuerst möglichst viele Regale aufstellen.', 'Das stellt er ausdrücklich hinter die Qualität des Austauschs.'], ['Nur noch von ihm ausgewählte Bücher erlauben.', 'Die unerwartete Vielfalt wird nicht als Problem bewertet.'], ['Die Nutzung an eine teure Bestellung binden.', 'Bisher ist die Nutzung ohne Bestellung möglich.']]
]);
add('reading', 'Warum der Bus früher kommt', 'Ursache und Wirkung einer Fahrplanänderung erklären.',
['市の循環バスは、来月から平日の朝だけ出発時刻が五分早くなる。駅で電車に乗り換える利用者から、現在の時刻では間に合わないことがあるという意見が多く寄せられたためだ。', 'バスの台数を増やす案もあったが、運転手が足りず、今回は実現しなかった。そのため、便の数と通る道は変えず、時刻だけを調整する。休日の時刻表には変更がない。', '市は一か月間、駅での乗り換えがどう変わったか調べる。出発を早めることで、別の停留所で乗れなくなる人がいないかも確認し、その結果を見て再び時刻を見直す予定だ。'],
'Der städtische Rundbus fährt ab nächsten Monat an Werktagmorgen fünf Minuten früher ab. Viele Fahrgäste hatten gemeldet, dass sie mit den bisherigen Zeiten manchmal den Anschlusszug verpassen. Mehr Busse einzusetzen wurde erwogen, scheitert vorerst aber am Fahrermangel. Anzahl der Fahrten und Strecke bleiben gleich; der Feiertags- und Wochenendfahrplan bleibt unverändert. Die Stadt untersucht einen Monat lang den Umstieg am Bahnhof und prüft zugleich, ob durch die frühere Abfahrt Menschen an anderen Haltestellen den Bus verpassen. Danach soll der Fahrplan erneut geprüft werden.',
[['乗り換え（のりかえ）', 'Umstieg'], ['見直す（みなおす）', 'überprüfen und gegebenenfalls ändern']], 'Ein nicht umgesetzter Vorschlag ist kein Bestandteil des neuen Fahrplans. Achte auf 実現しなかった.', [
['Was soll die Änderung vor allem verbessern?', 0, ['Den Anschluss vom Bus zum Zug.', 'Die Rückmeldungen über verpasste Anschlüsse begründen die Änderung.'], ['Die Geschwindigkeit der Züge.', 'Geändert wird der Busfahrplan.'], ['Die Anzahl der Feiertagsfahrten.', 'Diese Zeiten bleiben unverändert.'], ['Die Länge der Busstrecke.', 'Die Strecke bleibt gleich.']],
['Warum fahren nicht mehr Busse?', 1, ['Es fehlen Fahrer.', '運転手が足りず nennt das Hindernis.'], ['Die Stadt hat keine Busstrecke.', 'Eine Strecke existiert und bleibt bestehen.'], ['Niemand hatte zusätzliche Busse vorgeschlagen.', 'Es gab ausdrücklich einen solchen Vorschlag.'], ['Alle Züge fahren jetzt seltener.', 'Über weniger Züge wird nichts gesagt.']],
['Welche Auswertung wäre für die Stadt passend?', 2, ['Sowohl bessere Zuganschlüsse als auch verpasste Busse an anderen Haltestellen prüfen.', 'Die Stadt nennt beide Folgen der früheren Abfahrt.'], ['Nur zählen, ob mehr Fahrkarten verkauft werden.', 'Der Text nennt andere konkrete Prüffragen.'], ['Die Änderung ohne Prüfung dauerhaft festschreiben.', 'Eine erneute Prüfung ist vorgesehen.'], ['Nur den unveränderten Feiertagsfahrplan untersuchen.', 'Untersucht werden die Auswirkungen der geänderten Abfahrten.']]
]);
add('reading', 'Arbeiten von zu Hause', 'Eine differenzierte Alltagserfahrung zusammenfassen.',
['在宅勤務を始めたころ、通勤がなくなれば自由な時間が増えると思っていた。実際、朝は楽になったが、仕事が終わってもメールが気になり、以前より遅くまでパソコンを開く日が増えた。', 'そこで、仕事用の机を寝室から出し、夕方六時にはパソコンを閉じることにした。急ぎの連絡は電話でもらうよう同僚に伝えたので、大事な用件を見逃す不安も減った。', '在宅勤務がよいか悪いかは、家にいる時間の長さだけでは決められない。私には、仕事を始める場所と終える時刻をはっきりさせることが必要だった。便利な制度も、自分に合う使い方を考えて初めて役に立つのだと思う。'],
'Als ich anfing, von zu Hause zu arbeiten, erwartete ich mehr Freizeit ohne Pendeln. Morgens wurde es tatsächlich leichter, aber auch nach Feierabend beschäftigten mich E-Mails, und ich saß häufiger länger am Rechner. Deshalb stellte ich den Arbeitstisch aus dem Schlafzimmer heraus und beschloss, den Computer um 18 Uhr zu schließen. Für dringende Anliegen bat ich Kollegen um einen Anruf, was die Sorge verringerte, Wichtiges zu verpassen. Ob Heimarbeit gut ist, lässt sich nicht allein an der zu Hause verbrachten Zeit messen. Ich brauchte einen klaren Arbeitsort und Feierabend. Eine bequeme Regelung hilft erst mit einer persönlich passenden Nutzung.',
[['在宅勤務（ざいたくきんむ）', 'Arbeit von zu Hause'], ['用件（ようけん）', 'Anliegen']], 'Der Schluss verallgemeinert eine persönliche Erfahrung vorsichtig. Er fordert keine identische Regel für alle.', [
['Welche Aussage trifft die Haltung der schreibenden Person?', 2, ['Heimarbeit braucht eine zur Person passende Gestaltung.', '自分に合う使い方 ist der Schlussgedanke.'], ['Heimarbeit ist für jeden grundsätzlich schlecht.', 'Die Person lehnt die Regelung nicht generell ab.'], ['Ohne Pendeln entsteht automatisch mehr Freizeit.', 'Diese anfängliche Erwartung hat sich nicht vollständig erfüllt.'], ['Alle müssen im Schlafzimmer arbeiten.', 'Der eigene Tisch wurde gerade aus dem Schlafzimmer entfernt.']],
['Wie bleiben dringende Anliegen erreichbar?', 1, ['Durch Anrufe von Kollegen.', '急ぎの連絡は電話でもらう vereinbart diesen Kanal.'], ['Durch ständiges Lesen aller E-Mails nachts.', 'Der Computer soll um sechs geschlossen werden.'], ['Durch tägliche Fahrten ins Büro.', 'Das wird nicht als Lösung genannt.'], ['Durch den Verzicht auf jede Kommunikation.', 'Dringende Kommunikation bleibt möglich.']],
['Was dürfte der Person bei einem neuen Arbeitsmodell wichtig sein?', 2, ['Klare Grenzen zwischen Arbeit und Freizeit.', 'Ort und Endzeit haben ihr konkret geholfen.'], ['Möglichst lange am Rechner bleiben.', 'Gerade die unklar verlängerte Arbeitszeit war das Problem.'], ['Nur die eingesparte Fahrzeit vergleichen.', 'Der Text erklärt diese Betrachtung für unzureichend.'], ['Jede Regel unverändert übernehmen.', 'Die Nutzung soll an die eigene Situation angepasst werden.']]
]);
add('reading', 'Die passende Veranstaltung finden', 'Mehrere Bedingungen in einem Informationsangebot prüfen.',
['市民センター・週末講座。写真講座は土曜十時から十二時、参加費千円。自分のカメラが必要です。スマートフォンでは参加できません。定員は十人です。', '動画講座は土曜十四時から十六時、参加費千五百円。スマートフォンをお持ちください。編集用のパソコンは会場で貸し出します。初めての方も参加できます。', '申し込みはどちらも木曜までに窓口かウェブで。電話では受け付けません。空きがあっても当日の参加はできません。動画講座だけ、作った作品を講座後にメールで送ってもらえます。'],
'Wochenendkurse im Bürgerzentrum: Fotografieren am Samstag 10–12 Uhr, 1.000 Yen, eigene Kamera erforderlich; Smartphones sind nicht zugelassen. Zehn Plätze. Videokurs am Samstag 14–16 Uhr, 1.500 Yen. Bitte Smartphone mitbringen, Computer für den Schnitt werden gestellt. Anfänger können teilnehmen. Anmeldung für beide bis Donnerstag am Schalter oder online, nicht telefonisch. Spontane Teilnahme ist auch bei freien Plätzen nicht möglich. Nur im Videokurs erhält man sein Werk nachher per E-Mail.',
[['定員（ていいん）', 'maximale Teilnehmerzahl'], ['貸し出す（かしだす）', 'zur Nutzung ausleihen']], 'どちらも gilt für beide Angebote; だけ beschränkt eine Leistung auf genau eines.', [
['Was gilt für beide Kurse?', 2, ['Eine Anmeldung bis Donnerstag ist nötig.', 'どちらも bezieht die Frist auf beide Kurse.'], ['Man kann spontan bei freien Plätzen kommen.', '当日の参加はできません schließt das aus.'], ['Man bekommt sein Werk per E-Mail.', 'Das gilt nur für den Videokurs.'], ['Eine telefonische Anmeldung reicht.', 'Telefonische Anmeldung wird ausgeschlossen.']],
['Was wird im Videokurs bereitgestellt?', 1, ['Ein Computer für die Bearbeitung.', '編集用のパソコンは会場で貸し出します nennt die Ausleihe.'], ['Ein Smartphone zum Mitnehmen.', 'Das Smartphone soll selbst mitgebracht werden.'], ['Eine eigene Kamera für jeden.', 'Eine solche Ausgabe wird nicht genannt.'], ['Ein kostenloser Platz im Fotokurs.', 'Die Kurse sind getrennte kostenpflichtige Angebote.']],
['Eine Anfängerin hat nur ein Smartphone und nachmittags Zeit. Was sollte sie tun?', 1, ['Den Videokurs wählen und sich bis Donnerstag online oder am Schalter anmelden.', 'Zeit, Gerät und Zulassung passen; die gemeinsame Anmeldefrist bleibt nötig.'], ['Zum Fotokurs erst am Samstag ohne Anmeldung gehen.', 'Gerät, Tageszeit und Anmeldung passen nicht.'], ['Donnerstag telefonisch den Videokurs buchen.', 'Telefonische Anmeldungen werden nicht angenommen.'], ['Einen eigenen Schnittcomputer kaufen, bevor sie buchen darf.', 'Ein Computer wird am Veranstaltungsort ausgeliehen.']]
]);
add('reading', 'Ein Laden mit weniger Verpackung', 'Erfolg und Grenzen einer Maßnahme gemeinsam bewerten.',
['商店街の八百屋が、野菜を袋に入れずに売り始めた。客は必要な数だけ選び、持ってきた袋に入れる。店によると、使い捨ての袋は以前の半分に減ったが、客の数は特に変わっていない。', '一方、買い物に慣れていない客からは「一個の値段がわかりにくい」という声が出た。店は大きな値札をつけ、重さで売る野菜には、およそ二人分の値段も示すことにした。', '店主は、袋をなくすだけで環境にやさしい店になるとは考えていない。必要以上に買って家で捨てる野菜が減ることも大切だという。来月は客に、買った量がちょうどよかったかを聞く予定だ。'],
'Ein Gemüseladen in der Einkaufsstraße verkauft Gemüse nun ohne Tüten. Kunden wählen die benötigte Stückzahl und nutzen eigene Taschen. Einwegtüten wurden halbiert, die Kundenzahl blieb ungefähr gleich. Unerfahrene Kunden fanden die Einzelpreise unklar. Der Laden beschloss größere Preisschilder und bei gewichtsabhängigen Preisen einen ungefähren Preis für zwei Portionen. Der Inhaber sieht Tütenverzicht allein noch nicht als ausreichenden Umweltschutz. Auch weniger weggeworfenes Gemüse durch passendere Einkaufsmengen sei wichtig. Nächsten Monat will er Kunden fragen, ob ihre gekaufte Menge richtig war.',
[['使い捨て（つかいすて）', 'zum einmaligen Gebrauch'], ['値札（ねふだ）', 'Preisschild']], 'Ein gemessenes Ergebnis und ein noch zu prüfendes Ziel sind verschieden: Tüten wurden schon reduziert; Haushaltsabfälle noch nicht gemessen.', [
['Welche Aussage fasst den Artikel am besten zusammen?', 2, ['Weniger Verpackung ist ein Anfang; passende Mengen und klare Information gehören dazu.', 'Der Inhaber erweitert den Blick von Tüten auf vermeidbare Lebensmittelabfälle.'], ['Ohne Tüten ist jedes Umweltproblem bereits gelöst.', 'Diese Schlussfolgerung wird ausdrücklich nicht gezogen.'], ['Der Laden will nur noch große Mengen verkaufen.', 'Kunden sollen die benötigte Menge wählen.'], ['Weniger Tüten haben die Kundenzahl halbiert.', 'Halbiert wurde der Tütenverbrauch, nicht die Kundenzahl.']],
['Wie reagiert der Laden auf Preisunsicherheit?', 1, ['Mit größeren Schildern und einem Preisbeispiel für zwei Portionen.', 'Beide Informationshilfen sind als Reaktion genannt.'], ['Mit einem Verbot kleiner Einkäufe.', 'Ein solches Verbot wird nicht genannt.'], ['Mit einem einheitlichen Preis für alle Gemüsearten.', 'Der Text behält verschiedene Preisarten bei.'], ['Mit dem Abschaffen sämtlicher Preisschilder.', 'Die Schilder werden größer.']],
['Welche Aussage wäre nach dem Text noch zu überprüfen?', 2, ['Ob Kunden zu Hause tatsächlich weniger Gemüse wegwerfen.', 'Die geplante Befragung soll die Passung der Mengen erst untersuchen.'], ['Ob überhaupt weniger Einwegtüten genutzt werden.', 'Dazu liegt bereits die Angabe „halb so viele“ vor.'], ['Ob der Laden Gemüse verkauft.', 'Das steht fest.'], ['Ob sich Kunden über unklare Preise geäußert haben.', 'Solche Rückmeldungen werden schon berichtet.']]
]);
add('listening', 'Eine Ausstellung vorbereiten', 'Ein Problem und die gemeinsam gewählte Lösung erkennen.',
['A: 写真展のポスター、入口の壁に貼ろうと思うんですが。\nB: そこは来週工事が入るそうですよ。貼っても見えなくなるかもしれません。', 'A: じゃあ、受付の横はどうですか。\nB: いいですね。ただ、あそこは広くないので、大きいのを一枚にしましょう。小さいのを何枚も貼ると、読みにくいですから。', 'A: わかりました。今日中に一枚印刷しておきます。\nB: お願いします。貼るのは、受付の担当者に確認してからにしてください。'],
'A: Ich würde das Plakat zur Fotoausstellung an die Wand am Eingang hängen. B: Dort sollen nächste Woche Bauarbeiten sein. Vielleicht sieht man es dann nicht. A: Wie wäre es neben der Anmeldung? B: Gut, aber dort ist wenig Platz. Nehmen wir ein großes statt vieler kleiner Plakate; viele wären schwer lesbar. A: Ich drucke heute eines aus. B: Danke. Hängen Sie es erst nach Rücksprache mit der zuständigen Person an der Anmeldung auf.',
[['受付（うけつけ）', 'Empfang / Anmeldung'], ['確認（かくにん）', 'Rückfrage / Bestätigung']], 'Die Zustimmung zum Ort hebt die spätere Bedingung nicht auf: Aufhängen erst nach Rücksprache.', [
['Warum wird ein anderer Ort gesucht?', 0, ['Bauarbeiten könnten das Plakat am Eingang verdecken.', 'B nennt 工事 und 見えなくなる als Problem.'], ['Die Ausstellung wurde abgesagt.', 'Die Vorbereitung geht weiter.'], ['Die Anmeldung wird geschlossen.', 'Dafür gibt es keine Aussage.'], ['Das Plakat ist bereits beschädigt.', 'Es soll erst gedruckt werden.']],
['Welche Plakatvariante wird gewählt?', 1, ['Ein großes Plakat.', '大きいのを一枚 ist die vereinbarte Lösung.'], ['Viele kleine Plakate.', 'Diese Variante wird wegen Lesbarkeit abgelehnt.'], ['Zwei gleich große Plakate.', '一枚 bedeutet eines.'], ['Kein gedrucktes Plakat.', 'Ein Druck ist ausdrücklich geplant.']],
['Was muss A vor dem Aufhängen noch tun?', 2, ['Bei der zuständigen Person an der Anmeldung nachfragen.', '確認してから legt diese Voraussetzung fest.'], ['Die Bauarbeiten selbst abschließen.', 'A erhält keinen Bauauftrag.'], ['Alle kleinen Plakate verteilen.', 'Gedruckt wird ein großes.'], ['Bis nach der Ausstellung warten.', 'Eine solche Verzögerung ist nicht vereinbart.']]
]);
add('listening', 'Der verspätete Zug', 'Eine ursprüngliche und eine neue Absprache auseinanderhalten.',
['A: すみません、電車が止まっていて、約束の一時には着けそうにありません。\nB: 会場には二時までに入れば大丈夫ですよ。どれくらい遅れそうですか。', 'A: 別の線で行けば、一時半には駅に着けると思います。\nB: それなら、駅で一緒に昼ご飯を食べるのはやめて、直接会場で会いましょう。', 'A: チケットを持っているのは私ですが、先に入れますか。\nB: 予約した名前を言えば入れるそうなので、心配しないでください。私は先に受付を済ませます。'],
'A: Entschuldigung, mein Zug steht. Ich schaffe die verabredete Zeit um eins wohl nicht. B: Es reicht, bis zwei im Veranstaltungsort zu sein. Wie spät wird es? A: Über eine andere Linie komme ich wohl um halb zwei am Bahnhof an. B: Dann lassen wir das gemeinsame Mittagessen am Bahnhof ausfallen und treffen uns direkt am Veranstaltungsort. A: Ich habe aber die Tickets. Können Sie vorher hinein? B: Man soll mit dem Reservierungsnamen hineinkommen, also keine Sorge. Ich erledige die Anmeldung schon vorher.',
[['直接（ちょくせつ）', 'direkt'], ['済ませる（すませる）', 'erledigen']], '一時半 ist die erwartete Ankunft am Bahnhof, nicht die Einlassfrist am Veranstaltungsort.', [
['Was ist die wichtigste Änderung?', 1, ['Das gemeinsame Essen entfällt; man trifft sich direkt am Veranstaltungsort.', '昼ご飯を食べるのはやめて und 直接会場 legen den Ersatzplan fest.'], ['Die gesamte Veranstaltung wird verschoben.', 'Nur der persönliche Plan ändert sich.'], ['Beide warten bis zwei am Bahnhof.', 'Der Treffpunkt wird gerade vom Bahnhof weg verlegt.'], ['B fährt A mit dem Auto abholen.', 'Ein Abholen wird nicht vorgeschlagen.']],
['Bis wann soll man am Veranstaltungsort hinein?', 0, ['Bis 14 Uhr.', '二時までに nennt die Frist.'], ['Bis 13 Uhr.', 'Das war die ursprüngliche Verabredung.'], ['Bis 13:30 Uhr.', 'Das ist As erwartete Ankunft am Bahnhof.'], ['Bis 12 Uhr.', 'Zwölf wird nicht genannt.']],
['Was wird B tun, bevor A eintrifft?', 2, ['Sich mit dem Reservierungsnamen anmelden.', 'B kann so hinein und will die Anmeldung vorab erledigen.'], ['Draußen zwingend auf die Papiertickets warten.', 'Der Reservierungsname ermöglicht den Einlass.'], ['Neue Tickets kaufen müssen.', 'Ein Neukauf wird nicht verlangt.'], ['Die Reservierung aufheben.', 'B nutzt die bestehende Reservierung.']]
]);
add('listening', 'Rückmeldung zum Praktikum', 'Sprecherrollen und konstruktive Kritik erschließen.',
['A: 先週お願いした売り場の記録、読みました。お客さんが何を探していたか、よく書けていますね。\nB: ありがとうございます。ただ、全部書こうとして、時間がかかってしまいました。', 'A: 実習中ですから、最初はそれでいいんです。次は同じ質問をまとめると、あとで読みやすくなりますよ。\nB: 一人ずつの順番で書かなくてもいいんですね。', 'A: ええ。目的は人数を数えることではなく、売り場で足りない案内を見つけることですから。\nB: では、今週は質問の種類ごとに整理してみます。'],
'A: Ich habe die erbetenen Aufzeichnungen aus dem Verkaufsbereich gelesen. Sie haben gut festgehalten, wonach Kunden suchten. B: Danke. Allerdings hat es lange gedauert, weil ich alles notieren wollte. A: Im Praktikum ist das anfangs in Ordnung. Fassen Sie nächstes Mal gleiche Fragen zusammen, dann lässt es sich später leichter lesen. B: Ich muss also nicht der Reihe nach jede Person erfassen. A: Genau. Es geht nicht ums Zählen, sondern darum, fehlende Hinweise im Verkaufsbereich zu finden. B: Dann ordne ich diese Woche nach Fragearten.',
[['実習（じっしゅう）', 'Praktikum / praktische Ausbildung'], ['種類ごと（しゅるいごと）', 'nach Arten / Kategorien']], 'Die Kritik betrifft die Ordnung der Beobachtungen, nicht deren Wert. Lob und Verbesserungsvorschlag können zusammenstehen.', [
['Welche Beziehung passt am besten?', 0, ['A betreut B bei einer praktischen Ausbildung.', 'A bewertet einen erteilten Auftrag; später wird 実習 ausdrücklich genannt.'], ['B verkauft A eine Eintrittskarte.', 'Es gibt keine Ticketbestellung.'], ['Beide sind zufällige Kunden ohne gemeinsame Aufgabe.', 'Ein früherer Auftrag verbindet sie.'], ['A ist ein Kind, das B um Hausaufgabenhilfe bittet.', 'Die Situation betrifft Aufzeichnungen aus einem Verkaufsbereich.']],
['Wie soll B die nächste Aufzeichnung ordnen?', 1, ['Gleiche Fragen zusammenfassen.', '同じ質問をまとめる ist der Vorschlag.'], ['Strikt nach jeder einzelnen Person.', 'Das wird als unnötig bestätigt.'], ['Nur noch die Namen der Kunden notieren.', 'Namen sind kein genanntes Ziel.'], ['Alle Fragen unverändert mehrmals abschreiben.', 'Gerade Wiederholungen sollen zusammengefasst werden.']],
['Welche Beobachtung wäre für den Auftrag besonders nützlich?', 2, ['Viele Kunden fragen nach einem schwer auffindbaren Bereich.', 'Wiederkehrende Fragen zeigen, wo Hinweise fehlen.'], ['Die genaue Reihenfolge aller vorbeigehenden Personen.', 'Die Reihenfolge ist für den Zweck nicht entscheidend.'], ['Nur die Gesamtzahl der Kunden.', '人数を数えることではなく grenzt das Ziel davon ab.'], ['Bs private Einkaufsliste.', 'Sie zeigt keinen Informationsbedarf der Kunden.']]
]);
add('listening', 'Eine Durchsage im Museum', 'Aus mehreren Ausnahmen die geltende Regel ableiten.',
['本日はご来館ありがとうございます。二階の特別展示室は、設備の点検のため、午後一時までご利用いただけません。一階の常設展示は通常どおりご覧いただけます。', '二階で予定していた十一時の作品解説は、一階の講堂に場所を変えて行います。開始時刻は変わりません。予約は不要ですが、席には限りがあります。', '特別展示の入場券をお持ちの方で、午後までお待ちになれない場合は、受付で別の日に使える券と交換いたします。現金での払い戻しではありませんので、ご注意ください。'],
'Willkommen im Museum. Wegen einer technischen Kontrolle ist die Sonderausstellung im zweiten Stock bis 13 Uhr nicht zugänglich. Die Dauerausstellung im ersten Stock ist normal geöffnet. Die für 11 Uhr im zweiten Stock geplante Werkbesprechung findet stattdessen im Vortragssaal im ersten Stock statt; die Zeit bleibt gleich. Keine Reservierung erforderlich, Plätze begrenzt. Wer ein Ticket für die Sonderausstellung hat und nicht bis nachmittags warten kann, kann es am Empfang gegen eines für einen anderen Tag tauschen. Es gibt keine Barauszahlung.',
[['常設展示（じょうせつてんじ）', 'Dauerausstellung'], ['払い戻し（はらいもどし）', 'Rückerstattung']], '場所を変えて betrifft den Ort. 開始時刻は変わりません bestätigt ausdrücklich die unveränderte Zeit.', [
['Was ist die Hauptinformation?', 0, ['Ein Teil des Museums ist vorübergehend gesperrt; andere Angebote bleiben verfügbar.', 'Sonder- und Dauerausstellung werden ausdrücklich unterschieden.'], ['Das gesamte Museum ist heute geschlossen.', 'Die Dauerausstellung ist geöffnet.'], ['Alle Führungen fallen dauerhaft aus.', 'Die Werkbesprechung findet an anderem Ort statt.'], ['Die Sonderausstellung endet heute endgültig.', 'Die Sperrung dauert bis 13 Uhr.']],
['Wo und wann findet die Werkbesprechung statt?', 1, ['Um 11 Uhr im Vortragssaal im ersten Stock.', 'Ort wird ersetzt, Zeit bleibt gleich.'], ['Um 13 Uhr im zweiten Stock.', 'Das verwechselt Wiederöffnung und Besprechung.'], ['Um 11 Uhr vor dem Museum.', 'Es wird ein Saal im ersten Stock genannt.'], ['Nur nach vorheriger Reservierung um 12 Uhr.', 'Reservierung ist nicht nötig und die Zeit ist falsch.']],
['Du kannst mit Sonderausstellungsticket nicht warten. Welche Lösung wird angeboten?', 2, ['Am Empfang gegen ein Ticket für einen anderen Tag tauschen.', '別の日に使える券と交換 nennt die Alternative.'], ['Den vollen Preis bar zurückerhalten.', 'Eine Barauszahlung wird ausdrücklich ausgeschlossen.'], ['Trotz Sperrung sofort in den zweiten Stock gehen.', 'Die Sonderausstellung bleibt bis 13 Uhr unzugänglich.'], ['Das Ticket ohne Ersatz abgeben müssen.', 'Es gibt einen Umtausch.']]
]);
add('listening', 'Die Gruppe entscheidet', 'Argumente und abschließende Entscheidung zusammenführen.',
['A: サークル旅行、海と山のどちらにしましょう。海の宿は安いですが、駅からバスで一時間かかります。\nB: 今回は土曜の仕事が終わってから来る人もいるので、移動が長いのは困りますね。', 'A: 山の宿なら駅まで迎えに来てくれます。ただ、海より一人二千円高いです。\nB: 予算を少し超えますが、夕食も含まれているんですよね。海の宿は食事が別でした。', 'A: そうです。じゃあ、今回は山にしましょう。予約の前に、遅く来る人も夕食を取っておいてもらえるか、聞いてみます。\nB: それが確認できたら、みんなに金額を知らせましょう。'],
'A: Soll unsere Vereinsreise ans Meer oder in die Berge gehen? Die Unterkunft am Meer ist günstig, aber eine Busstunde vom Bahnhof entfernt. B: Einige kommen erst nach der Arbeit am Samstag; eine lange Weiterfahrt ist schwierig. A: Die Unterkunft in den Bergen holt uns am Bahnhof ab, kostet aber pro Person 2.000 Yen mehr. B: Etwas über Budget, aber Abendessen ist enthalten, während es am Meer extra kostet. A: Dann nehmen wir dieses Mal die Berge. Vor dem Buchen frage ich, ob Essen für Spätankommende aufgehoben werden kann. B: Sobald das geklärt ist, teilen wir allen den Betrag mit.',
[['予算（よさん）', 'Budget'], ['取っておく（とっておく）', 'aufheben / zurücklegen']], 'Eine gewählte Option kann noch von einer organisatorischen Rückfrage abhängen. 予約の前に kennzeichnet den noch offenen Schritt.', [
['Welches Problem spricht gegen die Unterkunft am Meer?', 0, ['Die lange Weiterfahrt wäre für spät Anreisende ungünstig.', 'B verknüpft späte Anreise nach der Arbeit mit der Busfahrt.'], ['Sie ist teurer als die Unterkunft in den Bergen.', 'Ihr Grundpreis ist niedriger.'], ['Sie hat keinen Bahnhof in der Region.', 'Eine Busverbindung ab Bahnhof ist genannt.'], ['Alle wollen ausschließlich schwimmen.', 'Ein solcher Wunsch wird nicht geäußert.']],
['Was ist beim höheren Preis der Bergunterkunft enthalten?', 1, ['Das Abendessen.', '夕食も含まれている bestätigt die enthaltene Leistung.'], ['Die gesamte Zugfahrt.', 'Genannt wird Abholung am Bahnhof, nicht der Zugpreis.'], ['Ein zusätzliches Zimmer für jeden.', 'Die Zimmerverteilung wird nicht besprochen.'], ['Ein Ausflug zum Meer.', 'Das ist kein genannter Bestandteil.']],
['Was tut A vor der Buchung?', 2, ['Fragen, ob Abendessen für spät Ankommende aufgehoben werden kann.', 'Diese Rückfrage wird ausdrücklich vor die Buchung gesetzt.'], ['Sofort die billigere Meeresunterkunft buchen.', 'Die Gruppe hat sich für die Berge entschieden.'], ['Allen bereits eine bestätigte Essenszusage schicken.', 'Die Zusage steht noch aus.'], ['Die Reise ohne weitere Rückfrage absagen.', 'Die Gruppe will die Reise durchführen.']]
]);
require('./n3-expansion.cjs')(add);
};
