module.exports = add => {
add('reading', 'Eine E-Mail zur Lerngruppe', 'Eine Terminänderung und ihren Grund verstehen.',
['みなさんへ。あしたの{勉強会|べんきょうかい}は、{図書館|としょかん}ではなく、{駅|えき}の{近|ちか}くのカフェでします。{図書館|としょかん}が{休|やす}みだからです。', '{始|はじ}まる{時間|じかん}は{前|まえ}と{同|おな}じで、{午後|ごご}{三時|さんじ}です。カフェは{二階|にかい}にあります。', '{飲|の}み{物|もの}を{一|ひと}つ{注文|ちゅうもん}してください。{食|た}べ{物|もの}は{注文|ちゅうもん}しなくてもいいです。ノートを{忘|わす}れないでください。'],
'An alle: Die morgige Lerngruppe trifft sich nicht in der Bibliothek, sondern im Café nahe dem Bahnhof, weil die Bibliothek geschlossen ist. Die Anfangszeit bleibt bei 15 Uhr. Das Café ist im zweiten Stock. Bestellt bitte ein Getränk. Essen muss nicht bestellt werden. Vergesst euer Heft nicht.',
[['ではなく', 'nicht …, sondern …'], ['注文（ちゅうもん）', 'Bestellung']], 'しなくてもいい drückt aus, dass etwas nicht nötig ist. Es verbietet keine Essensbestellung.', [
['Was ist die wichtigste Nachricht?', 0, ['Der Ort ändert sich wegen der geschlossenen Bibliothek.', 'ではなく ersetzt die Bibliothek durch das Café und だから nennt den Grund.'], ['Die Lerngruppe fällt aus.', 'Sie findet im Café statt.'], ['Die Bibliothek öffnet später.', 'Sie ist geschlossen; eine spätere Öffnung steht nicht da.'], ['Die Gruppe trifft sich ab jetzt jeden Tag.', 'Die Nachricht betrifft nur morgen.']],
['Was bleibt unverändert?', 1, ['Der Beginn um 15 Uhr.', '前と同じ bezieht sich auf die Startzeit.'], ['Der Raum in der Bibliothek.', 'Der Ort ändert sich.'], ['Das Stockwerk des Treffpunkts.', 'Es wird kein altes Stockwerk verglichen.'], ['Die Getränkepreise.', 'Preise werden nicht genannt.']],
['Was erfüllt die Bitte?', 2, ['Ein Heft mitbringen und ein Getränk bestellen.', 'Beides wird verlangt; Essen ist optional.'], ['Nur Essen bestellen und das Heft zu Hause lassen.', 'Getränk und Heft fehlen.'], ['Nichts bestellen.', 'Ein Getränk soll bestellt werden.'], ['Unbedingt eine ganze Mahlzeit bestellen.', 'Essen ist ausdrücklich nicht nötig.']]
]);
add('reading', 'Ein Paket abholen', 'Aus einer Mitteilung gültige Abholbedingungen entnehmen.',
['お{荷物|にもつ}を{届|とど}けに{来|き}ましたが、お{留守|るす}でした。お{荷物|にもつ}は{駅前|えきまえ}の{店|みせ}で{預|あず}かっています。', 'あしたから{三日間|みっかかん}、{午前|ごぜん}{九時|くじ}から{午後|ごご}{七時|しちじ}まで{受|う}け{取|と}れます。{今日|きょう}は{受|う}け{取|と}れません。', 'この{紙|かみ}と、なまえがわかるものを{持|も}ってきてください。{家族|かぞく}も{受|う}け{取|と}れますが、その{人|ひと}のなまえがわかるものも{必要|ひつよう}です。'],
'Wir wollten Ihr Paket zustellen, aber Sie waren nicht zu Hause. Es liegt im Geschäft vor dem Bahnhof. Ab morgen können Sie es drei Tage lang von 9 bis 19 Uhr abholen, heute noch nicht. Bringen Sie diesen Zettel und einen Nachweis Ihres Namens mit. Auch Angehörige können es abholen, brauchen aber zusätzlich einen Nachweis ihres eigenen Namens.',
[['留守（るす）', 'Abwesenheit von zu Hause'], ['預かっています（あずかっています）', 'aufbewahren / in Verwahrung haben']], 'あしたから三日間 ist eine Frist ab morgen, kein Termin erst in drei Tagen.', [
['Warum liegt dieser Zettel vor?', 0, ['Eine Zustellung war wegen Abwesenheit nicht möglich.', '留守でした erklärt den erfolglosen Zustellversuch.'], ['Das Paket wurde bereits abgeholt.', 'Es wird noch aufbewahrt.'], ['Die Empfängeradresse ist unbekannt.', 'Als Grund wird Abwesenheit genannt.'], ['Das Geschäft hat geschlossen.', 'Es werden Abholzeiten angegeben.']],
['Wann ist eine Abholung möglich?', 1, ['Morgen um 10 Uhr.', 'Das liegt ab morgen innerhalb von 9 bis 19 Uhr.'], ['Heute um 10 Uhr.', 'Heute ist ausdrücklich ausgeschlossen.'], ['Morgen um 20 Uhr.', 'Die Abholung endet um 19 Uhr.'], ['Erst nach drei vollen Tagen.', 'Die Frist beginnt schon morgen.']],
['Was braucht eine abholende Angehörige zusätzlich?', 2, ['Einen Nachweis ihres eigenen Namens.', 'その人のなまえ bezieht sich auf die abholende Person.'], ['Einen Schlüssel zur Wohnung.', 'Ein Schlüssel wird nicht verlangt.'], ['Eine neue Bestellung.', 'Es geht um ein vorhandenes Paket.'], ['Nichts; Angehörige brauchen keine Nachweise.', 'も必要です verlangt einen zusätzlichen Nachweis.']]
]);
add('reading', 'Der erste Arbeitstag', 'Die Reihenfolge einer Alltagserzählung nachvollziehen.',
['きのう、パン{屋|や}でアルバイトを{始|はじ}めました。{店|みせ}に{着|つ}いてから、{先輩|せんぱい}にあいさつしました。', 'はじめに{手|て}を{洗|あら}って、エプロンをつけました。それから、パンを{袋|ふくろ}に{入|い}れる{練習|れんしゅう}をしました。レジはまだ{使|つか}いませんでした。', '{袋|ふくろ}に{入|い}れるのは{簡単|かんたん}だと{思|おも}っていましたが、パンがやわらかくて、むずかしかったです。あした、もう{一度|いちど}{練習|れんしゅう}します。'],
'Gestern habe ich meinen Nebenjob in einer Bäckerei angefangen. Nach der Ankunft begrüßte ich eine erfahrene Kollegin bzw. einen erfahrenen Kollegen. Zuerst wusch ich die Hände und zog eine Schürze an. Dann übte ich, Brot in Tüten zu packen. Die Kasse benutzte ich noch nicht. Ich hatte das Verpacken für einfach gehalten, doch das weiche Brot machte es schwierig. Morgen übe ich noch einmal.',
[['先輩（せんぱい）', 'erfahrenere Person in derselben Gruppe'], ['やわらかい', 'weich']], 'と思っていました beschreibt eine frühere Erwartung. が zeigt hier, dass die Erfahrung anders war.', [
['Wie erlebte die Person den ersten Arbeitstag?', 2, ['Eine vermeintlich einfache Aufgabe erwies sich als schwierig.', '簡単だと思っていましたが markiert den Gegensatz zwischen Erwartung und Erfahrung.'], ['Alles war so leicht wie erwartet.', 'むずかしかった widerspricht dem.'], ['Die Arbeit fiel vollständig aus.', 'Mehrere Arbeitsschritte wurden geübt.'], ['Die Kassenarbeit war am schwersten.', 'Die Kasse wurde noch nicht benutzt.']],
['Was tat die Person vor dem Verpacken?', 1, ['Hände waschen und eine Schürze anziehen.', 'はじめに und それから ordnen die Schritte.'], ['An der Kasse arbeiten.', 'レジはまだ使いませんでした schließt das aus.'], ['Neue Brote backen.', 'Backen wird nicht erwähnt.'], ['Nach Hause gehen.', 'Das Verpacken fand bei der Arbeit statt.']],
['Warum wird morgen weiter geübt?', 2, ['Weiches Brot lässt sich nicht so leicht einpacken.', 'やわらかくて nennt den Grund für die Schwierigkeit.'], ['Die Begrüßung wurde vergessen.', 'Die Begrüßung fand statt.'], ['Die Kasse war kaputt.', 'Eine Störung wird nicht genannt.'], ['Alle Tüten wurden verkauft.', 'Es fehlt nicht an Tüten.']]
]);
add('reading', 'So funktioniert die Waschmaschine', 'Bedingte Anweisungen in die richtige Reihenfolge bringen.',
['この{洗濯機|せんたくき}は、{洗剤|せんざい}が{自動|じどう}で{出|で}ます。じぶんで{入|い}れないでください。', '{服|ふく}を{入|い}れて、ドアを{閉|し}めてから、{三百円|さんびゃくえん}を{入|い}れてください。{赤|あか}いボタンを{押|お}すと{始|はじ}まります。', '{三十分|さんじゅっぷん}ぐらいかかります。{終|お}わってもドアが{開|あ}かないときは、{一分|いっぷん}{待|ま}ってください。それでも{開|あ}かなければ、{店|みせ}の{人|ひと}を{呼|よ}んでください。'],
'Diese Waschmaschine gibt Waschmittel automatisch hinzu. Füllen Sie selbst keines ein. Legen Sie die Kleidung hinein und schließen Sie die Tür, bevor Sie 300 Yen einwerfen. Mit dem roten Knopf startet sie. Es dauert etwa 30 Minuten. Öffnet sich danach die Tür nicht, warten Sie eine Minute. Wenn sie sich dann immer noch nicht öffnet, rufen Sie das Personal.',
[['洗剤（せんざい）', 'Waschmittel'], ['それでも', 'selbst dann / trotzdem']], 'それでも verbindet den letzten Schritt mit dem erfolglosen Warten. Nicht jede verschlossene Tür verlangt sofort Hilfe.', [
['Wozu dient der Text?', 0, ['Zur richtigen Benutzung einer Waschmaschine.', '洗濯機 und die Anweisungen beschreiben die Bedienung.'], ['Zum Verkauf von Kleidung.', 'Kleidung soll gewaschen werden.'], ['Zum Reparieren aller Haushaltsgeräte.', 'Die Anleitung betrifft genau diese Maschine.'], ['Zum Herstellen von Waschmittel.', 'Waschmittel wird automatisch dosiert.']],
['Wann wirft man Geld ein?', 1, ['Nach dem Einlegen der Kleidung und Schließen der Tür.', '閉めてから legt diese Reihenfolge fest.'], ['Bevor man die Kleidung einlegt.', 'Die genannte Reihenfolge ist umgekehrt.'], ['Erst nach dem Waschgang.', 'Das Geld wird vor dem Start eingeworfen.'], ['Nach jedem Drücken des roten Knopfs.', 'Es wird nur ein Einwurf vor dem Start beschrieben.']],
['Die Tür bleibt nach Ende und einer Minute Warten zu. Was nun?', 2, ['Das Personal rufen.', 'それでも開かなければ löst diesen Schritt aus.'], ['Noch mehr Waschmittel einfüllen.', 'Eigenes Waschmittel ist ausdrücklich untersagt.'], ['Sofort einen neuen Waschgang bezahlen.', 'Ein weiterer Waschgang wird nicht empfohlen.'], ['Die Tür mit Gewalt öffnen.', 'Stattdessen soll man Hilfe holen.']]
]);
add('reading', 'Welcher Kurs passt?', 'Zwei Angebote mit persönlichen Bedingungen vergleichen.',
['{料理|りょうり}{教室|きょうしつ}Ａ：{土曜日|どようび}の{午前|ごぜん}。{魚|さかな}の{料理|りょうり}を{作|つく}ります。{一回|いっかい}{二千円|にせんえん}。{材料|ざいりょう}は{教室|きょうしつ}で{用意|ようい}します。', '{料理|りょうり}{教室|きょうしつ}Ｂ：{日曜日|にちようび}の{午後|ごご}。{野菜|やさい}の{料理|りょうり}を{作|つく}ります。{一回|いっかい}{千五百円|せんごひゃくえん}。{材料|ざいりょう}は{教室|きょうしつ}で{用意|ようい}します。', 'どちらも{初心者|しょしんしゃ}が{参加|さんか}できます。エプロンだけ{持|も}ってきてください。{参加|さんか}したい{日|ひ}の{三日前|みっかまえ}までに{電話|でんわ}してください。'],
'Kochkurs A: Samstagvormittag, Fischgerichte, 2.000 Yen pro Termin. Zutaten werden gestellt. Kochkurs B: Sonntagnachmittag, Gemüsegerichte, 1.500 Yen pro Termin. Zutaten werden gestellt. Beide sind für Anfänger offen. Bringen Sie nur eine Schürze mit. Rufen Sie spätestens drei Tage vor dem gewünschten Termin an.',
[['初心者（しょしんしゃ）', 'Anfänger/in'], ['までに', 'spätestens bis (Frist)']], 'までに bezeichnet eine Frist. Die Vorbereitung „nur Schürze“ gilt für beide Kurse.', [
['Was haben beide Angebote gemeinsam?', 2, ['Auch Anfänger können teilnehmen.', 'どちらも bezieht sich auf beide Kochkurse.'], ['Beide finden samstags statt.', 'B findet sonntags statt.'], ['Beide kosten 1.500 Yen.', 'A kostet 2.000 Yen.'], ['Beide bereiten Fisch zu.', 'B kocht Gemüsegerichte.']],
['Was wird bei Kurs B gestellt?', 1, ['Die Zutaten.', '材料は教室で用意します nennt die Leistung.'], ['Eine Schürze für jede Person.', 'Die Schürze soll man selbst mitbringen.'], ['Ein kostenloses Telefon.', '電話する ist die Anmeldung, keine Ausstattung.'], ['Ein Fischgericht aus Kurs A.', 'B behandelt Gemüsegerichte.']],
['Du bist Anfänger, kannst nur sonntags und hast 1.500 Yen. Was passt?', 1, ['Kurs B, mit rechtzeitiger telefonischer Anmeldung.', 'Tag und Preis von B passen; die gemeinsame Frist gilt auch hier.'], ['Kurs A ohne Anmeldung.', 'Tag, Preis und Anmeldung passen nicht.'], ['Beide Kurse ohne Schürze.', 'A passt zeitlich nicht; eine Schürze ist mitzubringen.'], ['Keiner, da Anfänger ausgeschlossen sind.', 'Anfänger sind bei beiden willkommen.']]
]);
add('listening', 'Eine Bitte im Büro', 'Eine Bitte und die gewünschte Anzahl verstehen.',
['A: この{資料|しりょう}をコピーしてもらえますか。{会議|かいぎ}は{二時|にじ}からです。\nB: はい。{十枚|じゅうまい}でいいですか。', 'A: いえ、{二人|ふたり}{増|ふ}えたので、{十二枚|じゅうにまい}おねがいします。', 'B: わかりました。\nA: コピーしたら、{会議室|かいぎしつ}の{机|つくえ}の{上|うえ}に{置|お}いてください。'],
'A: Könnten Sie diese Unterlage kopieren? Die Besprechung beginnt um zwei. B: Ja. Reichen zehn Kopien? A: Nein, zwei Personen sind hinzugekommen, also bitte zwölf. B: Verstanden. A: Legen Sie die Kopien danach auf den Tisch im Besprechungsraum.',
[['資料（しりょう）', 'Unterlagen'], ['増えた（ふえた）', 'mehr geworden / hinzugekommen']], 'Die erste Zahl ist eine Rückfrage, die zweite die endgültige Menge.', [
['Was soll B übernehmen?', 0, ['Unterlagen für eine Besprechung kopieren.', 'コピーしてもらえますか formuliert die Bitte.'], ['Den Beginn der Besprechung verschieben.', 'Die Zeit wird nur genannt.'], ['Neue Mitarbeiter einstellen.', 'Die zusätzlichen Personen begründen die Menge.'], ['Einen Tisch kaufen.', 'Der Tisch ist Ablageort.']],
['Wie viele Kopien werden benötigt?', 1, ['Zwölf.', '十二枚 ist die korrigierte Menge.'], ['Zehn.', 'Zehn wird ausdrücklich korrigiert.'], ['Zwei.', 'Zwei Personen kommen zusätzlich dazu.'], ['Vierzehn.', 'Die zwei zusätzlichen Personen sind in zwölf schon enthalten.']],
['Was tut B nach dem Kopieren?', 2, ['Die Unterlagen auf den Tisch im Besprechungsraum legen.', 'コピーしたら nennt die nächste Handlung.'], ['Alle Unterlagen nach Hause bringen.', 'Als Ort ist der Besprechungsraum genannt.'], ['Zwei Kopien wegwerfen.', 'Alle zwölf werden benötigt.'], ['Die Unterlagen in der Küche ablegen.', 'Die Küche wird nicht genannt.']]
]);
add('listening', 'Picknick bei Regen', 'Einen geänderten Plan samt Bedingung nachvollziehen.',
['A: あしたのピクニック、{雨|あめ}でも{行|い}きますか。\nB: {朝|あさ}から{雨|あめ}だそうですから、{公園|こうえん}はやめましょう。', 'A: じゃあ、{映画|えいが}はどうですか。\nB: いいですね。{駅|えき}に{十一時|じゅういちじ}ではなく、{十時半|じゅうじはん}に{集|あつ}まりましょう。', 'A: おべんとうはいりませんね。\nB: はい。{映画|えいが}のあとで、みんなで{食|た}べに{行|い}きましょう。'],
'A: Machen wir das Picknick morgen auch bei Regen? B: Es soll schon morgens regnen, lassen wir den Park ausfallen. A: Wie wäre es mit Kino? B: Gut. Treffen wir uns am Bahnhof um halb elf statt um elf. A: Dann brauchen wir kein mitgebrachtes Mittagessen. B: Genau. Nach dem Film gehen wir zusammen essen.',
[['だそうです', 'es heißt / man hat gehört'], ['集まる（あつまる）', 'sich versammeln / treffen']], 'ではなく ersetzt eine frühere Angabe. Merke dir die Zeit nach dieser Wendung.', [
['Warum wird der Ausflug geändert?', 0, ['Weil für den Morgen Regen angekündigt ist.', '雨だそうですから nennt den Grund.'], ['Weil der Park zu teuer ist.', 'Kosten werden nicht erwähnt.'], ['Weil niemand Zeit hat.', 'Die Gruppe plant weiterhin gemeinsam etwas.'], ['Weil das Kino geschlossen ist.', 'Das Kino wird als Alternative gewählt.']],
['Wann ist der neue Treffpunkt am Bahnhof?', 1, ['Um 10:30 Uhr.', '十時半 ersetzt 十一時.'], ['Um 11 Uhr.', 'Diese Zeit wird zurückgenommen.'], ['Um 11:30 Uhr.', 'Es heißt 十時半.'], ['Um 10 Uhr.', '半 ergänzt eine halbe Stunde.']],
['Wie sollte A das Essen planen?', 2, ['Kein Bento mitbringen; nach dem Film gemeinsam essen.', 'Beide bestätigen diesen Ablauf.'], ['Ein Bento für den Park mitbringen.', 'Der Parkplan wurde aufgegeben.'], ['Vor dem Treffen allein essen müssen.', 'Eine solche Pflicht wird nicht genannt.'], ['Im Kino kochen.', '食べに行く heißt essen gehen.']]
]);
add('listening', 'Das geliehene Buch', 'Rückgabefrist und Rückgabeweg unterscheiden.',
['A: {借|か}りた{本|ほん}、あした{返|かえ}してもいいですか。きょうは{学校|がっこう}に{行|い}けなくなって。', 'B: {金曜日|きんようび}まで{使|つか}わないから、あしたで{大丈夫|だいじょうぶ}ですよ。でも、わたしは{午後|ごご}いません。', 'A: じゃあ、{午前中|ごぜんちゅう}にあなたの{教室|きょうしつ}へ{持|も}っていきます。\nB: おねがいします。{友|とも}だちに{預|あず}けなくていいですよ。'],
'A: Darf ich das geliehene Buch morgen zurückgeben? Ich kann heute doch nicht zur Schule kommen. B: Ich brauche es erst am Freitag, morgen ist also in Ordnung. Aber nachmittags bin ich nicht da. A: Dann bringe ich es vormittags in deinen Klassenraum. B: Danke. Du brauchst es nicht bei einem Freund zu hinterlegen.',
[['返す（かえす）', 'zurückgeben'], ['午前中（ごぜんちゅう）', 'im Laufe des Vormittags']], '使わないから erklärt die Flexibilität, ist aber nicht der vereinbarte Rückgabetermin.', [
['Was möchte A klären?', 0, ['Ob die Buchrückgabe auf morgen verschoben werden kann.', 'あした返してもいいですか bittet um Erlaubnis.'], ['Ob A ein Buch kaufen kann.', 'Das Buch ist bereits geliehen.'], ['Ob die Schule freitags geschlossen ist.', 'Freitag betrifft Bs Bedarf.'], ['Ob B heute ein neues Buch leiht.', 'Es geht um Rückgabe.']],
['Wann ist B morgen nicht da?', 1, ['Am Nachmittag.', '午後いません nennt die Abwesenheit.'], ['Am Vormittag.', 'Für den Vormittag wird später die Übergabe geplant.'], ['Den ganzen Tag.', 'Nur der Nachmittag ist ausgeschlossen.'], ['Erst ab Freitag.', 'Freitag ist der Tag, an dem das Buch gebraucht wird.']],
['Wie gibt A das Buch zurück?', 2, ['Morgen vormittags direkt in Bs Klassenraum.', 'A kündigt dies an, B stimmt zu.'], ['Heute über einen Freund.', 'Heute kann A nicht kommen; Hinterlegen ist nicht nötig.'], ['Freitagnachmittag am Bahnhof.', 'Dieser Termin und Ort werden nicht vereinbart.'], ['Morgen Nachmittag in der Bibliothek.', 'B ist dann abwesend; der Ort stimmt nicht.']]
]);
add('listening', 'Ein Zimmer reservieren', 'Mehrere Bedingungen einer Reservierung zusammenführen.',
['A: {土曜日|どようび}に{一泊|いっぱく}したいんですが、{二人|ふたり}の{部屋|へや}はありますか。\nB: はい。{朝|あさ}ごはんがつく{部屋|へや}と、つかない{部屋|へや}があります。', 'A: {朝|あさ}は{早|はや}く{出|で}るので、{朝|あさ}ごはんはいりません。\nB: では、お{二人|ふたり}で{八千円|はっせんえん}です。', 'A: {車|くるま}で{行|い}きます。\nB: {駐車場|ちゅうしゃじょう}は{無料|むりょう}ですが、{予約|よやく}が{必要|ひつよう}です。\nA: じゃあ、{車|くるま}{一台|いちだい}もおねがいします。'],
'A: Ich möchte Samstag eine Nacht bleiben. Haben Sie ein Zimmer für zwei? B: Ja, mit oder ohne Frühstück. A: Wir fahren morgens früh ab und brauchen kein Frühstück. B: Dann kostet es für Sie beide 8.000 Yen. A: Wir kommen mit dem Auto. B: Parken ist kostenlos, aber eine Reservierung ist nötig. A: Dann bitte auch einen Stellplatz für ein Auto.',
[['一泊（いっぱく）', 'eine Übernachtung'], ['駐車場（ちゅうしゃじょう）', 'Parkplatz']], '無料 bedeutet kostenlos, nicht automatisch ohne Reservierung. Kosten und Buchungsbedingungen sind getrennte Informationen.', [
['Was möchte A buchen?', 0, ['Ein Zimmer für zwei für eine Nacht am Samstag.', '土曜日、一泊 und 二人 bestimmen die Buchung.'], ['Zwei Zimmer für eine Woche.', 'Weder zwei Zimmer noch eine Woche werden verlangt.'], ['Nur ein Frühstück am Sonntag.', 'Es geht um Übernachtung.'], ['Ein Auto für zwei Tage.', 'A reist mit dem eigenen Auto an.']],
['Warum wird ohne Frühstück gebucht?', 1, ['Die Gäste fahren früh ab.', '早く出るので begründet den Verzicht.'], ['Das Frühstück kostet 8.000 Yen.', '8.000 Yen ist der Gesamtpreis der Übernachtung.'], ['Es gibt samstags kein Frühstück.', 'Frühstück wird als Option angeboten.'], ['Nur eine Person isst morgens.', 'Das wird nicht gesagt.']],
['Welche zusätzliche Reservierung erfolgt?', 2, ['Ein kostenloser Stellplatz für ein Auto.', 'A bittet nach dem Hinweis auf Reservierung um 一台.'], ['Zwei kostenpflichtige Stellplätze.', 'Ein Auto und kostenlose Nutzung sind genannt.'], ['Ein Frühstück für den Fahrer.', 'Frühstück wurde abgewählt.'], ['Keine, da kostenlose Parkplätze nie gebucht werden müssen.', '予約が必要です sagt das Gegenteil.']]
]);
add('listening', 'Vor dem Schulfest', 'Zuständigkeiten und Reihenfolge selbstständig erfassen.',
['A: {明日|あした}のお{祭|まつ}りの{準備|じゅんび}、{何|なに}からしましょうか。\nB: まず、{体育館|たいいくかん}にいすを{運|はこ}びましょう。', 'A: ポスターはもう{貼|は}りましたか。\nB: まだですが、それは{山田|やまだ}さんがしてくれます。わたしたちはいすのあとで{机|つくえ}を{並|なら}べましょう。', 'A: わかりました。{掃除|そうじ}もしますか。\nB: {掃除|そうじ}は{今朝|けさ}{終|お}わりました。{机|つくえ}まで{終|お}わったら、{先生|せんせい}に{知|し}らせてください。'],
'A: Womit sollen wir die Vorbereitung für das morgige Fest beginnen? B: Bringen wir zuerst die Stühle in die Turnhalle. A: Hängen die Plakate schon? B: Noch nicht, aber das übernimmt Yamada. Wir stellen nach den Stühlen die Tische auf. A: Verstanden. Sollen wir auch putzen? B: Das ist seit heute Morgen erledigt. Wenn auch die Tische fertig sind, gib bitte der Lehrkraft Bescheid.',
[['運ぶ（はこぶ）', 'transportieren'], ['知らせる（しらせる）', 'Bescheid geben']], 'まだ und もう unterscheiden offene und abgeschlossene Aufgaben. Offene Aufgaben können dennoch einer anderen Person gehören.', [
['Was koordinieren die beiden?', 0, ['Die Vorbereitung eines Fests in der Schule.', '祭りの準備 und 体育館 bestimmen Anlass und Umgebung.'], ['Den Kauf neuer Schulmöbel.', 'Möbel werden transportiert, nicht gekauft.'], ['Einen Sportwettkampf heute Morgen.', 'Das Fest ist morgen.'], ['Eine Unterrichtsstunde über Poster.', 'Die Plakate sind eine praktische Aufgabe.']],
['Wer hängt die Plakate auf?', 1, ['Yamada.', 'それは山田さんがしてくれます weist die Aufgabe zu.'], ['A und B gemeinsam.', 'Sie übernehmen Stühle und Tische.'], ['Die Lehrkraft.', 'Sie soll später informiert werden.'], ['Niemand; die Plakate hängen bereits.', 'まだ sagt, dass sie noch nicht hängen.']],
['Was soll A nach Stühlen und Tischen tun?', 2, ['Der Lehrkraft Bescheid geben.', '机まで終わったら leitet den letzten Schritt ein.'], ['Noch einmal die Halle putzen.', 'Das Putzen ist bereits erledigt.'], ['Yamadas Plakate abnehmen.', 'Das wird nicht verlangt.'], ['Sofort nach Hause gehen, ohne etwas zu sagen.', 'Es soll ausdrücklich Bescheid gegeben werden.']]
]);
require('./n4-expansion.cjs')(add);
};
